### ISSUE TITLE
Using function for icon in weather widget

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#10]
https://github.com/resoai/TileBoard/commit/68e3ee00982dff88193b6a4b8a4c0785e10702a1 added the ability to use a function for `icons:` for widgets, but this doesn't seem to work for the weather widget since it uses a different method of specifying and showing an icon.

Backstory: https://community.home-assistant.io/t/new-dashboard-for-ha/57173/122?u=cgarwood

Weather widget uses this instead of the `icons:` directive.
```
fields: {
  icon: 'clear-day',
  iconMap: { 
    'clear-day': 'clear'
  },
}
```

**Comment by Evgeny-** [comment]
Please check this out https://github.com/resoai/TileBoard/commit/3121ed341a2b972810e69ec69bc23fb6eb00c98e

**Comment by cgarwood** [comment]
That works perfect. Thanks!
