### ISSUE TITLE
menu on the bottom in mobile layout overlaps tiles

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#100]
When:
 - Using mobile layout (`customTheme: CUSTOM_THEMES.MOBILE`)
 - Having menu on the bottom (`menuPosition: MENU_POSITIONS.BOTTOM`)
 - There is enough tiles to enable page scrolling
 - Page is scrolled to the very bottom

then the bottom menu partially overlaps bottom tiles which, depending on the overlapped tiles, might make it harder/impossible to interact with them.

See a screenshot:
![mobile-toolbar](https://user-images.githubusercontent.com/153197/42924778-013afaaa-8b2c-11e8-87ad-c85e3a4b2d22.png)

It should be possible to scroll more so that tile is not overlapped by menu.

**Comment by Evgeny-** [comment]
Just add little bit to the height of group. e.g. + 0.5

**Comment by Evgeny-** [comment]
Probably bottom margin of group also should work

**Comment by resoai** [comment]
Presume the matter is resolved and we can close this one?

**Comment by rchl** [comment]
While I appreciate how customisable this project is and how easily we can workaround issues, I think this should still be fixed in core.

It would be easy to fix it for mobile layout, but I think it should be fixed for all themes which would be quite a bit more work. Basically make sure that it's always possible to scroll page so that tiles are unobstructed by toolbar. For non-mobile layouts toolbar is even bigger so it's even easier to make it obstruct tiles if there is enough content vertically.

**Comment by resoai** [comment]
For non-mobile themes which  have page menu on the left, having menu  overlap the tiles is kinda a feature.

**Comment by rchl** [comment]
I'm only talking about menu on the bottom. I haven't seen menu on the left obstructing tiles.

**Comment by rchl** [comment]
OK, I see it. But in that case there is no problem as it's possible to scroll page all the way to the left (or right, depending how you look at it) and then no tiles are obstructed.

**Comment by resoai** [comment]
Would you be able to provide a PR of what you think would be the best fix? Please keep in mind that we should only edit .less.

**Comment by rchl** [comment]
For my specific issue the fix could be:

```diff
diff --git a/styles/themes.less b/styles/themes.less
index 37c1a58..56c282f 100644
--- a/styles/themes.less
+++ b/styles/themes.less
@@ -151,6 +151,18 @@
          }
       }
    }
+
+   &.-menu-bottom {
+      .page {
+         padding-bottom: 44px;
+      }
+
+      @media (min-width: 500px) {
+         .page {
+            padding-bottom: 56px;
+         }
+      }
+   }
 }

 .-theme-mobile, .-theme-winphone {
```
But as I said, all themes should have similar fix (this change only handles MOBILE and WINPHONE). I could probably work on full fix in soon future, if you are not gonna handle it before.

**Comment by resoai** [comment]
I'd love to get people on board so it could become a joint project.

**Comment by resoai** [comment]
Thanks for the commit. Believe we can close it.
