### ISSUE TITLE
Transparent portions of page menu toolbar should allow click-through

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#104]
If there is enough tiles to trigger either horizontal or vertical scrolling then the tiles might end up under the transparent part of the page menu toolbar and while it looks like it should still be possible to click those tiles, they are obstructed by invisible toolbar and can't be clicked.

In themes that have that toolbar transparent, we should probably use pointer-events none on those regions without buttons.

Here you can see areas highlighted in red where clicking won't trigger action on tiles beneath:
![unclickable-area](https://user-images.githubusercontent.com/153197/43035264-f1aba45a-8cec-11e8-849b-48edc3cde201.png)

**Comment by rchl** [comment]
The fix should not apply themes that don't have transparent toolbar like homekit or winphone.

**Comment by Evgeny-** [comment]
They are shouldn't

**Comment by rchl** [comment]
I don't understand your last comment and why it was closed.

Do you mean that tiles shouldn't be clickable even though they are clearly unobstructed. Don't you think that's quite counter-intuitive?

**Comment by Evgeny-** [comment]
No. Because menu don't suppose to be above tiles. except mobile themes with vertical align.

**Comment by rchl** [comment]
@resoai said that horizontal scrolling is by design and that problem affect horizontal scrolling also. I don't understand why vertical scrolling would be unexpected. It doesn't cost anything to support that
(and if you insist on not supporting it, maybe disable vertical scrolling explicitly).

**Comment by Evgeny-** [comment]
Vertical scroll supported with vertical menu or with mobile theme. Though you still can make pull request with solving this "problem"

**Comment by rchl** [comment]
I've created solution that instead of making that transparent menu area clickable, just darkens the area so that it's clear that the tiles underneath can't be clicked.

It looks like this:
<img width="286" alt="darkened" src="https://user-images.githubusercontent.com/153197/43267315-e95c2a86-90ed-11e8-96dc-1de7d578a4f9.png">
