### ISSUE TITLE
switchPercents returns NaN if brightness is 0

### ISSUE THREAD

**Issue by vpnmaster** [resoai/TileBoard#11]
I'm using several lights platforms.
Lifx lights allows you to set the brightness to zero (they don't turned off).
Is it possible for switchPercents to return 0% instead of NaN?

**Comment by Evgeny-** [comment]
Not sure if it will work but https://github.com/resoai/TileBoard/commit/a1b25632222bf36886fa851213d542c59e052fef
It's only place in function where NaN can possibly have created. Though not sure if the brightness really is 0, because then it wouldn't be a NaN.

**Comment by vpnmaster** [comment]
Yes brightness is really 0.
![image](https://user-images.githubusercontent.com/4130346/41660388-92ec4150-74a4-11e8-82b7-d16182118764.png)

Now it reports 'on' in the tile if the brightness is 0.

**Comment by Evgeny-** [comment]
Makes sense. Try now https://github.com/resoai/TileBoard/commit/e3a2e9685a643cf526d2929ba547fa5b5adb20c4

**Comment by vpnmaster** [comment]
Sorry, not fixed.
Tile still shows on if brightness is 0.

**Comment by Evgeny-** [comment]
What about now?

**Comment by vpnmaster** [comment]
It works
Thank you
