### ISSUE TITLE
Calling a service (cover tile all buttons avaiable)

### ISSUE THREAD

**Issue by zietek** [resoai/TileBoard#111]
Hey!

I would like to know if it's possible to call a home assistant service? For example after clicking on tile I would like to call service: `cover.open_cover`, with service data
`{
  "entity_id": "cover.fibaro_system_fgrm222_roller_shutter_controller_2_level"
}`
On the other hand when the cover is opened I would like to call `cover.close_cover` service. Is it possible? If not, I think it could be very useful feature. 

P.S.
Great job! Finally I found a dashboard that looks very cool and fits my needs!

**Comment by resoai** [comment]
You can poke around the API but I don't see a reason for it. We do have a cover tile already.

**Comment by cgarwood** [comment]
I set this up with a custom tile and media player services. I’ll have to look up the code when I get home and share it

**Comment by zietek** [comment]
Ohh I haven't noticed cover tile! But I have got another issue. 
I would like to have all buttons avaiable on my cover tile. By default it's not possible even in home assistant but if you customize your entity and set `assumed_state` to `true` it allows you to have all options avaiable.

![fireshot capture 9 - home assistant - http___raspberrypi_8123_states](https://user-images.githubusercontent.com/1236459/43312347-43d3aa3a-918d-11e8-9610-07d5e94201dd.png)

Unfortunately that option won't chane on tileBoard. Do you have an idea what should I do now?
![fireshot capture 10 - tileboard - file____home_marcin_projects_tileboard_index html](https://user-images.githubusercontent.com/1236459/43312403-791e52da-918d-11e8-9b37-15202ecf0e60.png)

**Comment by resoai** [comment]
Why would you want to close the cover when it is already closed?

**Comment by zietek** [comment]
It's not closed. It's partialy closed (or open) but second button is still not avaiable.

**Comment by resoai** [comment]
So what is the actual state when it is partially open/closed?

**Comment by resoai** [comment]
We are only disabling buttons when state is open or closed:

```
ng-class="{'-disabled': entity.state === 'open'}"
```

```
ng-class="{'-disabled': entity.state === 'closed'}"
```

**Comment by zietek** [comment]
Ahh ok, it looks like a controller has just two states: closed and open. I modify source code to disable adding class depending on state and everything works perfect. Thanks for you help. I'm closing issue
