### ISSUE TITLE
Control Iframe src from Custom Tiles

### ISSUE THREAD

**Issue by atomic10** [resoai/TileBoard#113]
Is it possible to change the URL of an iframe from a custom tiles?
All the methods I have tried were to no avail.

**Comment by resoai** [comment]
1. Define iframe tile as a variable
2. Change `url` of that tile from wherever you like.

**Comment by atomic10** [comment]
Thanks Resoai. Thinking this is no doubt my inexperience with JS.
Will keep tinkering.
