### ISSUE TITLE
Feature: Remember last opened page

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#114]
I have TileBoard running as an APP on mobile ('Add to home screen' option in Chrome). When TileBoard is not the active app, android will quite quickly remove it from memory and then on next opening, TileBoard will reload and it will revert to first page. I would prefer that it stays on last opened page instead.

That can be fixed either by storing active page in local storage or storing state in the URL. For the latter, dependency on ui-router (or ng-route) would probably be needed to properly handle URL changes.

**Comment by resoai** [comment]
We already have `openPage` exposed as a function. What about firing an event when navigation occurs?

**Comment by rchl** [comment]
Where would the state be stored with that approach?

**Comment by resoai** [comment]
You would be able to handle it however you like, i.e. store page number in localStorage etc.

**Comment by rchl** [comment]
So you are suggesting to implement all that logic in my config.js? Is it really a right place for such functionality? It's possible I guess but not sure if the best option. I'm suggesting to have it as core functionality.

**Comment by resoai** [comment]
Should work fine without ***ng-route*** with good old anchors.

**Comment by rchl** [comment]
Well, imagine someone is already using some url param. For example, I'm using ?mobile to trigger mobile layout. If there is just a "?page=2" anchor, it will overwrite existing param and turn off mobile layout for me.
It's just an example.

**Comment by rchl** [comment]
I've looked at your changes now. Some notes:
 - It works but initial load triggers page-scroll animation. Ideally there would be no animation on initial load.
 - Changing location.hash manually works but it's not really very clean solution and creates 'hash within hash' --- /#!#2. Also it doesn't handle history navigation or manual change of the URL. That's why using ng-route/ui-route would be more complete solution.
 - For future extensibility, it would probably be better to have more explicit hash. Something like page=2 instead of just 2. That can be problematic when someone decides to have more functionality tied to hash.

**Comment by resoai** [comment]
I agree with what you are saying, I simply wanted to steer clear of extra dependencies.

**Comment by resoai** [comment]
I think I nailed down point 2, so hash within hash no longer shows. In all fairness nobody is going to do anything with hash I think and this feature will probably remain solely for two of us.

**Comment by avandeputte** [comment]
Nope,  I will use it too :)

**Comment by resoai** [comment]
So, now there will be no animation upon initial navigation. Believe this is now OK for everybody?

**Comment by resoai** [comment]
I think you might have need to clear browser's cache. Only #0 get's added on initial load in both FF and Chrome. Which browser are you using?

**Comment by rchl** [comment]
Chrome but same happens in FF.

My URL to TileBoard contains port number. Also it's served from a server rather than from local file system.

**Comment by resoai** [comment]
Very strange, mine also is served from the server and also has port number. Are you sure you have the latest code? There have been a few updates in the past two hours.

**Comment by rchl** [comment]
Yes, I have latest code and cleared the cache.

I can see that angularjs tries to rewrite [hashbang to html5 url](https://github.com/angular/angular.js/blob/v1.7.x/src/ng/location.js#L940). It seems to be what happens to me but it might be slightly timing sensitive because it doesn't happen when I break in certain place in the code.

**Comment by resoai** [comment]
I can't reproduce it I'm afraid.

**Comment by rchl** [comment]
@resoai Do you happen to have TileBoard served from specific path rather than root of the domain? That is, from `[domain]/[some_path]` rather than just `[domain]/`. That would explain why you can't see the problem accordint to this [angularjs issue](https://github.com/angular/angular.js/issues/5529)

**Comment by resoai** [comment]
Yes, mine is in `[domain]:[port]/local/tileboard/index.html`

**Comment by Evgeny-** [comment]
This issue was joke
