### ISSUE TITLE
Media Player: Support for Volume Up/Down only media players

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#116]
Homeassistant supports media players that don't have a volume slider (volume_set). For these players, homeassistant has volume_up and volume_down services. The tile doesn't show slider or volume up/down buttons for these players, making them impossible to control volume.

Workaround: Separate custom tiles to call volume up/down.

**Comment by resoai** [comment]
Can you please show dump of the state of such player?

**Comment by resoai** [comment]
As you can see it is actually being reported as 0, so it is set which is a bit odd. They do have `supported_features` which I will have to look into. Which HA component is being used?

**Comment by mouth4war** [comment]
This is my mistake, I waited in between screenshots. By then, the media player had changed to one which supports slider/volume_set.

Here's how it looks while in no-slider/volumeup-down:

{
  "is_volume_muted": false,
  "source_list": [
    "PS4",
    "Shield",
    "Chromecast"
  ],
  "friendly_name": "Living Room Media Player",
  "supported_features": 3464
}

**Comment by mouth4war** [comment]
Another example:
{
  "volume_level": 0,
  "is_volume_muted": false,
  "source_list": [
    "PS4",
    "Shield",
    "Chromecast"
  ],
  "friendly_name": "Yamaha AVR Receiver",
  "supported_features": 3512
}

**Comment by mouth4war** [comment]
Yes, supported features looks like a better source. SUPPORT_VOLUME_SET and SUPPORT_VOLUME_STEP seem to correspond.

**Comment by resoai** [comment]
What is the integer value of SUPPORT_VOLUME_STEP ?

**Comment by mouth4war** [comment]
SUPPORT_VOLUME_SET = 4
SUPPORT_VOLUME_STEP = 1024

from https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/__init__.py

**Comment by resoai** [comment]
Yes, I've already found it!

**Comment by resoai** [comment]
Could you please check if this is working as expected?

**Comment by mouth4war** [comment]
Wow, Yes! It works for two out of three of my media players. I'm investigating that third one.

I would switch the positions of volume up and down to make down on left and up on right. Feels more natural and mimics HASS.

**Comment by resoai** [comment]
I swapped the position of the buttons (I was doing it from work so I have no idea why I've done it like this).  Personally I don't understand the actual meaning of `SUPPORT_VOLUME_STEP` and `SUPPORT_VOLUME_SET`

**Comment by resoai** [comment]
Can you post state dump of that player which shows slider?

**Comment by resoai** [comment]
I might have figured it out. Could you please try getting latest code and see if it works?

**Comment by mouth4war** [comment]
You definitely have. All 3 are working great now. Thanks a ton!
