### ISSUE TITLE
Nothing Updating

### ISSUE THREAD

**Issue by aravind-natch** [resoai/TileBoard#121]
Hi, I don't know if this problem is a tileboard specific problem, but when I hosted the files directly on my home assistant server (raspberry pi), I could not edit those files again. The edits I made would not be reflected when i visited xxx.duckdns.org/local/index.html. This stayed true to all of my other files that I had hosted through the local www directory. For example, I had an mp3 file that I hosted. Upon deletion, I could still access it through .../local/xxx.mp3. In fact, I deleted this projects contents, and to this day its still on my server. For whatever reason I cannot edit the files to my liking which renders this project useless for me. The only thing I've tried is deleting the database file. If you have any other suggestions please help me out.

Thanks,
Aravind

**Comment by NilSkilz** [comment]
Sounds like the files are cached in your browser. Clear the cache and try again.

**Comment by aravind-natch** [comment]
Thanks a million! This had me quite frustrated!
