### ISSUE TITLE
nt_clear.svg icon doesn't display

### ISSUE THREAD

**Issue by arraylabs** [resoai/TileBoard#122]
Looking at the text of the .svg file the formatting is different than the others. It doesn't display in tileboard.

**Comment by resoai** [comment]
I can't reproduce what you mentioned. It shows just fine in Firefox and Chome.  

![screenshot_2018-08-19 tileboard](https://user-images.githubusercontent.com/11579512/44309884-2e91ec00-a3c5-11e8-950e-96e1f3e573a7.png)


Iconsw source: https://github.com/manifestinteractive/weather-underground-icons

**Comment by arraylabs** [comment]
Sorry for the bother, turns out it was all my nt- versions, had nt_ instead of nt- in the array.
