### ISSUE TITLE
Cover tile should be able to ignore state

### ISSUE THREAD

**Issue by michaelarnauts** [resoai/TileBoard#123]
I have a cover that doesn't support showing it's current state. In hass, this is represented like this, since I've added the option `assumed_state: true`:
![image](https://user-images.githubusercontent.com/1193779/44331252-5aff4400-a469-11e8-8515-467c740e9779.png)

TileBoard shows it like this:
![image](https://user-images.githubusercontent.com/1193779/44331274-69e5f680-a469-11e8-9784-e3b396827e39.png)

This means I can't close the cover. The state will always be closed. Can there be a way so the cover doesn't use the state to show the buttons?

This is probably the same issue as #111

**Comment by resoai** [comment]
Please show the state dump of your cover.

**Comment by michaelarnauts** [comment]
It's always `closed`. This state doesn't change.

I've found a workaround, but it's not pretty:

```
                        {
                            position: [1, 1],
                            type: TYPES.COVER,
                            id: 'cover.sun_blinds',
                            state: function (item, entity) {
                                entity.state = 'unknown';
                                return false;
                            }
                        }
```

The `return false;` needs a different change, since it will output the function now:

![image](https://user-images.githubusercontent.com/1193779/44339687-9fe3a480-a482-11e8-97ab-27c67c0a91f2.png)

This can be solved by changing the code in app.js like this so a `return false` or `return null` works to hide the state.

```patch
diff --git a/scripts/controllers/main.js b/scripts/controllers/main.js
index 3e0e547..b652a8c 100644
--- a/scripts/controllers/main.js
+++ b/scripts/controllers/main.js
@@ -432,7 +432,7 @@ function MainController ($scope, $location) {
          }
          else if(typeof item.state === "function") {
             res = callFunction(item.state, [item, entity]);
-            if(res) return res;
+            return res;
          }
       }
```

![image](https://user-images.githubusercontent.com/1193779/44339783-f7821000-a482-11e8-9148-376ec332946c.png)

I'm not sure why the return value of the anonymous state function needs to be checked. There are a few other checks in that function that might need to be changed.

**Comment by michaelarnauts** [comment]
I can live with the hack by setting the state to unknown, but I guess the checking of the state after the anonymous function needs a real fix.

**Comment by resoai** [comment]
No, if function in state returns false, this means there should be no state. Can I still see the state dump of the cover? Perhaps there is a `supported_features` attribute which can be used in this case?

**Comment by michaelarnauts** [comment]
If a return false means no state, then there should be nothing in the tile for state, this is not how the code is working now. It's outputting the function definition (see screenshot above). Currently, it's only passing the state if it evaluates to true, otherwise, it will default to `item.state`, what is the function itself.

For the cover, this is a templated cover that only implements a down and up action (since that's all I can call)

![image](https://user-images.githubusercontent.com/1193779/44343402-1934c480-a48e-11e8-8745-e2b5029a6f8d.png)
![image](https://user-images.githubusercontent.com/1193779/44343488-58631580-a48e-11e8-882c-2696f263312a.png)

**Comment by resoai** [comment]
If it is a template cover than the state should (probably) be `unknown`?

Stopping code execution at that point would not allow it to move to `if(item.states)...` which is something other users are using.

**Comment by michaelarnauts** [comment]
The code would only be stopped when the anonymous function would return false, and that's something the user has added explicitly in their configs then. I think the logic in `$scope.entityState` is wrong since it returns the `item.state` at the end while this can be a function.

**Comment by resoai** [comment]
Yes and no. The idea was to allow the execution to continue. Here is a use case:

```
title: 'Floor lamp',
subtitle: 'Lounge',
id: 'light.lounge_floor_lamp',
type: TYPES.LIGHT,
state: switchPercents('brightness', 255, true),
states: {
    on: "On",
    off: "Off"
},
```

**Comment by michaelarnauts** [comment]
I see, simply returning isn't okay then, but maybe by changing the check if `=== false`? When the function returns `false`, that should be a clear indication that we don't want a state, and also don't want it to be mapped. If you want it mapped, you can return `off`.

**Comment by michaelarnauts** [comment]
That also still leaves the possibility for the function itself to be returned (from `item.state`), if there is no mapping. Or maybe don't return `item.state` at all in the end?

**Comment by resoai** [comment]
I know it is far from being ideal but I think we could break things changing current behavior.

**Comment by stewface** [comment]
I was trying the code above

`   {
                            position: [1, 1],
                            type: TYPES.COVER,
                            id: 'cover.sun_blinds',
                            state: function (item, entity) {
                                entity.state = 'unknown';
                                return false;
                            }
                        }`

It doesn't seem to work for me - any other ways of getting covers to work without states?

**Comment by michaelarnauts** [comment]
@stewface I have this patch applied to index:
```patch
--- a/scripts/controllers/main.js
+++ b/scripts/controllers/main.js
@@ -429,7 +429,7 @@ function MainController ($scope, $location) {
          }
          else if(typeof item.state === "function") {
             res = callFunction(item.state, [item, entity]);
-            if(res) return res;
+            return res;
          }
       }
```

And this in my config:

```js
                        {
                            position: [0, 2],
                            type: TYPES.COVER,
                            id: 'cover.sun_blinds',
                            title: 'Zonnewering',
                            subtitle: 'Woonkamer',
                            state: function (item, entity) {
                                entity.state = 'unknown';
                                return false;
                            }
                        },
```
