### ISSUE TITLE
hideScrollbar: true causes a spacing on the second page

### ISSUE THREAD

**Issue by michaelarnauts** [resoai/TileBoard#124]
When setting `hideScrollbar: true`, and going to the next page, you can see it doesn't scroll all the way.  You see about 10px of the previous page at the top. This happens only with `transition: TRANSITIONS.ANIMATED_GPU` and `transition: TRANSITIONS.ANIMATED`.

**Comment by resoai** [comment]
`hideScrollbar: true` is really a very dirty workaround which will be removed in future.
