### ISSUE TITLE
Add RGB light color picker

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#128]
Would it be possible to integrate a color picker for color selection of RGB lights?

**Comment by resoai** [comment]
This would require breaking light secondary controls into a popup (like alarm and date picker) and a lot of changes to the way light tile behaves. Unfortunately I don't have time to do this.

**Comment by mouth4war** [comment]
May I propose using a new button for color picker in addition to the +/- buttons for brightness. This one can be on the left as a special button only for RGB lights. This way the sliders remain as is and color picker can be added easier.

I believe there are existing libraries for color picking and these return a value that can be passed to HASS.

**Comment by resoai** [comment]
There is simply no space for it there really. It would probably be much simpler to make a slider which would control hue alone of HSL, assuming Saturation is fixed at 100% and Lightness is basically a value of our brightness.

**Comment by mouth4war** [comment]
That would be a good workaround thanks. Can you give me an example so I can try?

**Comment by resoai** [comment]
This still requires some work to be done in the code to make that happen. Sadly I absolutely have no time for it at the moment.

**Comment by cgarwood** [comment]
I think it would be great to be able to specify configuration for a tile to have a more info popup if you long-press it (similar to the more-info dialogs in the default HA UI), but that would be a pretty large undertaking to add in.

**Comment by TheCellMC** [comment]
I totally agree with @cgarwood. I think it would be very cool if we could have a colour picker on long press. Maybe somethings like the colour picker of the TileBoard project? 
![screen shot 2018-08-30 at 09 28 57](https://user-images.githubusercontent.com/12169936/44836711-fe094800-ac37-11e8-812a-a198c4f71ffc.png)

**Comment by isbrodie1** [comment]
Hey guys, has there been any further update on this one?

**Comment by MPopti0n** [comment]
As a work around (no as nice as a color picker...)

1. **I created scripts in `HomeAssistant` in `script.yaml`** (one for each color)

```
color_hue_livingroom_green:
  alias: "Couleur hue - Salon - VertFonce"
  sequence:
    - service: mqtt.publish
      data:
        topic: "Maison/lumieres/in"
        payload : "HA-Couleur-Salon-VertFonce"
        retain: false
```
_I use Node-Red/MQTT but you can use direct instructions to the entity in HA depending on your light (mine are Philips Hue) like this :_

 ```
color_hue_livingroom_green:
  alias: "Couleur hue - Salon - VertFonce"
  sequence:
    - service: light.turn_on
      data:
        rgb_color: [0,255,0]
        entity_id: light.livingroom
```

2. **I created new tiles in `TileBoard` in `config.js`** (one for each color)
```
               {
                    position: [0, 0],
                    width: 1,
                    height: 1,
                    title: '', // GREEN
                    type: TYPES.SCRIPT,
                    id: 'script.color_hue_livingroom_green',
                    state: false,
                    customStyles: function(item, entity) {
                        return {
                            'backgroundColor': 'rgb(0, 255, 0)',
                            'borderRadius': '70px'
                        };

                    },
                },
```
3. **Nothing to do with the color picker but I added the following at the end of my light tile (not the script tile) to make the background the same color as the actual light color :**

```

                    customStyles: function(item, entity) {
                        var a = (entity.state);
                        var b = (entity.attributes.rgb_color);

                        if (a = 'on') {
                            h = b;
                        } else {
                            h = 1000;
                        }

                        if (h === 1000) {
                            return;
                        } else {
                            return {
                                'backgroundColor': 'rgb(' + h + ')'

                            };
                        }
                    },
```
** And this to show the actual brightness
```

                    subtitle: function(item, entity) {
                        var a = (entity.state);
                        var b = (entity.attributes.brightness);
                        var c = b * 100
                        var d = c / 255
                        var e = d.toFixed(0)
                        var f = e + "%"

                        if (a === 'on') {
                            return f;
                        } else {
                            return;
                        }
                    },
```

### What it looks like : 
![light_dash](https://user-images.githubusercontent.com/36873863/55752258-885b2b00-5a15-11e9-8fdc-87c846983f10.jpg)

**Comment by danhounshell** [comment]
I think I can add a fairly clean RGB color picker with minimal disruption to existing code by using this: https://github.com/Alberplz/angular-colorpicker-directive

The control for it would live on the 2nd view of the lights panel (the longpress/controlsEnabled view) under the brightness slider. I already have most of the hard part done, I just need to add some css and send the updated values back to HA. 

![RGBColorPicker](https://user-images.githubusercontent.com/455284/55823193-2f4fcd80-5acf-11e9-8b64-4e61c2dc371c.png)

**Comment by danhounshell** [comment]
We can close this issue :)
