### ISSUE TITLE
override the camera thumb to an icon?

### ISSUE THREAD

**Issue by kevinshane** [resoai/TileBoard#131]
Hi, @resoai Thanks for the awesome work!
I try this code and it's working like a charm
```
{
                  position: [3, 1],
                  title: 'cam',
                  subtitle: 'kitchen',
                  id: 'camera.generic_camera',
                  type: TYPES.CAMERA_THUMBNAIL,
                  refresh: 10000,
                  bgsize: 'cover',
                  width: 1,
                  height: 1,
                  states: false,
                  fullscreen: {
                      type: TYPES.CAMERA_THUMBNAIL,
                      refresh: 1000,
                      bgSize: 'contain'
                  }
                },
```
However I would like to replace the thumb to an icon(kind of mach the transprant theme) instead, I try to add the `icon: "mdi-cctv"` but it won't work! Can I somehow make the icon overrided? Thanks

**Comment by resoai** [comment]
Icon will not work because in  camera and camera_thumbnail there is only an image. You could create a separate class in `custom.css` file and override `.item-camera` if you really want to  get rid of the preview.
