### ISSUE TITLE
[Feature Request] Long Press Color Picker

### ISSUE THREAD

**Issue by TheCellMC** [resoai/TileBoard#133]
Would it be possible to support a long press actions on tiles such as lights to bring up their colour settings and brightness.
I really like the way the Home Panel project accomplished this. Would it be possible to do something similar here ?
![screen shot 2018-08-30 at 09 28 57](https://user-images.githubusercontent.com/12169936/44836566-9b17b100-ac37-11e8-83a0-82a40e3a4f1d.png)

**Comment by TheCellMC** [comment]
Sorry, duplicate of #128

**Comment by MPopti0n** [comment]
See for a (not as pretty as a color picker) work around 
https://github.com/resoai/TileBoard/issues/128#issuecomment-480979824
