### ISSUE TITLE
Camera flickering

### ISSUE THREAD

**Issue by mariuszluciow** [resoai/TileBoard#140]
Showing camera on fullscreen by refreshing images (`camera_proxy`) results in `flickering effect`. How about using `camera_proxy_stream` instead? 

```
https://hass.com/api/camera_proxy_stream/camera.piggies_camera?token=asd
```

**Comment by resoai** [comment]
We tried it initially and HA is starting to throttle streams effectively not showing anything after opening camera a few times. Also, `camera_proxy_stream` is not really documented.

We have tried bypassing flickering by caching next image and only showing it once it is loaded and it seems to be working OK-ish on Chrome and other Webkit browsers.

**Comment by ricreis394** [comment]
I'm having the same problem with latest version of TileBoard. Is there anything I can do to fix this?

![stream](https://user-images.githubusercontent.com/11768109/59867074-142df380-9385-11e9-9d8f-3921f082868d.gif)
