### ISSUE TITLE
Moon and the Sun on right header

### ISSUE THREAD

**Issue by pepebc** [resoai/TileBoard#143]
Perhaps it could be interesting to be able to place on  header right the state of the Moon and the Sun.
How could it be done?

**Comment by resoai** [comment]
Header can include any html via `CUSTOM_HTML`. You can create your own logic for that and even  display images for moon phase. 

https://github.com/resoai/TileBoard/wiki/Header-configuration

https://www.cufonfonts.com/font/moon-phases
