### ISSUE TITLE
Start versioning TileBoard

### ISSUE THREAD

**Issue by mariuszluciow** [resoai/TileBoard#145]
Small suggestion - could you start tagging TileBoard with version using semantic versioning, marking in the notes compatibility range with HASS? 
In addition to having better visibility, it will allow people easier installation using git, eg

```
> git clone https://github.com/resoai/TileBoard.git --branch <tag_name> --single-branch 
```

and than just move the config.

**Comment by resoai** [comment]
To be honest, I've never used tagging before. Usually changes we make are purely incremental i.e. we either add new functionality or fix what was broken. What would one put into tags?

**Comment by mariuszluciow** [comment]
Well, that's up to you, you can either create tag each time a PR is merged or wait for more changes to come and then create a tag listing all changes. Comprehensive example of using tags you can find on https://github.com/home-assistant/home-assistant/releases repository, although they don't use semantic versioning.

**Comment by resoai** [comment]
Thanks for the tip, I will have a look at it!

**Comment by Evgeny-** [comment]
Versioning could be useful if we had builds, but TileBoard was specially created without javascript compilation. Though using branches is good idea, but seems there's no much left to do anyway (at least in my opinion).
