### ISSUE TITLE
Ability to set icon as a value of sensor

### ISSUE THREAD

**Issue by mariuszluciow** [resoai/TileBoard#146]
As a small UX improvement I would like to set icon as a value of my sensor, e.g. visual representation of battery state, keeping the top-right state with numeric value. 

<img width="174" alt="screen shot 2018-09-17 at 22 57 55" src="https://user-images.githubusercontent.com/7955061/45649976-295fb400-bacd-11e8-9d86-368503d0eae4.png">

Is it possible currently?

**Comment by resoai** [comment]
Yes, something like this should work:

```
icon: function(){
               var battery_level = this.states[item].attributes.battery_level || 0;
               var battery_round = parseInt(battery_level / 10) * 10;

               if (battery_round >= 100) return 'mdi-battery';
               else if (battery_round > 0) return 'mdi-battery-' + battery_round;
               else return 'mdi-battery-alert';
            }
```

**Comment by mariuszluciow** [comment]
I tried this but no luck, the 100% is still there.

```
 {
                            position: [0, 1],
                            type: TYPES.SENSOR,
                            id: 'sensor.piggies_camera_battery',
                            title: 'Battery',
                            icon: function(item, entity){
                                var battery_level = this.states[item].attributes.battery_level || 0;
                                var battery_round = parseInt(battery_level / 10) * 10;
                 
                                if (battery_round >= 100) return 'mdi-battery';
                                else if (battery_round > 0) return 'mdi-battery-' + battery_round;
                                else return 'mdi-battery-alert';
                             }
                        },
```

**Comment by resoai** [comment]
If `sensor.piggies_camera_battery` is reporting percentage as state, than you surely need to amend `this.states[item].attributes.battery_level`. This was a code I used for my  Aqara motion sensors for `TEXT_LIST` . All you need for your one is `entity.state`

**Comment by mariuszluciow** [comment]
I wasn't precise enough. The problem is that using `TYPES.SENSOR` I'm unable to show icon instead of value. Which is obvious looking at the code: 

```
      <div ng-if="item.type === TYPES.SENSOR"
           class="item-entity-container">
         <div class="item-entity">
            <span ng-bind="entityValue(item, entity)"
                  class="item-entity--value"></span>

            <span ng-if="(_unit = entityUnit(item, entity))"
                  class="item-entity--unit" ng-bind="_unit"></span>
         </div>
      </div>
```
Is there a work around for it other than using `TYPES.CUSTOM` which makes tile clickable?

**Comment by resoai** [comment]
Simply use `GENERIC_ICON` tile

**Comment by mariuszluciow** [comment]
Oh, missed this one, thanks!

**Comment by resoai** [comment]
And remember that you can still use a function to display a different icon  :)
