### ISSUE TITLE
cameraList allows duplicates of cameras

### ISSUE THREAD

**Issue by mariuszluciow** [resoai/TileBoard#147]
My organisation of UI has a dashboard (first page) with the most important data, and then dedicated page for each room. Due to this, my security camera is added into two pages, resulting into duplicate on cameraList. 

I can create PR with filtering cameras by id, but I'm not sure what should be done here, as some of the `fullscreen` config can be different for each camera.

**Comment by resoai** [comment]
I don't think there is a need for that. Each tile can be hidden:

```
  /* hidden: hide tile (optional)
   * can be Boolean or function that return Boolean
   */
  hidden: Boolean | Function,
```

All you need to do is create an function checking which page is currently open and returning true or false respectively.

**Comment by resoai** [comment]
I've also added `hideFromList: true` yesterday.
