### ISSUE TITLE
Hide list item in TYPES.TEXT_LIST,

### ISSUE THREAD

**Issue by Nemesis24** [resoai/TileBoard#151]
**you could use this in config.js:**
`list: [
					    {
                           title: 'your title',
						   icon: 'your icon',
						   hideli: function () {
                             return this.parseFieldValue('&yourdoorsensorforexample.state') === 'on' ?  ' ' : 'hide-li';
                           }
                        },`

**and add this in index.html line 632**
`<div class="item-list--item"
                 ng-repeat="line in item.list track by $index" ng-class="listField('hideli', item, line)">`

**add this in custom.css**
`.hide-li {
	display:none;
}`

**Comment by resoai** [comment]
The proper way would be simply create an array of items you need before assigning it.
