### ISSUE TITLE
Problem installing tileboard

### ISSUE THREAD

**Issue by ngreis** [resoai/TileBoard#153]
Hi

I created the www/tileboard folder, altered the config.exemple to config.js, tried to go to the default page.
I get connection refused, with this page, http://prntscr.com/kxtco4

As far as i get it should bring up a login screen, yes?
Config is as follows, http://prntscr.com/kxtdsx

Can you help please?

Best regards

Nuno Reis

**Comment by resoai** [comment]
For some reason Chrome is redirecting you to localhost. Try clearing browser's cache.

**Comment by ngreis** [comment]
Hi

Done that, ctrl+F5 after,  not working, i am using Hass.io in a VM, so the localhost in the base config.js, should work.
Altered to ip as in picture, same error.
Tought it could be some config missing in yaml file for HA, setup http: manually, with IP:port and API password, same error.

:\

**Comment by resoai** [comment]
404 for custom.css is not an error. I really don’t know how you have configured VM but it should not work with localhost.

**Comment by resoai** [comment]
What if you open the page in Firefox?

**Comment by ngreis** [comment]
Well in Edge browser works.
Chrome issue, then.

Tileboard is stored in the vm in local folder so local shouldwork, but i get that you connect to the HA so in fact wont work with localhost, either way i have it setup with IP.
Like i said, with Edge works fine.

Browser related bug? Any ideias?

**Comment by resoai** [comment]
No clue why Chrome redirects to localhost honestly. I have mine running in docker and everything works fine.

**Comment by tsvdonsk** [comment]
I have same problem in safari, Firefox and chrome(

**Comment by Evgeny-** [comment]
@ngreis @tsvdonsk what about using predefined api tokens? 
https://github.com/resoai/TileBoard/blob/master/config.example.js#L18
At least it should work without redirections

**Comment by stratosgear** [comment]
Hmmm, I get redirected to localhost even on firefox.

Can't even try Tileboard... :(

**Comment by stratosgear** [comment]
On the other hand, changing `localhost` to `hassio.local` (or however else you access your server) on `config.js`:

```
...
   serverUrl: "http://hassio.local:8123",
   wsUrl: "ws://hassio.local:8123/api/websocket",
...
```

Seems to work for both Chrome and Firefox (plus, cleaning your file cache (CTRL+SHIFT+DELETE))

**Comment by narfel** [comment]
That's a weird issue. No matter what you put in the config, chrome arbitrarily decides to redirect to http://localhost:8123/local/index.html?oauth=1&code=<...> when it should redirect to http://hassio.local:8123/local/index.html?oauth=1&code=<...> :/

**Comment by narfel** [comment]
Update: i found the error. The it is not a redirect at all. It's just that the default config entry pointing to 
 localhost doesn't get deleted when you refresh or(!) delete the cache of Chrome. In Chrome under "Clear browsing data" you **have** to select "Content settings" and likely "Hosted app data" to get this to update and then it works with either the mdns or the ip in serverUrl and wsUrl.
