### ISSUE TITLE
cover arrow enable/disable + slider cover position

### ISSUE THREAD

**Issue by madmicio** [resoai/TileBoard#156]
Hi!
I'm trying tile board, I like it a lot. but I have a problem with the tile cover. when the cover is not completely closed the up arrow does not work. so even if the cover is 50% it is not possible to open it completely. Is it possible to have the slider for the position over the arrows up, down, stop? in home assistant the slider controls the position of the shutters and updates its position if the shutters are opened or closed by the physical buttons on the wall.

**Comment by dennisschroeder** [comment]
`         {
                position: [1, 0],
                type: TYPES.SLIDER,
                id: 'cover.xxxxxxxx',
                title: false,
                subtitle: false,
                width: 1,
                height: 1,
                unit: '%',
                value: '@attributes._c.value',
                state: false,
                bottom: true,
                slider: {
                  field: 'position',
                  request: {
                    type: "call_service",
                    domain: "cover",
                    service: "set_cover_position",
                    field: "position"
                  }
                }
              }`

Here is my cover.slider config part. But to reflect the current_position in the slider position, i had to modify line 715 in the controllers/main.js file.

`$scope.getSliderConf = function (item, entity) {
    var key = "_c";

    if (!entity.attributes) entity.attributes = {};
    if (entity.attributes[key]) return entity.attributes[key];

    var def = item.slider || {};
    var attrs = entity.attributes || {};

    entity.attributes[key] = {
      max: attrs.max || def.max || 100,
      min: attrs.min || def.min || 0,
      step: attrs.step || def.step || 1,
      value: +entity.state || def.value || +entity.attributes.current_position || 0,
      request: def.request || {
        type: "call_service",
        domain: "input_number",
        service: "set_value",
        field: "value"
      }
    };

    setTimeout(function () {
      item._sliderInited = true;
    }, 50);

    return entity.attributes[key];
  };`

I adjustet this line `value: +entity.state || def.value || +entity.attributes.current_position || 0,`

**Comment by madmicio** [comment]
I'm sorry but I'm really inexperienced

this is the config.js code: 

> { position: [1, 0], type: TYPES.SLIDER, id: 'cover.xxxxxxxx', title: false, subtitle: false, width: 1, height: 1, unit: '%', value: '@attributes._c.value', state: false, bottom: true, slider: { field: 'position', request: { type: "call_service", domain: "cover", service: "set_cover_position", field: "position" } } }

this mod for line 715:

> var def = item.slider || {};
var attrs = entity.attributes || {};

entity.attributes[key] = {
  max: attrs.max || def.max || 100,
  min: attrs.min || def.min || 0,
  step: attrs.step || def.step || 1,
  value: +entity.state || def.value || +entity.attributes.current_position || 0,
  request: def.request || {
    type: "call_service",
    domain: "input_number",
    service: "set_value",
    field: "value"
  }
};

setTimeout(function () {
  item._sliderInited = true;
}, 50);

return entity.attributes[key];
};`
I adjusted this line value: +entity.state || def.value || +entity.attributes.current_position || 0,

and this?

> `$scope.getSliderConf = function (item, entity) {
var key = "_c";
if (!entity.attributes) entity.attributes = {};
if (entity.attributes[key]) return entity.attributes[key];

**Comment by madmicio** [comment]
![schermo](https://user-images.githubusercontent.com/42836292/46636666-3cf4bc80-cb59-11e8-94e2-e50040f91c19.JPG)
this is my current screen. but it is a compromise of script and input_number. your solution is the best. but I must understand well how and where to enter your code

**Comment by madmicio** [comment]
Help!

**Comment by radinsky** [comment]
@madmicio 
Have you find a solution?

**Comment by madmicio** [comment]
in the end I gave up tileboard. I am very sorry, but it gave me continuous reconnection problems.

now i'm using lovelace. I tried to make it as close as possible to tilboard

https://www.facebook.com/groups/HomeAssistant/permalink/2365817007022989/

**Comment by radinsky** [comment]
actually I figured how it should be done, just after writing the previous messages. the answer is easy, filed should be "current_position" instead of "postion" as i was using.
Anyway, sorry to hear you gave up, my setup actually working pretty nice, but recently I also see a lot of reconnection. I will try opening a new issue for it.

**Comment by radinsky** [comment]
> https://www.facebook.com/groups/HomeAssistant/permalink/2365817007022989/
It's really nice for lovelace, but visually (and functionally) not even close to be as Tileboard.

**Comment by santoleo83** [comment]
Hi guys,
With this code:
```
{
                     position: [0, 0],
                     id: 'cover.tapparella_cameretta',
                     title: 'Tapparella Cameretta',
                     subtitle: false,
                     type: TYPES.SLIDER,
                     //unit '%',
                     state: false,
                     field: 'position',
                     bottom: false, // puts slider on bottom,
                     value: '&cover.tapparella_cameretta.attributes.current_position',
                     slider: {
                        max: 100,
                        min: 0,
                        step: 1,
                        title: "Position",
                        field: "current_position",
                        value: '&cover.tapparella_cameretta.attributes.current_position',
                        request: {
                           type: "call_service",
                           domain: "cover",
                           service: "set_cover_position",
                           field: "position"
                        }
                     }
                  },
```
I have this on Tileboard:
![tileboard](https://user-images.githubusercontent.com/52829914/83647667-6f1c2300-a5b5-11ea-84d1-ecad5bca3fb7.PNG)
It is OK.
Now I would like to have the square with UP/STOP/DOWN.
What kind of code have to write?
Please help me.
Thx Leo
