### ISSUE TITLE
Unable to open page using id:

### ISSUE THREAD

**Issue by KHouse75** [resoai/TileBoard#157]
I'm attempting to implement automation for when certain events are triggered to open specific pages based on id: per this example:

```
    /* Example: Open a specific TileBoard page
     * Include a page field in the event_data from Home Assistant
     * that matches the id: of a page in the TileBoard CONFIG
     */
    {
      command: 'open_page',
      action: function(e) {
        window.openPage(CONFIG.pages[e.page]);
      }
    }
  ],
```
e.page comes back undefined.  I've tried adding id: to each page and I've tried using title:.  The only way it works is if I use the index number of each page as per the order in which they appear in the config.js file.  CONFIG.pages[1] works, for example, but is not ideal since orders in the code could change as I add new pages.  I haven't found in the code where it's taking e.page and determining its index.  Just to make sure it wasn't something in my config, I used the sample config as a base and had the same problem.

Am I missing something or is this not yet implemented?

Also, is there a way to put a timer on the page so after x seconds it goes back to a page specified?  Such as CONFIG.pages[Page Index to go to , Timeout in Seconds, Page Index to return to after Timeout]?  Basically, what I'm looking for is if someone pulls into my driveway, an event gets triggered that tells  TileBoard to switch to my driveway camera page for 30 seconds then goes back to the main panel automatically.

**Comment by resoai** [comment]
If you wish to add `id` to each page than you do something like this:

```
    {
      command: 'open_page',
      action: function(e) {
        var page = CONFIG.pages.filter(function(obj) {
          return obj.id == e.page;
        });
        window.openPage(CONFIG.pages[page]);
      }
    }
```

**Comment by resoai** [comment]
As for the timeout, you could use a `DOOR_ENTRY` tile with the very same event simply defining the tile as a variable beforehand:

```
this.$scope.openDoorEntry(tile, tile.id);
```

`CONFIG.doorEntryTimeout` allows you to set timeout (in seconds) for the popup to automatically close.

**Comment by KHouse75** [comment]
Thank you.  I misunderstood what the open_page example was referring to with id.  DOOR_ENTRY with doorEntryTimeout is exactly what I was looking for and works perfectly.
