### ISSUE TITLE
TYPES.SCRIPT

### ISSUE THREAD

**Issue by Jmang95** [resoai/TileBoard#159]
I am powering the TV on and off using 1 tile and a script. As I click on the tile, the script is executed and the TV is powered on and off accordingly. However the tile does not change its state nor the icon. How can I modify this? I have attached a screenshot of the relevant code

                    {
                        position: [0, 0],
                        width: 2,
                        type: TYPES.SCRIPT,
                        id: "script.power",
                        //id: "switch.broadlink_send_packet_192_168_137_56",
                        title: 'Power',
                        states: { on: 'On', off: 'Off' },
                        states: function (item, entity) { return entity.state },
                        icons: { on: 'mdi-power', off: 'mdi-power-off' },
                    },

**Comment by Jmang95** [comment]
No it does not. Is there a way to toggle the state of the tile upon clicking on it? Or perhaps when the script is executed?

**Comment by resoai** [comment]
TileBoard is just a frontend so it obviously relies on state values reported by it. I'm not sure how you expect it to work.

**Comment by rchl** [comment]
A bit cleaner possibly with 'switch' type with 'assumed state' + automation but still same downsides.

**Comment by resoai** [comment]
The best way would be to create two scripts one for turning TV on and one for turning it off.

**Comment by rchl** [comment]
Yeah, probably one would came to that conclusion eventually. No point in trying to be smart when device is not. :)

**Comment by resoai** [comment]
I have a similar problem with one of the gates at my  house. There is no way of knowing if they are open or closed and no way of adding a sensor.

**Comment by Jmang95** [comment]
I am using an Broadlink IR blaster to switch on and off the TV, that's why I cannot detect the state of the TV.   I was trying to keep track of its state by assuming an initial state (in this case I am assuming it to be off), so that I can notify the user whether the TV is on and off.

**Comment by mouth4war** [comment]
@resoai try using a door/window sensor to sense your gate state. I use one on my dumb curtain motor to know it's state. Works great.

**Comment by resoai** [comment]
@mouth4war gates are 250 meters away from the house so there is no way to fit the sensor.
