### ISSUE TITLE
Header covers content on smaller (tablet) resolutions

### ISSUE THREAD

**Issue by dlizak** [resoai/TileBoard#160]
Header covers content on Huawei MediaPad M3 tablet which has 854x534 resolution (2560x1600 native), as presented on screenshot below. Also element are slightly too big. TileBoard is targeted to this type of devices, so maybe 'px' unit does not fit perfect.

![screenshot_20181010-184358](https://user-images.githubusercontent.com/1761503/46756414-ae527d80-ccc7-11e8-8439-d8b932c4d83f.png)

**Comment by resoai** [comment]
There is a whole Wiki on how to configure different sizes, including mobile devices. Please take some time to read through it.

https://github.com/resoai/TileBoard/wiki
