### ISSUE TITLE
config.js is cached by browser

### ISSUE THREAD

**Issue by dlizak** [resoai/TileBoard#162]
I noticed, that everytime I edit config.js, I have to clean browser data to see new version of config.js. It's inconvinient especially on mobile devices, where I need to digg into menu and clean it manually.

**Comment by resoai** [comment]
1. Click top right drop down menu in chrome browser
2. Click "New incognito tab"
3. Navigate to your website and see all your most recent changes.

On desktop you can disable cache on developer tools. 

![chrome-disable-cache](https://user-images.githubusercontent.com/11579512/46765312-97675780-ccd6-11e8-8368-8da5d14c1551.png)

**Comment by cederlof** [comment]
This is still a problem for mobile browsers?
