### ISSUE TITLE
dynamic icon for a page

### ISSUE THREAD

**Issue by nnhhuu** [resoai/TileBoard#163]
Hello,

i'm trying to have a different icon for a page depending on the status of a group, for example show a 'mdi-lightbulb-**on**-outline' when any of the lights in a group is ON or vice versa. 

i tried many ways to use a function to do that ... but all of them show me an empty icon.  I started with something like this 

icon: function () {
       return this.parseFieldValue('&group.ligthnhu.state') === 'on' ?  'mdi-lightbulb-on-outline' : 'mdi-lightbulb-outline';
     },

any ideas....

Thank you

**Comment by resoai** [comment]
In the tile where you define `group.ligthnhu` you can do state as a function which would override the icon of the page in config:

```
CONFIG.pages[1].icon = '...';
````

**Comment by nnhhuu** [comment]
thank you!!!!!! it works....  

    state: function () {
      var estado = this.parseFieldValue("&group.ligthnhu.state");
      if ( estado == "on")
          CONFIG.pages[3].icon =  'mdi-lightbulb-on-outline'
      else
          CONFIG.pages[3].icon =  'mdi-lightbulb-outline';

      return  false;
    },

**Comment by resoai** [comment]
```
state: function (item, entity) {
   CONFIG.pages[3].icon = entity.state === 'on' ? 'mdi-lightbulb-on-outline' : ''mdi-lightbulb-outline';
   return false;
}
```

**Comment by nnhhuu** [comment]
@resoai thank you...
