### ISSUE TITLE
For types SENSOR show history on press

### ISSUE THREAD

**Issue by mariuszluciow** [resoai/TileBoard#165]
Recently lovelance UI for hass introduced a new `SENSOR` card. 
https://www.home-assistant.io/lovelace/sensor/

We could reuse this idea, drawing a chart how the state changed over the last 24h. My proposal is to show the chart on click or longpress. 

The data can be obtained through API:
localhost/api/history/period/2018-10-19T21:38:04.264Z?filter_entity_id=sensor.speedtest_download&end_time=2018-10-20T21:38:04.264Z

What do you think?
Cheers

**Comment by cadavre** [comment]
I already developed a chart for sensors to show on tile click:
<img width="2039" alt="Zrzut ekranu 2019-10-14 o 22 53 16" src="https://user-images.githubusercontent.com/461796/66782213-79c66280-eed5-11e9-9d74-3ee4065c6d36.png">

What I have in TODO is to create very simple charts to show inside a tiles, just like in `sensor` Lovelace cards. But first I'd need to get PR #270 merged.

**Comment by akloeckner** [comment]
PR #274 might be a start. Feel free to join the discussion!
