### ISSUE TITLE
Vacuum - Return to Home support

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#168]
Hi @resoai,

The toggle vacuum tile doesn't support return to home service vacuum.return_to_base. Could you please add support for that?

**Comment by resoai** [comment]
Current vacuum tile acts as a switch only so it does not have many features. I don't have a vacuum myself so even current implementation was done blindly.

**Comment by mouth4war** [comment]
I propose toggling between turn_on and return_to_base. This is how it used to work when using a switch tile before the change in HASS vacuum architecture.

Still think a larger tile based on media_player tile is the way to go eventually. You need no logic, just buttons for play, pause, stop, return to base, locate and spot clean (each button has a service call only). And a fan speed selector to replace the source select.

**Comment by mouth4war** [comment]
For reference, this is how HASS UI vacuum looks while vacuum is cleaning. The toggle button changes to "return to base" from "start cleaning". So yeah, we should toggle between those.

![image](https://user-images.githubusercontent.com/30283635/47600737-95dea480-d9e3-11e8-8390-7b8588cd2017.png)


Detailed view shows all buttons and fan speed selector.

![image](https://user-images.githubusercontent.com/30283635/47600735-81021100-d9e3-11e8-8406-7136f56c8603.png)

**Comment by resoai** [comment]
Not all of the vacuums support "return to base" if I understand correctly. You can see that I already had some logic for various ones.
