### ISSUE TITLE
slider control

### ISSUE THREAD

**Issue by madmicio** [resoai/TileBoard#171]
is it possible to set the value on mouse up?

**Comment by resoai** [comment]
You can change `ng-change` to `ng-mouseup` in index.html for the sliders you need (SLIDER tile or sliders within LIGHT tile).

**Comment by madmicio** [comment]
I tried and in effect on the pc it works. but unfortunately on a tablet or smartphone it does not work. I move the bar, the blinds remain motionless. i thought that removing the finger from the touchscreen was equivalent to mouse up, now I understand that it is not. How can I solve the problem?

**Comment by resoai** [comment]
I’m afraid this is something you would have to research yourself.
