### ISSUE TITLE
Tileboard Each Tile size? Zoom in/Zoom out in Tablet browser

### ISSUE THREAD

**Issue by ceaswaran** [resoai/TileBoard#173]
I see all UI great in PC/Laptop but on my tablet. it looks zoomed in. is there a way to resolve this in tileboard config or in browser setting?
**How I see in PC/Laptop:**
![whatsapp image 2018-11-04 at 10 42 31 pm](https://user-images.githubusercontent.com/40624146/47973858-97d3f200-e0cc-11e8-8e26-11a380268b70.jpeg)

**How I see in 7inch Android Tablet:**
![whatsapp image 2018-11-04 at 11 02 13 pm](https://user-images.githubusercontent.com/40624146/47973957-29436400-e0cd-11e8-9a8c-5756230403da.jpeg)

Please Help

**Comment by resoai** [comment]
Visit our wiki page, it has plenty of information as to sizing and mobile configurations.
