### ISSUE TITLE
Feature Request: Google Calendar Tile

### ISSUE THREAD

**Issue by scottdarby93** [resoai/TileBoard#175]
Hello, I love the dashboard but I'm looking to implement more features into this and I'd love to be able to pull some of my upcoming calendar events into TileBoard as this example below in Lovelace, is this something that can be implemented?

https://github.com/rdehuyss/homeassistant-lovelace-google-calendar-card

**Comment by resoai** [comment]
You can implement any tile types you wish. A good starting point would be to have a look at `TEXT_LIST`
