### ISSUE TITLE
Confirmation modal

### ISSUE THREAD

**Issue by alekslyse** [resoai/TileBoard#176]
Is it any easy way to add something simple like a "do you really want to xxxx yes no" modal with click on a button? I have some buttons I don't want accidentally clicked. Modal or for example long press x seconds.

**Comment by alekslyse** [comment]
In general yes, I fully agree, but sometimes it could be usually with eater require long press, or a second modal on critical systems. 

in 99% of the use-cases I agree with what you say, but in my example I use implemented an aquarium controller that one button is maintainance mode (that stops pumps etc) - If I had to hold the button for example 10 seconds of get a second modal that would secure the system. 

Im not sure why it should not be a good addon to be able to long press on a programmable seconds (for example a ring going around the icon) or a second yes/no modal that is completely optional for operations that the user could in theory miss press

**Comment by resoai** [comment]
I suppose you could add a custom tile to enable long press (there is an example in main controller) however I don’t feel this should be implemented for everyone.

**Comment by cgarwood** [comment]
I'd support adding a confirmation modal as an option. Especially with a toddler that has figured out how to reach the tablet :)

**Comment by resoai** [comment]
To be honest I don't feel like a confirmation modal and dashboard should exist in the same universe but there is nothing preventing you from doing a simple `window.confirm` with a custom tile.
