### ISSUE TITLE
Camera refreshing during screensaver

### ISSUE THREAD

**Issue by dummptyhummpty** [resoai/TileBoard#180]
I believe the camera tile is still refreshing while the screensaver is visible. My iPad 3 doesn’t handle this well and after some time Safari crashes.

**Comment by resoai** [comment]
Should be freezing cameras whenever screensaver is shown now.

**Comment by domibarton** [comment]
@resoai Your changes in 6811a339 broke the screensaver, as mentioned in #195 :)
