### ISSUE TITLE
Often disconnects

### ISSUE THREAD

**Issue by ivanovd** [resoai/TileBoard#182]
Hi. I noticed that if I leave my browser for few hours, after I return TileBoard is disconnected and Chrome presents me with an error page and when I refresh I have to login to Hassio again. Do you think it is an issue with Hassio or with WebSockets?
![maxthonsnap20181128091702](https://user-images.githubusercontent.com/4889583/49138639-65e33380-f2f8-11e8-8969-6c6c49ee1c56.png)

**Comment by resoai** [comment]
Definitely a network issue. I have three dashboards running via Chrome for months with no issues. TileBoard also handles reconnects gracefully.

**Comment by ivanovd** [comment]
Thanks. I will look into it.
