### ISSUE TITLE
Climate: Missing +/- buttons when in off mode (generic thermostat)

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#183]
Unable to set the thermostat while it is off. The +/- buttons only appear when in heat mode.

**Comment by helenclarko** [comment]
I'm also having this issue, Was a fix found?

I just set up a generic thermostat:
https://www.home-assistant.io/integrations/generic_thermostat

The + and - buttons are missing and I have no way to control the thermostat from Tileboard.

**Comment by resoai** [comment]
If thermostat is off, than +/- should in fact not bee present otherwise what is there to control?
