### ISSUE TITLE
Better long-lived token support

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#184]
I understand that long-lived tokens are supported by writing it directly to the config file but I don't want to put sensitive data in the config (as it's exposed publicly).

The UI could ask for the token and store it in the local storage or cookie like it did previously with plain passwords.

Flow-wise, when not logged in, it could open an overlay of some sort that would give option to either login through HA or enter token manually.

**Comment by resoai** [comment]
This is up to the user to make a decision. A simple window.prompt with saving data to  localStorage would be sufficient. Same can easily be defined in an anonymous function.

**Comment by rchl** [comment]
Are you suggesting that all this is implemented in config file?

A lot can be done through config file (as history showed) but where do draw the line in terms of ease of use? Is it a project for developers or normal users? :) I wouldn't mind this being solved in core, with some nice and simple UI.

**Comment by resoai** [comment]
TileBoard is actually for developers rather that users to be honest hence the relative code simplicity and hack-ability.

**Comment by resoai** [comment]
Please also remember that long-lived tokens were actually never meant for normal users. We handle refreshing tokens for normal users.

**Comment by rchl** [comment]
Guess you are right, given that it's not easy to configure tiles in the first place.
Feel free to close if you don't agree that core should handle that.
