### ISSUE TITLE
Header dateFormat doesn't apply to HEADER_ITEMS.DATE

### ISSUE THREAD

**Issue by YannikW** [resoai/TileBoard#189]
Hi,

I configured my header with clock on left side an date on right side, see code below:

```javascript
header: { // https://github.com/resoai/TileBoard/wiki/Header-configuration
    styles: {
      padding: '10px 130px 0',
      fontSize: '48px'
    },
    right: [
      {
        type: HEADER_ITEMS.DATE,
        dateFormat: 'EEEE, d. MMMM', //https://docs.angularjs.org/api/ng/filter/date
      }
    ],
    left: [
      {
        type: HEADER_ITEMS.TIME,
      }
    ]
  },
```

For this configuration date should be ```Monday, 7. January```, but it shows as the default ```Monday, January 07```.

![image](https://user-images.githubusercontent.com/12040515/50788689-6a691780-12ba-11e9-9cdf-64251761d9c1.png)

When I switch to ```HEADER_ITEMS.DATETIME``` it is applyed correct:

```javascript
header: { // https://github.com/resoai/TileBoard/wiki/Header-configuration
    styles: {
      padding: '10px 130px 0',
      fontSize: '48px'
    },
    right: [
      {
        type: HEADER_ITEMS.DATETIME,
        dateFormat: 'EEEE, d. MMMM', //https://docs.angularjs.org/api/ng/filter/date
      }
    ],
    left: [
      {
        type: HEADER_ITEMS.TIME,
      }
    ]
  },
```

![image](https://user-images.githubusercontent.com/12040515/50788942-0c88ff80-12bb-11e9-90d5-0a46596f3500.png)
(please ignor that shitty layout with datetime, it's caused by my css config)

Second, not issue related question, is it possible to change language of date / datetime ? I would like to use it in german..

Thanks in advance :)

**Comment by resoai** [comment]
For ` HEADER_ITEMS.DATE` you need to specify `format` and not `dateFormat`. You can localise Angular by  including this file:

```
<script src="includes/angular-locale_de-de.js"></script>
```

https://github.com/angular/bower-angular-i18n/blob/master/angular-locale_de-de.js

**Comment by YannikW** [comment]
Thanks for the fast reply!

Both is working perfect :)

![image](https://user-images.githubusercontent.com/12040515/50849500-8252a100-1377-11e9-9448-c575452670f7.png)

**Comment by jsglazer** [comment]
How do you format the HEADER_ITEMS.TIME element?  I tried 'format', 'Format', 'dateFormat', and every permutation that I could think of.
This is not working.
`    left: [
      {
        type: HEADER_ITEMS.TIME,
        format: 'hh:mm:ss', //https://docs.angularjs.org/api/ng/filter/date
      }`

**Comment by resoai** [comment]
You can't format `HEADER_ITEMS.TIME`:

https://github.com/resoai/TileBoard/blob/master/index.html#L467

**Comment by LucianTothezan** [comment]
> <script src="includes/angular-locale_de-de.js"></script>

hello. where is this line to be inserted and how does it work please? i am trying to change the date timer format also, but i ndo not know how to do it. thank you in advance for your reply.

**Comment by rchl** [comment]
Please see the `locale` option. It's documented in the readme.

**Comment by LucianTothezan** [comment]
I got it working the way i wanted. thank you so much for your hint.
