### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by abeksis** [resoai/TileBoard#19]
Is it possible to add code to rtl?

**Comment by resoai** [comment]
You may try to add the following to the body selector in CSS

`
{
direction:rtl;
}
`

However it might take more than that for proper RTL support and I'm afraid that this is something a native speaker should do.

**Comment by abeksis** [comment]
Unfortunately this is causing problems. I will try to add rtl anywhere by checking the code

**Comment by resoai** [comment]
Since the whole dashboard is simply an HTML file, you can add any styles you wish to `main.css` file.

**Comment by abeksis** [comment]
Thanks for the answer - that's exactly what I will do.
