### ISSUE TITLE
Alarm Control Panel Pin Code Not Required

### ISSUE THREAD

**Issue by ash32152** [resoai/TileBoard#192]
Hi Guys,

Fairly new to this so apologies if I've done something stupid, just looking for some advice, I've got a Yale Smart Alarm which I've put into my config.yaml, I've then used the 'code_format: xxxx' so that if someone broke in they couldn't just click the icon in HA and disarm the alarm...
![image](https://user-images.githubusercontent.com/34089376/51663287-36763d80-1fae-11e9-9cc8-77f48b4cdf96.png)

I then learnt about your guys great work and started adding all my things to Tileboard, to which I added my alarm like the below in my config.js:
                  {
                     position: [0, 0],
                     type: TYPES.ALARM,
                     id: "alarm_control_panel.yale_smart_alarm",
                     title: 'Home Alarm',
                     icons: {
                        disarmed: 'mdi-bell-off',
                        pending: 'mdi-bell',
                        armed_home: 'mdi-bell-plus',
                        armed_away: 'mdi-bell',
                        triggered: 'mdi-bell-ring'
                     },
                     states: {
                        disarmed: 'Disarmed',
                        pending: 'Pending',
                        armed_home: 'Armed home',
                        armed_away: 'Armed away',
                        triggered: 'Triggered'
                     }
                        }
Now that works perfectly, displays the correct status, can execute each armed command, my only problem is, although it shows the keypad, it doesn't actually require anything entering to change the state... I'm thinking I may need to drop the code_format value either into the config.js or the index.html to mirror the HA config, but i've been trying different things and hit a wall, can't find anything in old forums 😞 

![image](https://user-images.githubusercontent.com/34089376/51663431-b3a1b280-1fae-11e9-84eb-84bd7a5b0553.png)

Cheers,

**Comment by resoai** [comment]
So how does it work in HA? If it does not require a code, you could wrap it around manual alarm panel in HA and specify the code you need.

**Comment by resoai** [comment]
Are you sure it actually disarms the alarm? All we we is send API request to HA...

**Comment by ash32152** [comment]
Yeah, 100% the Yale alarm beeps and I get app notifications to say that it has😞 it’s like it’s not picking up the variables there but not sure how I can troubleshoot it

**Comment by resoai** [comment]
I’m sorry but I never had any experience with alarm panels mysel. Mine is an dumb old fashion thingy.

**Comment by ash32152** [comment]
Ah no worries, i'm doing further testing to try and figure out, i'll post here as i'm sure it'll not just be me that uses the Yale alarm with HA & tileboard. One interesting thing  i did find out, eve with 'code_format: xxxx' for the entity in HAS, I can put in any code and it'll arm/disarm, it's just I can't arm/disarm without any pin in HAS. So that'll explain why Tileboards is firing the service call without

**Comment by resoai** [comment]
TileBoard would fire the call anyway it is than up to HA to decide if arming or disarming should take place.

**Comment by ash32152** [comment]
> TileBoard would fire the call anyway it is than up to HA to decide if arming or disarming should take place.

Ok so figured it out, HA wasn't requiring the pin to arm/disarm etc, it needed an input but no check to see if it was the correct pin, I had a look at the .py script for the Yale Smart Alarm module and I don't have any experience with python but have coded with many other languages and got the jist, I took the .py script into my custom_components and re-wrote logic into it to check for a code just on disarm, I know this isn't a tileboard issue but hopefully if anyone comes across the same problem they may find it in a google search, I would approach for it to be included in an updated release but as my pythons a bit rusty i've not got any pop-up notification to confirm an incorrect pin like i've seen in some peoples alarm scripts, but if anyone does have the issue if you want you can drop me a PM and I will supply you an edited version for just a pin required on disarm.
