### ISSUE TITLE
authToken SECURITY issue

### ISSUE THREAD

**Issue by jwater7** [resoai/TileBoard#193]
Probably should change the README or the comments in the example config to reflect that including an authToken is basically giving the internet access to your instance of home assistant.

I see a [similar issue](https://github.com/resoai/TileBoard/issues/184) has been raised before, but I think if safe support for it isn't going to be included in the core TileBoard functionality, then IMO it should either be removed or a huge disclaimer should be added to the example config and README.

**Comment by resoai** [comment]
It doesn't matter how many times we mentioned similar thing about the password, people just don't read README. I have made a note about it in the example config though.

https://github.com/resoai/TileBoard/commit/5b7b356f731f4d47f5bf1d50a830499603f8dacc

**Comment by shiftux** [comment]
forgive me if this is a n00b question: 
but would it be sufficient to export the token into a seperate file and then import it with: `loadJS('./secret_token.js')`

**Comment by resoai** [comment]
Absolutely not, the very same file is accessible via browser.

**Comment by shiftux** [comment]
thanks for the reply!
that's what i figured...
what if i were to put it into an environment variable on the server and interpret that in config.js? would it be interpreted and then exposed in plaintext in the browser?

**Comment by resoai** [comment]
TileBoard is simply a webpage, it has absolutely no access to the backend. All you need to do if some reason you are planning to to expose TileBoard to the outside world is to avoid specifying token altogether, you might also want to add basic auth via nginx.

**Comment by shiftux** [comment]
i see. it is basically a static webpage that relies on the hass webserver, and only that has access to the backend...
makes sense now that you expressed it.
thanks for explaining
