### ISSUE TITLE
Improve quality of map tile (HDPi)

### ISSUE THREAD

**Issue by Swiftnesses** [resoai/TileBoard#196]
Hi,

Great HA add-on, thank you!

It would be nice if the map tiles could be displayed in high res, currently it looks very blurry on HDPi devices...

**Comment by resoai** [comment]
Please feel free to test it.

**Comment by Swiftnesses** [comment]
Works great, thanks @resoai :)

**Comment by Swiftnesses** [comment]
@resoai My neighbours have a business and the marker appears right over my house on Google Maps, I believe there's a way to hide places via the API, can this be achieved with TileBoard?

**Comment by resoai** [comment]
Try changing lines 189 and 190 in main.js to:

```
            url = "https://maps.googleapis.com/maps/api/staticmap?center="
               + coords + "&zoom="+zoom+"&size="+sizes+"&scale=2&maptype=roadmap&style=poi.business|visibility:off&markers=" + marker;
```

Does this fix it?

**Comment by Swiftnesses** [comment]
Sadly, the map doesn't work if I replace the lines with the above...

**Comment by resoai** [comment]
I will let you play with the URL and decide what parameters work best for your case.

**Comment by Swiftnesses** [comment]
Tried and failed, your above suggestion stopped the map displaying completely :(

**Comment by Swiftnesses** [comment]
Regarding now showing businesses, I tried and failed, your above suggestion stopped the map displaying completely :(

**Comment by arvathrowaway** [comment]
This isn't a problem with TileBoard. Please refer to the [Maps Static API docs](https://developers.google.com/maps/documentation/maps-static/styling) for how to fix. BUT, the following should work based on the documentation:

```
   url = "https://maps.googleapis.com/maps/api/staticmap?center="
               + coords + "&zoom="+zoom+"&size="+sizes+"&scale=2&maptype=roadmap&style=feature:poi.business|visibility:off&markers=" + marker;
```
I think @resoai was missing the "feature:" declaration in his fix.
