### ISSUE TITLE
Using Google Geocode results in error, help?

### ISSUE THREAD

**Issue by Swiftnesses** [resoai/TileBoard#197]
I'm using this within my config to convert to lat and long into an address (work in progress!)

Currently I have:

```
					title: 'Address',
					icon: 'mdi-update',
					value: function() {
						return new Promise(function(resolve, reject) {
							var request = new XMLHttpRequest();
							var method = 'GET';
							var url = 'https://maps.googleapis.com/maps/api/geocode/json?latlng=' + '40.714224' + ',' + '-73.961452' + '&key=' + 'mykey';
							// console.log(url)
							var async = true;
							request.open(method, url, async);
							request.onreadystatechange = function() {
								if (request.readyState == 4) {
									if (request.status == 200) {
										var data = JSON.parse(request.responseText);
										console.log(data)
										var address = data.results[0];
										console.log(address)
										resolve(address);
									} else {
										reject(request.status);
									}
								}
							};
							request.send();
						});
					},
				}, {
```

The issue is, while the console outputs the address, I also get an error:

`Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.7.2/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…tem%2C%20line)%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%7B%7D%7D%5D%5D at angular.min.js:7 at m.$digest (angular.min.js:150) at updateView (main.js:1841) at handleEvent (main.js:1813) at handleMessage (main.js:1795) at main.js:1633 at api.js:187 (anonymous) @ angular.min.js:7 $digest @ angular.min.js:150 updateView @ main.js:1841 handleEvent @ main.js:1813 handleMessage @ main.js:1795 (anonymous) @ main.js:1633 (anonymous) @ api.js:187 setTimeout (async) (anonymous) @ api.js:187 $Api._fire @ api.js:186 $Api._handleMessage @ api.js:207 (anonymous) @ api.js:173`

Any ideas? I'm no coder BTW :)

**Comment by Swiftnesses** [comment]
Okay, I got it working, not sure if it's a good implementation:

At the top of the config I declared a var:

`var geo_address = 'waiting...';`

I then placed this in my tile:

```
					title: 'Address',
					icon: 'mdi-update',
					value: function() {
						  setInterval (function() {
							var request = new XMLHttpRequest();
							var method = 'GET';
							var url = 'https://maps.googleapis.com/maps/api/geocode/json?latlng=' + '40.714224' + ',' + '-73.961452' + '&key=' + 'mykeyhere';
							// console.log(url)
							var async = true;
							request.open(method, url, async);
							request.onreadystatechange = function() {
								if (request.readyState == 4) {
									if (request.status == 200) {
										var data = JSON.parse(request.responseText);
										// console.log(data)
										geo_address = data.results[0].formatted_address;
										console.log(address)
									}
								}
								else {
									return 'Error';
								}
							}
							request.send();
						}, 6000)
						return geo_address;
						}
```

Any comments welcome :)

**Comment by resoai** [comment]
Where are the coordinates coming from? Having setIntetval is not a good idea.

**Comment by Swiftnesses** [comment]
Coordinates are coming from the iOS tracker devices... What about setTimeout instead?

**Comment by resoai** [comment]
You can do this outside of the config and simply assign value: to geo_address variable you defined.

**Comment by Swiftnesses** [comment]
I’m trying, but really struggling, I now have the geo lookup code function at the top, and have lat | long as function variables passed to the function from the tile code where I grab the device info (I then return the address and display it), not sure I have the skills to make it happen, I’m close… :-/

**Comment by resoai** [comment]
Why not get the address in HA using a custom component and use the value of the sensor in TileBoard? 

https://github.com/michaelmcarthur/GoogleGeocode-HASS

**Comment by Swiftnesses** [comment]
:-D

There’s always an easier way, well, at least I learnt a little code :)

**Comment by resoai** [comment]
I have not tried it myself so I'm not sure if it still works, but there appears to be a thread about it:

https://community.home-assistant.io/t/google-geocode-custom-component-gps-to-street-address/22233/305

**Comment by resoai** [comment]
Should we close this one?

**Comment by Swiftnesses** [comment]
Sorted, thanks you @resoai!

I'd love to get the Google Maps clearer, if you could check my issue :)

P.S. Thank you so much for this great add-on!
