### ISSUE TITLE
Subtitle - Rookie error or...

### ISSUE THREAD

**Issue by Swiftnesses** [resoai/TileBoard#198]
Hi,

Why do these work:

```
subtitle: '&binary_sensor.coop.attributes.round_trip_time_avg',
subtitle: 'Ping ' + '&binary_sensor.coop.attributes.round_trip_time_avg',
```

But this doesn't:

`subtitle: '&binary_sensor.coop.attributes.round_trip_time_avg' + 'ms',`

**Comment by resoai** [comment]
I guess if you add a space before ms in the first example, it would work fine?

**Comment by Swiftnesses** [comment]
Hmmm, it seems to, rookie error? :)

**Comment by resoai** [comment]
Parser can only replace exact sensor values.
