### ISSUE TITLE
Config.js issues

### ISSUE THREAD

**Issue by WeeMan1990** [resoai/TileBoard#204]
So i got home today and all out of nowhere tileboard refuses to load. Never had any issues except for the ocassional ''missing comma'' in my config, but it still loaded the ui without any issues. Now i have tried everything, including to restart from scratch and use the config example without any changes.  Does anyone have any ideas? These are the responses i get when i try to load: 

Please make sure you have "config.js" file and it's a valid javascript!
If you running TileBoard for the first time, please rename "config.example.js" to "config.js"

ReferenceError: CONFIG is not defined
File: http://192.168.1.12:8123/local/TileBoard/scripts/init.js
Line: 22:5

**Comment by resoai** [comment]
Open browser’s developer tools and see what error says. This is clearly an error in your config.

**Comment by WeeMan1990** [comment]
> 
> 
> Open browser’s developer tools and see what error says. This is clearly an error in your config.

It turns out it wasn'tthe config, i save all my working configs before i change anything, and i tried several of them. Turns out that somewhere my config got messed up, but it wouldnt work until i cleared my web browers cache.
