### ISSUE TITLE
INPUT_SELECT should have the option to show a popup, like ALARM

### ISSUE THREAD

**Issue by timvancann** [resoai/TileBoard#205]
Currently the INPUT_SELECT popup is a very tiny list, which is very hard to control on wall-tablets, normal tablets or phones.
The ALARM popup for state select is absolutely perfect. It'd be great if the INPUT_SELECT popup would be configurable to something similar to the ALARM popup.

**Comment by resoai** [comment]
You can style text size however you like in custom.css file. Contextual menus and popups are purposely diferent UI elements.

**Comment by timvancann** [comment]
@resoai Thanks for the reply. Although I'm a backend engineer (and suck at anything CSS) I can manage that!
