### ISSUE TITLE
Feature Request: Add Source_list to Media_player

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#21]
Would be nice to add the source_list input_selectish variable to mediaplayers on clicked.

**Comment by Evgeny-** [comment]
We have it already, if i get you right. Try to click on source name in the tile

**Comment by nayaj** [comment]
Check http://jayan.se/example.avi for a short recorded video of what i mean

**Comment by resoai** [comment]
This is already implemented.

**Comment by nayaj** [comment]
i cant see the selector after inputing that in the code, was this patched in the last hours?

**Comment by resoai** [comment]
No this has been implemented two days ago. Did you clear browser's cache? Are you clicking on the title?

**Comment by nayaj** [comment]
Not working :( 

here is the config

```
{
   position: [7, 1],
   width: 2,
   title: 'Sonos One - Köket',
   id: 'media_player.kitchen',
   type: TYPES.MEDIA_PLAYER,
   showSource: true,
   state: '@attributes.media_title',
   input_select: '@attributes.source_list',
   bgSuffix: '@attributes.entity_picture', // show picture of current media as a background
},
{
   position: [7, 2],
   width: 2,
   title: 'Sonos Connect - Vardagsrum',
   id: 'media_player.livingroom',
   type: TYPES.MEDIA_PLAYER,
   showSource: true,
   state: '@attributes.media_title',
   bgSuffix: '@attributes.entity_picture', // show picture of current media as a background
},
{
   position: [7, 3],
   width: 2,
   title: 'Sonos One - Sovrum',
   id: 'media_player.bedroom',
   type: TYPES.MEDIA_PLAYER,
   showSource: true,
   state: '@attributes.media_title',
   bgSuffix: '@attributes.entity_picture', // show picture of current media as a background
},
```

**Comment by resoai** [comment]
Please post screenshot showing state details of media player in HA

**Comment by nayaj** [comment]
![2018-06-21 11-05-21](https://user-images.githubusercontent.com/40382766/41709295-1f8a055e-7543-11e8-8d05-50fcba695308.jpg)

Here u go, i got source working for my LG TV now, but not for the Sonos speakers yet.

**Comment by resoai** [comment]
If you have a closer look at the screenshot you can see that it is exposing source_list but not the source so there is no way of knowing which source is currently selected. I don't own Sonos myself, perhaps someone else could comment on it.

**Comment by nayaj** [comment]
Noticed another bug with my VU+ box as media_player.

It lists source but cannot be clicked..

![2018-06-21 11-13-33](https://user-images.githubusercontent.com/40382766/41709872-98455308-7544-11e8-8064-7ad8469fbc42.jpg)

perhaps because its a long source?

![2018-06-21 11-12-31](https://user-images.githubusercontent.com/40382766/41709880-9c8c72d4-7544-11e8-9d52-ecafbb0f26e0.jpg)

**Comment by nayaj** [comment]
source = media_title for Sonos maybe?

**Comment by resoai** [comment]
No, media_title is a current song. If I understand correctly from the video you posted, even HA does not show current (selected) source?

**Comment by nayaj** [comment]
I suppose you are right.. 

Source_list for Sonos is basicly starting new playlists

Source_list for my  Vu+ box is basicly swapping TV channel

**Comment by resoai** [comment]
Media Player in HA is a bit of nightmare. there are players that implement certain things but do not implement others.

**Comment by nayaj** [comment]
i would still like it to work tho :) <3

**Comment by resoai** [comment]
How many channels are there? I might need try it on my TV. As for Sonos, we could (probably) show a text "Source" when source_list is exposed but source isn't but I'm not sure how adequate this solution would be.

**Comment by nayaj** [comment]
85 channels

**Comment by nayaj** [comment]
If i add "Source": "Valid source example" in HA then source_list pops up for a few seconds in Tileboard (and i can swap sources).

<img width="298" alt="add_source" src="https://user-images.githubusercontent.com/40382766/41720795-728dccec-7564-11e8-9830-f937719c7d0b.PNG">


So basicly what i need is a way for Tileboard to be able to ignore the "Source" variable and go straight to "Source_list"

**Comment by resoai** [comment]
It has been implemented a few hours ago. Please get the latest code and have a go at it.

**Comment by nayaj** [comment]
Did update, and it didnt help sadly.

**Comment by resoai** [comment]
You must be able to see the "Source" title now. Did you clear the cache?

**Comment by nayaj** [comment]
yes i even moved the entire directory to run it from a local disk instead of apache.

**Comment by nayaj** [comment]
Give me a few minuters and i will

**Comment by nayaj** [comment]
Power buttons show for LGTV (still need to be able to bind turn_on to run script tho).
Power-Off works just fine. WOW!

SOURCE IS SHOWING FOR SONOS!!!! you are amazing.

now to the sad part, still cant browse the sources on the VU+ box.

**Comment by resoai** [comment]
I made a temporary fix which should solve the problem. Long lists have simply been going off screen.

**Comment by nayaj** [comment]
Amazing! Resolved!
