### ISSUE TITLE
Feature request: Theme style bypass in items

### ISSUE THREAD

**Issue by MPopti0n** [resoai/TileBoard#211]
It will be a good addition to add an option to bypass the Theme style of an item
 ex: 
I want my temperature tile to be BIG TEXT and light blue with dark blue margin, but my outside pressure tile to be as the theme set it.
```
Items [ 
....
    Styles: {
       fontSize : 70px
       marginColor : blue or #000000},
```

**Comment by apop880** [comment]
Have a look at the readme and examples posted in the Home Assistant forum. You can use customStyles (best for a one-off tile or one where you're going to change the style based on a function) or classes (best for a reusable style) on the tile to accomplish this. Examples:

https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/1964?u=apop (uses classes)

https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/436 (uses customStyles - basic)

https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/345 (uses customStyles - advanced)

https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/944 (uses customStyles - advanced)

**Comment by MPopti0n** [comment]
Many thanks @apop880  for the quick response! Looks like i'll be having so much fun with that tonight!
