### ISSUE TITLE
Question and/or Feature Request: HTML in sensors value

### ISSUE THREAD

**Issue by MPopti0n** [resoai/TileBoard#212]
HA is up-to-date (`0.90.1`) running on `RP3`
The TileBoard is also up-to-date
The type of `items` use is : `type: TYPES.DEVICE_SENSOR`

I have a sensor that sends CO2 level to HomeAssistant (and many others in that style too!, like aquariums parameters).

- When the level is OK : 
 `500` (number, no unit [unit can be add and then it's text])

- But... when the level is high :
`<font color= "#f71c00"> 3000 ppm </font>` (as text)

**The number part is showing ok, but the second one is showing the text [`<font color= "#f71c00"> 3000 ppm </font>`  ] and not the supposed red text**

### My questions : 

1. 

is there a way (or another `type` to use) to make it "use" the HTML code in the sensors value (like with HADashboard [`appdeamon`])

2.

can I replace the HTML part ( `<font color= "#00000"> ... </font>` ) with something else that will be use to define the text color/size... or else!?

**Comment by apop880** [comment]
Are you passing that whole HTML string from HA to TileBoard? I would recommend just passing the number and then using a function in customStyles to set the color dynamically based on the value. See my comment on your other issue for customStyles examples.

**Comment by MPopti0n** [comment]
> Are you passing that whole HTML string from HA to TileBoard? I would recommend just passing the number and then using a function in customStyles to set the color dynamically based on the value. See my comment on your other issue for customStyles examples.

We can do that!!! Awww nice :) I'll take a look, thanks a lot 👍 
And yess i'm the string is pass from node-red to HA to TitleBoard.
