### ISSUE TITLE
Fully Kiosk support

### ISSUE THREAD

**Issue by danhounshell** [resoai/TileBoard#217]
I like many others am using TileBoard in Fully Kiosk. To make full usage of Fully I have added support for using its api to allow the tablet to act as a motion sensor and media player (supporting TTS) and report the state of the device and the browser to HA (whether it is plugged in, screen brightness, wifi signal strength, etc). It is based on this: https://github.com/pkozul/ha-floorplan-kiosk/blob/master/www/custom_ui/floorplan/lib/fully-kiosk.js

It is a standalone module that requires very few changes to TileBoard itself to work and if you are not using Fully or do not have the Fully browser api enabled it exits early. 

I would be happy to PR what I have to TileBoard, though I understand if you do not want to add something that will only be used by the few. In that case I can just create a separate repo for it with instructions for including it in TileBoard.

**Comment by MPopti0n** [comment]
Can't you already do that with/in HA (or Node-Red if you use it!) directly with the Fully Kiosk api? I find it simpler to use HA than TileBoard for that as it is HA that contain all the script / automation / switch.... that are presented on TileBoard. Can you give a more complete example of the purpose of adding that function? I'm intrigued!

**Comment by danhounshell** [comment]
You can see what I have done here: https://github.com/danhounshell/TileBoard/tree/featuure-add-fullykioskapi, this is what I would be putting in a PR along with instructions for setting up the switches and media player definitions in HA. 

I have a wall mounted tablet in one of my main entry points of the house. It only runs the Fully Kiosk browser displaying TileBoard.

If I create a couple of binary sensors in HA and add a custom media player file then I can have Fully Kiosk relay the state of Fully Kiosk and the device (tablet) to Home Assistant. One of the primary uses for me is that I can use the tablet as a motion detector. And since HA sees it as a media player I can use the TTS functionality. I can also have an automation that lets me know if the device has been unplugged and/or the battery is low. The switch definitions and automations all still exist in Home Assistant.  The code I have added just sends the values to HA and responds to media player command from HA. 

Here is a pic of one of the sensors with attributes received from Fully Kiosk on the tablet. 

![ha_fullykiosk](https://user-images.githubusercontent.com/455284/55726072-f9322100-59dc-11e9-9c1e-099f561322f4.png)

**Comment by resoai** [comment]
Thanks for your work which does look good however I don't think we should make this part of the code (TileBoard is already messy). What we should do is make it into a standalone module and provide users with a guide on how to integrate it should they wish to do it.

**Comment by danhounshell** [comment]
Thanks, we can close this issue.

**Comment by recklessnl** [comment]
@danhounshell this looks really cool - is there a guide on how to set this up properly?
