### ISSUE TITLE
Issue: Media_Player bgSuffix entity_picture not loading

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#22]
my media_players are not loading any entity pictures, even though i can see that they are there in the regular UI.

**Comment by Evgeny-** [comment]
Please give us more information. Take a screenshot of tile element in the DOM inspector where style applies.

**Comment by nayaj** [comment]
i noticed that if i copy the full api url it saves the file as media_player.kitchen for example.. if i rename this to .jpg for example i can open the file.

**Comment by nayaj** [comment]
any way to do like
```
bgSuffix: '("@attributes.entity_picture'" + ".jpg")',
```
 ?

**Comment by nayaj** [comment]
Not sure exactly what you are asking for Evgeny.

![2018-06-21 09-38-51](https://user-images.githubusercontent.com/40382766/41704816-93de77a2-7537-11e8-8f2f-fa308f527849.jpg)

![2018-06-21 09-38-22](https://user-images.githubusercontent.com/40382766/41704836-9971afea-7537-11e8-9d69-9f3e42f560f6.jpg)

![2018-06-21 09-44-40](https://user-images.githubusercontent.com/40382766/41704925-d92ce744-7537-11e8-9164-6d80fc79ce3e.jpg)

**Comment by nayaj** [comment]
something like 
```
    var str1 = "@attributes.entity_picture";
    var str2 = ".jpg";
    var res = str1.concat(str2);

**Comment by resoai** [comment]
Adding the extension is incorrect. This works absolutely fine with:

```
                  {
                     position: [0, 3],
                     width: 2,
                     id: 'media_player.denon',
                     type: TYPES.MEDIA_PLAYER,
                     showSource: true,
                     state: '@attributes.media_title',
                     bgSuffix: '@attributes.entity_picture',
                     //bgOpacity: 0.5
                  },
```

**Comment by resoai** [comment]
I suspect that this is similar issue to what you have with the entity_picture of device tracker due to hosting issues so I will close the issue for now.
