### ISSUE TITLE
Events: Start Screensaver - Only Black

### ISSUE THREAD

**Issue by JesseWebDotCom** [resoai/TileBoard#226]
When I trigger the event to start the screensaver, the screen turns black.  If I leave tileboard idle, it displays the proper screensaver.

**Comment by JesseWebDotCom** [comment]
Got it - So the event starts and stop the Fully Kiosk screensaver NOT the tileboard screensaver.  I recommend updating the documentation to make this clearer and also add the steps to turn on "Enable Javasccript Interface Plus", buy the Fully Kiosk Plus license, and setup the  "Screensaver (PLUS)".

Ideally these events would start and stop the tileboard screensaver.

**Comment by resoai** [comment]
There are separate functions to start and stop built in screensaver along with additional info on the wiki page.
