### ISSUE TITLE
Feature Request: Events to Specific Clients

### ISSUE THREAD

**Issue by JesseWebDotCom** [resoai/TileBoard#227]
I'd like to send events to different tablets  - ex. send a notification to tablet A, set page to 4 on tablet B, play sound on tablet C.  Right now the events send to every tablet.

**Comment by resoai** [comment]
Add an identifier to to the config and send extra parameter with the event to check it against that identifier.

**Comment by cgarwood** [comment]
I’m doing this with my setup. I’ll try to share some code later today. Tag me in a reply if I haven’t posted anything after a couple days in case I forget 🙂

**Comment by cgarwood** [comment]
OK here's some example code:. It's a little messy and past-due for some cleanup but it should get you started.

For events that I want to only apply to certain tablets, I created a `checkTarget` function that gets called in each event:

```
events: [
    {
      command: "screen_off",
      action: function(e) {
        if (typeof fully !== undefined) {
          if (checkTarget(e)) {
            fully.startScreensaver();
          }
        }
      }
    },
    {
      command: "screen_on",
      action: function(e) {
        if (checkTarget(e)) {
          if (typeof fully !== undefined) {
            fully.stopScreensaver();
            fully.bringToForeground();
          }
        }
      }
    }
]
```

checkTarget is defined as:
```
function checkTarget(event_data) {
  if (event_data.hasOwnProperty("target")) {
    if (typeof fully !== "undefined") {
      if (typeof event_data.target === "string") {
        if (devices.hasOwnProperty(event_data.target)) {
          if (devices[event_data.target].indexOf(deviceId) > -1) {
            return true;
          }
        }
      }
      if (event_data.target instanceof Array) {
        for (var i = 0; i < event_data.target.length; i++) {
          if (devices.hasOwnProperty(event_data.target[i])) {
            if (devices[event_data.target[i]].indexOf(deviceId) > -1) {
              return true;
            }
          }
        }
      }
    }
    return false;
  }
  return true;
}
```
(man I should refactor and clean that up...)
It allows me to pass either a string or array as `target` in the event data from Home Assistant. If no target is specified, it defaults to all tablets.

Names that can be passed from HomeAssistant are defined in config.js as follows:
```
// Map Device IDs to friendly IDs to call from Home Assistant
var devices = {
  living_room: [device_ids.living_room],
  master_bedroom: [device_ids.master_bedroom],
  nursery: [device_ids.nursery],
  test: [device_ids.living_room, device_ids.master_bedroom],
};
```

So I can fire a `tileboard` event from HomeAssistant with the following `event_data`
```
{
  'command':'screen_on',
  'target':'living_room'
}
```
to turn on the living room tablet.

```
{
  'command':'screen_on',
  'target':'test'
}
```
to turn on the living room and master bedroom tablets.

```
{
  'command':'screen_on',
  'target':['master_bedroom','nursery']
}
```
to turn on the master bedroom and nursery tablets

etc.

**Comment by JesseWebDotCom** [comment]
@cgarwood - thanks for the quick reply and example.  The only thing I can’t figure out is how each tablet has a unique name.  Am I setting that in the tablet OS (ex nursery)?

**Comment by cgarwood** [comment]
Yeah, in my case I’m using Fully Kiosk Browser. It’s javascriot interface has a few functions that can return different device IDs

**Comment by JesseWebDotCom** [comment]
Got it, thanks:
https://www.ozerov.de/fully-kiosk-browser/#websiteintegration

You've been extremely helpful.
