### ISSUE TITLE
Feature Request: Notify with Image or Camera

### ISSUE THREAD

**Issue by JesseWebDotCom** [resoai/TileBoard#228]
Right now I can trigger a notify event with a specific icon.  I'd like to be able to use an image and ideally a camera feed.  

Use case: When I arrive home, send a "Jesse is Home" notification with my picture
Use case: When I open the garage, send a notification with a camera feed of the garage

**Comment by resoai** [comment]
Notification should not include an image. What you are looking for is probably to open door entry with camera feed for 120 seconds when certain event occurs.

**Comment by JesseWebDotCom** [comment]
for "icon", is there a way to use images instead of mdi icons?  That would solve this feature for me as well as allow me to use icons outside to materialdesignicons.  Thanks

**Comment by resoai** [comment]
Sure, just create your own css rule for each of your own icon. mid-xxx is simply a css class
