### ISSUE TITLE
[Feature Request] long press

### ISSUE THREAD

**Issue by JesseWebDotCom** [resoai/TileBoard#229]
I'd love to have the ability to prevent clicks and only have a long press.  This is particularly important for cover tiles, where I don't want someone accidentally opening the garage door because they were swiping/scrolling through the dashboard.

To start, perhaps you can quickly add this to the custom tile (ex. action = click press, action_long = long press)?

**Comment by resoai** [comment]
This breaks functionality with light tile which has separate functionality for long press and is not an expected behaviour. You are free to override the default handlers in main.js for your own setup though.

**Comment by JesseWebDotCom** [comment]
Is there any way to override handlers without modifying core TileBoard files?  I'm concerned about hacking up core files, updating when you have a new release, and I lose my changes.

Thanks

**Comment by resoai** [comment]
There will hardly be any changes to that file in future.

**Comment by JesseWebDotCom** [comment]
I was able to add long press to TYPES.CUSTOM with the code below.  Perhaps you can incorporate this into the official release for others:

MAIN.JS
```
   $scope.entityLongClick = function ($event, page, item, entity) {
      $event.preventDefault();
      $event.stopPropagation();

      switch (item.type) {
         case TYPES.LIGHT: return $scope.openLightSliders(item, entity);
         // ONLY ADDED THE LINE BELOW
         case TYPES.CUSTOM: return $scope.customTileActionLong(item, entity);
      }

      return false;
   };

   // ADDED THIS FUNCTION
   $scope.customTileActionLong = function (item, entity) {
      if(item.action_long && typeof item.action_long === "function") {
         callFunction(item.action_long, [item, entity]);
      }
   };   
```

CONFIG.JS (Example on how to make an open/close garage door tile REQUIRE a long press)
```
{
   type: TYPES.CUSTOM,
   state: false,
   id: 'cover.garage',
   title: 'Garage',
   icons: {
      open: 'mdi-garage-open',
      opening: 'mdi-garage-alert',
      closing: 'mdi-garage-alert',
      closed: 'mdi-garage'
   },
   action_long: function (item, entity) {
      var service_name = 'close_cover';
      if (entity.state === 'closed') {
         service_name = 'open_cover';
      }

      Api.send({
         type: "call_service",
         domain: "cover",
         service: service_name,
         service_data: {
            entity_id: item.id
          }
      });
   }, 
```

**Comment by JesseWebDotCom** [comment]
The code I provided will not work properly if you provide an "action" and "action_long".  I see you have this same problem in "openLightSliders".  I'll see if there if I can find a workaround for the above.  If not, I'll just have to use one or the other.  You could also incorporate the above by adding a property where people specify the desired press type (single click by default but they can specify "long" if desired):
```
{
   type: TYPES.CUSTOM,
   action: function xyz...,
   action_press_type: (click, long)
  ...
}

**Comment by helenclarko** [comment]
If you have this working, can you make a pull request?

**Comment by akloeckner** [comment]
Check this out #282

**Comment by akloeckner** [comment]
@JesseWebDotCom , can this be closed per the PR above?

**Comment by rchl** [comment]
I think it should be possible to handle the original use case with the above-mentioned change.
