### ISSUE TITLE
Entity "updater.updater" not found

### ISSUE THREAD

**Issue by jrnhrmn** [resoai/TileBoard#231]
After install the default Tileboard page states: **Entity "updater.updater" not found**
How can I remove this? The updater.updater doesn't exist anymore I think.

**Comment by cgarwood** [comment]
I think the default TileBoard config contains a tile for `updater.updater` - you can just remove that tile from your TileBoard config

**Comment by jrnhrmn** [comment]
Ah stupid. Off course. Was looking at it al wrong :)
Thanks!
