### ISSUE TITLE
[Feature Request] Variables from JSON file

### ISSUE THREAD

**Issue by JesseWebDotCom** [resoai/TileBoard#234]
I'd like to store sensitive data (ex. phone numbers, names) in a separate json file that Tileboard would load and allow me to access by variable name (ex. secrets.phone_01).  This would allow me to upload and share my entire tileboard config to github (minus this sensitive json file).

Looks like this is a native angualr feature, I just dont know how to enable it.
THanks

**Comment by resoai** [comment]
Believe that you have already been given a response on the forum.
