### ISSUE TITLE
Reconnect issues

### ISSUE THREAD

**Issue by radinsky** [resoai/TileBoard#236]
Hi,

I recently see a lot of reconnection issues, even when all other services (lovelace, appdaemon with hadashboard and more) working correctly.
Yes, I can disable the notification but I'm looking to solve the root cause.
@resoai Can you please elaborate on this one?

Thanks!

**Comment by resoai** [comment]
https://github.com/resoai/TileBoard/commit/a8132ecffb42fc592ebf8a00b40f54b6987749b1

**Comment by radinsky** [comment]
Thanks, I have those changes, actually for now I've disabled pinginng and it became more stable in my setup.
