### ISSUE TITLE
can TEXT_LIST states being a friendly-name

### ISSUE THREAD

**Issue by rexjun83** [resoai/TileBoard#237]
hi,resoai
I use a lock entity in TEXT_LIST, 
in HA it looks like  
entity:  lock.front_door
state: locked / unlocked
but english is not my mother tongue, I want to show state in other languages in textlist-tile.
or rename the states(locked / unlocked). 
Can tileboard do it now? Or will this feature be add to future versions? 
thank you for a nice work

**Comment by rexjun83** [comment]
Climate tile display status (cool,heat,auto,off) can not be set in HA language. Can I modify the file to make it what I need?

**Comment by resoai** [comment]
You can use anonymous function to format values in TEXT_LIST. As for the climate, we are only able to output what we get from the API and we need to send the very same values back.
