### ISSUE TITLE
Can i pull data from a REST API and show it in TileBoard ?

### ISSUE THREAD

**Issue by donnib** [resoai/TileBoard#239]
Hi,
I have Grocy Hass.io addon. Is there a way i can get data shown on TileBoard ? I see grocy has an REST API.

/donnib

**Comment by cgarwood** [comment]
You can, but you'll have to manually write the code to query the REST API on a timer and update tile values.

**Comment by MichielMag** [comment]
While this is closed, I'm adding a question. How would one "update tile values"?
