### ISSUE TITLE
Issue: Media_Player volume slider overlaps subtitle

### ISSUE THREAD

**Issue by vpnmaster** [resoai/TileBoard#24]
Media_Player volume slider overlaps the subtitle layer

**Comment by resoai** [comment]
Can you please post a screenshot?

**Comment by vpnmaster** [comment]
Sure

![image](https://user-images.githubusercontent.com/4130346/41708210-9cc321b8-7548-11e8-8186-8e38addbdc37.png)

**Comment by Evgeny-** [comment]
This tile is not supposed to use subtitle, so in production we showed song name in the `state`, not a perfect solution, but media_player component is too complicated in terms of variability.
