### ISSUE TITLE
how can I close my climate

### ISSUE THREAD

**Issue by tongt15** [resoai/TileBoard#240]
If the climate doesn't include off mode, how can I close my ac from climate tab?

**Comment by resoai** [comment]
How do you “close” it from HA?

**Comment by tongt15** [comment]
> How do you “close” it from HA?

Currently, When I click the thermostat card, it will shows the on/off button. The off state is not listed in operation mode.
![image](https://user-images.githubusercontent.com/21130335/60380516-8daa9d80-9a79-11e9-8f63-f36f062d2a0d.png)

**Comment by tongt15** [comment]
![image](https://user-images.githubusercontent.com/21130335/60380518-9ac78c80-9a79-11e9-9c72-9e84aa34a4d6.png)

**Comment by resoai** [comment]
We list all operation modes that are exposed via the API.

**Comment by resoai** [comment]
What HA service is being called for on/off? Also, please provide us with the entity dump from dev-tools.

**Comment by tongt15** [comment]
![image](https://user-images.githubusercontent.com/21130335/60380615-fb0afe00-9a7a-11e9-83cf-fce0c4befdc7.png)

Service: climate.turn_off
{
"entity_id": "xxxxx "
}
like this

**Comment by resoai** [comment]
You can create a separate SWITH tile to turn in on and off.

**Comment by resoai** [comment]
You can create a SWITCH or CUSTOM tile to turn it on and off.

**Comment by tongt15** [comment]
you mean I need Two Tab to controll one AC right? one is climate one is switch?

**Comment by resoai** [comment]
That is correct.
