### ISSUE TITLE
Stacking of groups / multiple groups per row/column

### ISSUE THREAD

**Issue by rvliege** [resoai/TileBoard#241]
Groups are now aligned horizontally or vertically with one group per row/column. It would be nice if multiple groups could 'stack' in a row or column allowing multiple groups per row/column.
This way empty space can be filled with other content including a group title to nicely separate it from the rest.

**Comment by resoai** [comment]
This would kill the grid layout

**Comment by rvliege** [comment]
I understand this will not be possible with the current layout? That's too bad but at least I know I won't have to try any further.

**Comment by resoai** [comment]
You could always assign custom CSS to a tile, essentially making it look like a group title and playing with tile height and position.
