### ISSUE TITLE
[Feature request] Swipe to toggle page

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#242]
On mobile it would be natural to allow switching pages using swipe action instead of trying to hit tiny page selector buttons.

I have actually implemented this for myself but changes are fairly extensive so not sure if you would be interested. I did this:
 - using hammer library (also replaces currently used 'long.press' library)
 - switches page stacking to be horizontal when menu is at the bottom (for swipe direction to follow toggle animation)

**Comment by resoai** [comment]
Please feel free to share the code
