### ISSUE TITLE
For sensors, support refresh interval.

### ISSUE THREAD

**Issue by Boosik** [resoai/TileBoard#243]
I have a google home mini integrated with google assistant and I'd like to show times and alarms or TileBoard.
I came up with this sensor tile:
```
                  {
                     position: [0, 2],
                     type: TYPES.SENSOR,
                     title: 'Timer',
                     id: 'sensor.living_room_speaker_timer',
                     state: false, // hidding state
                     refresh: 100,
                     filter: function (value) { // optional
                        var now = new Date();
                        var timer = new Date(value);
                        var diffMs = (timer - now);
                        var diffMins = Math.round(((diffMs % 86400000) % 3600000) / 60000);
                        var seconds = (diffMs / 1000).toFixed(0);
                        var minutes = Math.floor(seconds / 60);
                        var hours = "";
                        if (minutes > 59) {
                            hours = Math.floor(minutes / 60);
                            hours = (hours >= 10) ? hours : "0" + hours;
                            minutes = minutes - (hours * 60);
                            minutes = (minutes >= 10) ? minutes : "0" + minutes;
                        }

                        seconds = Math.floor(seconds % 60);
                        seconds = (seconds >= 10) ? seconds : "0" + seconds;
                        if (hours != "") {
                            return hours + ":" + minutes + ":" + seconds;
                        }
                        return minutes + ":" + seconds;
                     }
                  }
```
Problem is that "refresh: 100" does not work and my tile is refreshed only when other sensor values are updated or when I actually use some switch.

**Comment by resoai** [comment]
Refresh is only valid for IFRAME tiles, otherwise all values are updated whenever the actual value changes. This is by design.

**Comment by Boosik** [comment]
Problem is, that Home assistant does not refresh the state, it only sets DateTime of when the timer is supposed to finish and calculates remaining time in lovelace. 
![image](https://user-images.githubusercontent.com/939813/61143293-168df400-a4d2-11e9-9b43-6a9cee5e32d4.png)
![image](https://user-images.githubusercontent.com/939813/61143311-1e4d9880-a4d2-11e9-81e9-5ddfa40a3484.png)
Any idea how to resolve it with the current implementation of sensor cards?

**Comment by resoai** [comment]
You can probably use `setTimeout` and call `angular.element(window).triggerHandler('view:updated');` every second or so.

**Comment by Boosik** [comment]
That worked! It now updates every second.

**Comment by oneseventhree** [comment]
> That worked! It now updates every second.

are you able to show me your whole code? I am also struggling with this problem
