### ISSUE TITLE
Climate tile broken in HA 0.96 due to major component changes.

### ISSUE THREAD

**Issue by kalash-** [resoai/TileBoard#245]
After update tile looks like this 
![image](https://user-images.githubusercontent.com/919178/61494727-a0046100-a9bf-11e9-8331-13e228b6a6fa.png)

List of changes is here https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html

**Comment by jncanches** [comment]
It's because operation_modes attribute is now hvac_modes. I will fix it in my install in a few hour. Will post the update here

**Comment by resoai** [comment]
I think that hvac_mode is useless now, perhaps we need to map the selection to presets. Unfortunately I can’t even test anything, as KNX climate is completely broken in this update.

**Comment by resoai** [comment]
This should fix it.
