### ISSUE TITLE
[Feature request] Android-like screensaver 

### ISSUE THREAD

**Issue by LordBoos** [resoai/TileBoard#247]
Hi, 
I'd appreciate if there was Android-like screensaver.
By that I mean black screen with time and date, but the time and date periodically (like every 5-10 minutes) change it's place on the screen to random positions. This is to prevent screen burn-in.
I know that I can use leftBottom, leftTop, rightBottom, rightTop, but 4 fixed positions are not enough to eliminate screen burn in.

Currently I'm using in-build Android screensaver on my always-on tablet with tileboard, but that causes disconnections and tileboard refreshes itself before it can be used when screensaver is closed and tileboard loaded and that is really inconvenient because of the time it takes to reload.

**Comment by resoai** [comment]
You can always make the function which will change the position of the clock randomly if you wish, simply change or assign the style of div to `position: absolute;`

**Comment by Boosik** [comment]
I'm not really experienced in web development so I have added following script to index.html:
```
      function getRandomPosition(element) {
        var x = document.body.offsetHeight-element.clientHeight;
        var y = document.body.offsetWidth-element.clientWidth;
        var randomX = Math.floor(Math.random()*x);
        var randomY = Math.floor(Math.random()*y);
        return [randomX,randomY];
      }
      
      setInterval(function(){
        var element = document.getElementsByClassName('screensaver-content--left-top')[0]
        if (typeof element !== 'undefined') {
          var xy = getRandomPosition(element);
          element.style.top = xy[0] + 'px';
          element.style.left = xy[1] + 'px';
        }
      }, 300000)
```
This works, but I have one problem with it. The first position of the date and time element always starts at the top left and only gets random position after the setInterval function is triggered. 
Is there any event or something that would allow me to detect that the screensaver just started so I can trigger my function?

**Comment by resoai** [comment]
You could check if `screensaver` DIV is visible in a separate function which will be called every few seconds and only change the position if that DIV is actually visible.

https://github.com/resoai/TileBoard/blob/master/index.html#L305
