### ISSUE TITLE
[feature request] Can I have a 'time' tile in addition to 'datetime'

### ISSUE THREAD

**Issue by DeviousPenguin** [resoai/TileBoard#252]
I've quite like to set times using Tileboard, such as a time to turn the lights off every evening, it would be nice if there was a 'time' tile.

Or could I somehow use the 'datetime' tile with some elements hidden using CSS?

**Comment by resoai** [comment]
If I remember correctly this should depend on HA’s entity:

 only_time:
    name: Input with only time
    has_date: false
    has_time: true

**Comment by DeviousPenguin** [comment]
Thanks very much, with ' has_date: false' for the entity set to false, it gives only time input, which is exactly what I'm after. :) I can tweak layout with CSS a little to make the numbers fill the tile.
