### ISSUE TITLE
[Feature Request] Bar/gauge Tile

### ISSUE THREAD

**Issue by helenclarko** [resoai/TileBoard#253]
The work you have put into tileboard is amazing, it looks great and it just works!

Wanting to know what the plan is for adding additional tiles. I'm looking for a gauge or a simple bar tile. Something similar to the bar card plugin for Home assistant.

**Comment by resoai** [comment]
Sadly due to big changes in my life I presently can’t afford to spend time on the development. Perhaps someone could implement it and create a PR.

**Comment by helenclarko** [comment]
Would donations help in any way or is it a lack of time to work on the project?

**Comment by resoai** [comment]
It is purely complete lack of time and other priorities.

**Comment by rchl** [comment]
Integrating something like https://github.com/ashish-chopra/angular-gauge should be quite easy.

**Comment by helenclarko** [comment]
Wow that looks really nice.

**Comment by inxaos** [comment]
I opened https://github.com/resoai/TileBoard/pull/256 where I implemented the above-linked gauge display as a Tile option.  Let me know what you guys think.

**Comment by helenclarko** [comment]
DUDE! Boy am I glad you are contributing to this project. I was a little worried when resoai mentioned he was unable to work on the project (But life always comes first). Thanks for the work on this.

**Comment by resoai** [comment]
Having a newborn does not leave you with any time even to sleep...

**Comment by helenclarko** [comment]
Ha, when I said life always comes first I didn't realize just how much that would be true. I have a 3 month old, so fully understand where you are coming from.

Anyway, I'll stay out of this now, no need for me to turn this into a chat lol.

**Comment by helenclarko** [comment]
Implemented in #256
