### ISSUE TITLE
Door sensor

### ISSUE THREAD

**Issue by grm** [resoai/TileBoard#257]
Hello,

I have been looking in the tiles to a tile showing a door sensor (open/close) but could not find one.
Maybe you can orient me to the right tile to do so ?
I was thinking of a custom, but the fact is that it only displays information without interaction.

Btw, thx for tileboard, i really love it and keep up the good work !

Jérémie

**Comment by cgarwood** [comment]
I use SENSOR_ICON tiles for open/close sensors:

Function I added to config.js above the area where pages/groups/etc are defined:
```
function generateDoorWindowSensorTile(entity_id, title, subtitle) {
  return {
    title: title,
    subtitle: subtitle,
    type: TYPES.SENSOR_ICON,
    id: entity_id,
    states: {
      on: "Open",
      off: "Closed"
    },
    icons: {
      on: "mdi-alert-circle",
      off: "mdi-checkbox-marked-circle"
    },
    classes: ["binary-sensor-security"]
  };
}
```

Using the tile:
```
        mergeObjects(
          { position: [3, 0] },
          generateDoorWindowSensorTile(
            "binary_sensor.kitchen_window",
            "Kitchen",
            "Windows"
          )
        ),
```

**Comment by grm** [comment]
Thx, 

It works like a charm.
AS a reference, I just changed the icon to :

`
      on : "mdi-door-open",
      off: "mdi-door-closed"
`

which is more adapted to my use case.

Thx a lot for your help !
