### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by fmandal** [resoai/TileBoard#259]
Is there a way to override the locale setting? I'm now having the day in english, would be nice to get it in my local language.

**Comment by attenzione** [comment]
You can change it in `config.js` to another format, excluding naming. For example 2019-09-16
or include i18n script for Angular filters:
```
<html ng-app>
 <head>
….
   <script src="angular.js"></script>
   <script src="i18n/angular-locale_de-de.js"></script>
….
 </head>
</html>
```
Source: https://docs.angularjs.org/guide/i18n
