### ISSUE TITLE
Issue: tileSize and icon position

### ISSUE THREAD

**Issue by vpnmaster** [resoai/TileBoard#26]
Icons aren't centered in tile when the tileSize is smaller or bigger than 150

**Comment by Evgeny-** [comment]
You may change @tileSize variable in main.less file https://github.com/resoai/TileBoard/blob/master/styles/main.less#L6 But after you will be needed recompile less file.

**Comment by vpnmaster** [comment]
I don't understand why you are allowing the change of tile size while all other values are hardcoded.
Here is a screenshot with tileSize @120

![image](https://user-images.githubusercontent.com/4130346/41716657-d7bd9c5a-755f-11e8-829a-e20d5c42398a.png)

**Comment by Evgeny-** [comment]
@vpnmaster first of all, it's not hardcoded, it's just an variable in the .less file, second tiles with icons isn't only tiles we have, and it's useful e.g. for pages with cameras, third whole project supposed to be private pet project with it's problems in term of extendability.

**Comment by vpnmaster** [comment]
I understand.
Thank you
