### ISSUE TITLE
Scripts should load in order.

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#262]
I noticed that, when I do something complicated in config.js, then init.js complains about the CONFIG variable not existing.

I suspect that is because scripts are loaded asynchronously, but are actually meant to be run in order, because they rely on each other. The scripts should therefore be loaded and executed sequentially.

Here is how this can be done: 
https://stackoverflow.com/questions/27701185/javascripts-arent-executed-sequentially-in-modern-browser

(Something complicated = creating another HApi object to automatically generate pages.)

**Comment by rchl** [comment]
Scripts *are* loaded synchronously. Seems like it's using `document.write` to append all scripts and that is synchronous.

Your issue might be triggering when there is an error in config.js for example.

**Comment by akloeckner** [comment]
You're right. I just checked what happens before the original Api is instantiated. And, as it seems, the Api requires CONFIG.serverUrl to be set. Thanks for the hint!
