### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by abeksis** [resoai/TileBoard#27]
I managed to align right  a question, how do I change the position of the table (where my photos and my wife it will be on the right) 

https://imgur.com/a/cvtgYxx

**Comment by resoai** [comment]
I believe you can simply play around rearranging objects within `groups: []`

**Comment by abeksis** [comment]
Yes I saw there, but I thought you had a quick solution instead of I would sit on it

**Comment by resoai** [comment]
To be frank this is the quickest and most logical thing to do :)

**Comment by abeksis** [comment]
Lol, thanks anyway.

What do you think of what I did?

**Comment by resoai** [comment]
Looks good! what device are you planning to run it on?

**Comment by abeksis** [comment]
It's going to sit on the iPad at the entrance to the house

**Comment by resoai** [comment]
Android devices are a bit more suitable for such things as you  can install apps like Fully Kiosk Browser and use front-facing camera as a motion sensor and turn the screen on whenever someone is passing by (just a thought).

https://play.google.com/store/apps/details?id=de.ozerov.fully&hl=en_US
