### ISSUE TITLE
URL filling up with code and oauth

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#279]
When using TileBoard for a while, its URL tends to evolve into something as this:

`https://localhost:8123/local/tileboard/index.html?oauth=1&oauth=1&oauth=1&oauth=1&oauth=1&oauth=1&oauth=1&oauth=1&oauth=1&code=3f995498dd8a4e09a6315da3369c85&code=96b3f2af100146bc9f290934de17de&code=cda2e5e8019527b98ac16b4295b97&code=c15025bcae6a4c5e9e9507b475e531&code=3fb5277426a447d894f6a2e08fc8cdb&code=051c410d71a4438799313c5613450&code=fb63b9021e4b68bb91f49280e23ada&code=a9b14ac91ea94849898643254566b&code=d8a471eecbf4cf1aa6e480f6874b1fa&oauth=1`.

It might be related to my unstable VPN connection.

**Comment by rchl** [comment]
3e504c804a0f28a50e11ab36d66bc7c6bef498b9 is probably gonna make this less of a problem as any random error won't trigger re-authentication. But it would still happen if actual authentication error happens.

**Comment by akloeckner** [comment]
Ok. I'll monitor and report back or close the issue. Thanks!
