### ISSUE TITLE
accessible through duckdns

### ISSUE THREAD

**Issue by coltju** [resoai/TileBoard#281]
I noticed the warning where you said tileboard is accessible through the web if e.g. duckdns is used, but when i tried the tileboard link from outide my LAN i was able to see the HA-token with pressing F12 in my browser. 

In my case it would be best if tileboard wouldn't be accessible from the outside. So it would be nice if that could be added someway in tileboard.

**Comment by resoai** [comment]
Just don’t use a long-lived token.
