### ISSUE TITLE
Header blocks interaction with tiles

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#283]
The header blocks interaction with tiles, even if those are simply at the same vertical position. I assume, the header `div` spans the whole screen width, even if only the left header is used.

Example: the whole pinkish area is not clickable here:

![IMG_20191031_003307](https://user-images.githubusercontent.com/7125061/67907054-ef3d5e80-fb76-11e9-9391-ec967f04f99e.png)

That's the relevant header configuration:
```
   header: { // https://github.com/resoai/TileBoard/wiki/Header-configuration
      left: [
         {
            type: HEADER_ITEMS.TIME,
            styles: {
               margin: '55px 0px 0px -10px', //trbl
               transform: 'rotate(-90deg)',
               border: '0px solid red',
            },
         }
      ]
   },
 ```

**Comment by rchl** [comment]
I think the options for fixing this are to either:
 - make it clear visually that the header area is there and not let entities be positioned there
 - make it invisible to clicks. That could, in theory, break someone's use cases if they have clickable things there. And it just plain looks bad when header content is drawn on top of entities.

**Comment by akloeckner** [comment]
A third option could be to let the header only take up horizontal space it actually needs?

For me, the easiest fix would probably be your second option. Is there a simple custom css that I could try?

**Comment by rchl** [comment]
`pointer-events: none;` to make clicks go through.

**Comment by akloeckner** [comment]
Thanks! 

I put this in `custom.css` and it fixes the problem for me. 

```
.header {
  pointer-events: none;
}
```

**Comment by rchl** [comment]
I think it might not be ideal to add that CSS. It would work in more cases but still, things could obstruct tiles.

**Comment by akloeckner** [comment]
Ok. Since it works for me, I close the issue.

Thanks for your help!
