### ISSUE TITLE
12th page icon not displayed

### ISSUE THREAD

**Issue by grm** [resoai/TileBoard#287]
Hello,

Is there a max number of pages ? 
It seems that, starting at the 12th pages, the icon in the menu is not shown. I can still go to the 12th page by swiping the screen.

Is there such a limit ?

Thx,
Grm

**Comment by resoai** [comment]
There is no hard limit as to the number of pages. Perhaps the rest of the pages simply fallout out of the visible area?

**Comment by grm** [comment]
I tried with both vertical and horizontal and i have the same issue ont the tablet.
On my laptop, I have all distinct menus.
But on the tablet, the last one is not shown (which is weird, there is some space left on the screen). I will try to take some screenshots in order to show you.

**Comment by grm** [comment]
Hello,

Here are the two screenshots
From the tablet :
![Screenshot_2019-11-17-15-57-50](https://user-images.githubusercontent.com/70435/69009202-78181080-0953-11ea-8fee-cae8ad98b3cc.png)

From the computer :
<img width="1440" alt="Screenshot 2019-11-17 at 15 57 07" src="https://user-images.githubusercontent.com/70435/69009186-51f27080-0953-11ea-803a-b5a8dfeb0fd6.png">

Thank you for your help.

**Comment by AalianKhan** [comment]
@grm have you tried different browsers (chrome/safari). Which OS are you running?

**Comment by Evgeny-** [comment]
@grm it looks a bit like your icon didn't loaded, try to tap in a place where an icon supposed to be, or change the type of icon. Or may be just cache.

**Comment by grm** [comment]
> @grm have you tried different browsers (chrome/safari). Which OS are you running?

I am using a chrome base browser (webview) in an android samsung tablet !

**Comment by AalianKhan** [comment]
Try using a different browser and see if it makes a difference. Your can use this browser if your want https://play.google.com/store/apps/details?id=de.ozerov.fully

**Comment by grm** [comment]
> @grm it looks a bit like your icon didn't loaded, try to tap in a place where an icon supposed to be, or change the type of icon. Or may be just cache.

Indeed, the zone is clickable and works but the icon does not show up (even after emptying cache).
I changed the icon, and now it works perfectly.

I am not sure  why this icon cannot shows up, but now everything works. The issue does not seems related to tileboard.

Thanks for your help.

**Comment by ajaxhanna68** [comment]
all

need help, please.
I have both vertical and horizontal icon shows on my desktop but no icon shows on my samsung tablet....
Without the icons but the tiles is working.

Please assist. thank you
