### ISSUE TITLE
Issue with authentivation token manipulation in last commit b228791

### ISSUE THREAD

**Issue by grm** [resoai/TileBoard#288]
Hello,

it seems that the latest version ( b228791 ) of Tileboard has an issue with the auth token manipulation with the following message : 
```TypeError: Cannot read property 'then' of undefined```

The error seems to come from the models/api.js fil here when calling **this.getToken().then(....)**.

I am far from a JS expert, but i may try to have a look into it soon.
Currently I took an older commit and it works great.

Grm

**Comment by rchl** [comment]
Will have a look at the code soon (currently in transit). What platform/browser/version?

**Comment by rchl** [comment]
Can you point out the exact code line where this happens for you? There is no `this.getToken().then` line, there is `_getToken` but the code there looks fine to me.

**Comment by grm** [comment]
My bad, as i have typed the ticket after reverting, i forgot about the underscore.

Here are the screens from the developer tools.

<img width="697" alt="Screenshot 2019-11-11 at 20 00 25" src="https://user-images.githubusercontent.com/70435/68613114-55eb4200-04be-11ea-8ab9-a83fcbd60f9d.png">

<img width="558" alt="Screenshot 2019-11-11 at 20 00 46" src="https://user-images.githubusercontent.com/70435/68613113-55eb4200-04be-11ea-80f5-41e0352ede6a.png">

I am on Mac using chrome (Version 78.0.3904.70 (Official Build) (64-bit)) and on android using also chrome !

I had a quick look into it (trying to have a new one tomorrow) and it seemed also fine ...  Maybe i need to adapt my config.js (which was working fine before and works with the previous version) ?

Grm

**Comment by rchl** [comment]
And are you sure you don't have any local modifications in your api.js?
I can see how it would fail if any code path in `_getToken` would not return a promise but as far as I can tell it doesn't.
If you would be willing to debug it, you could place a breakpoint on that line and once it breaks, step into and over the code to see how it returns something that it shouldn't.

**Comment by rchl** [comment]
Never mind, I see that it returns undefined in a case when using long-lived token (I think). I will look into it.

**Comment by grm** [comment]
Working like a charm now.
Thanks,

Grm
