### ISSUE TITLE
TypeError: Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by syphernl** [resoai/TileBoard#29]
I'm seeing one of these errors for each state change that comes by:
```
TypeError: Cannot read property '_c' of undefined
    at b.MainController.$scope.getSliderConf (main-controller.js:474)
    at fn (eval at compile (angular.min.js:241), <anonymous>:4:393)
    at m.$digest (angular.min.js:147)
    at updateView (main-controller.js:1298)
    at handleEvent (main-controller.js:1282)
    at handleMessage (main-controller.js:1270)
    at main-controller.js:1171
    at api.js:138
```

**Comment by cgarwood** [comment]
Looks like its related to a slider config. Do you have any sliders in your configuration? If so, could you post the configuration for them? Also, are you running the most recent code?

**Comment by resoai** [comment]
Could you please try getting latest code and try now? I might have resolved the issue.

**Comment by resoai** [comment]
I think I've found the place where it occurs but I need some time to debug and find a solution.

**Comment by resoai** [comment]
Could you please check if you see any errors now? Also, it is a good idea to double-check sliders in lights, media_player and input_number

**Comment by syphernl** [comment]
The config I'm currently using is the default/dummy config. With the last revision it is still showing the same error for each state update it receives.

**Comment by resoai** [comment]
Did you try clearing browser's cache?

**Comment by syphernl** [comment]
Yes, I've also tried in in an incognito window but the result is the same.

**Comment by resoai** [comment]
Could you please try now?

**Comment by syphernl** [comment]
Tested and it is working fine now! :+1:

**Comment by resoai** [comment]
Perfect!
