### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by AalianKhan** [resoai/TileBoard#292]
Hello, I was doing some documentation about tiles and how they work but I think I don't understand the concept correctly. can someone lead me in the right direction? here is the [page](https://github.com/resoai/TileBoard/wiki/Adding-Tiles). BTW its not completely finished

**Comment by resoai** [comment]
Home Assistant variant you mentioned does not make much sense as 1/3 has no equivalent in HA.

**Comment by AalianKhan** [comment]
@resoai yup I am aware of that. What should I change it to tho?

**Comment by akloeckner** [comment]
Maybe split the table on two? Types with HA equivalent. And types without, but with a short description of what they do. 

Or just always, what they do?  E.g. “adds a `sensor` to your dashboard“ or “adds a tile to open any arbitrary website in a popup“?
