### ISSUE TITLE
History popup issues

### ISSUE THREAD

**Issue by resoai** [resoai/TileBoard#296]
As window becomes wider, graph goes outside of visible area of popup:

![image](https://user-images.githubusercontent.com/11579512/69157772-59458580-0add-11ea-8307-5e3d29bc7184.png)

Also, what do you guys think about loosing background under close button? Perhaps even moving it to the left before title, just like in HA's UI.

**Comment by resoai** [comment]
This is how it look like with:

```
float: left;
  width: 35px;
  height: 35px;
  line-height: 50px;
  font-size: 25px;
```

![image](https://user-images.githubusercontent.com/11579512/69169770-d3cbd080-0af0-11ea-8b67-80a864ab88e4.png)

**Comment by rchl** [comment]
I guess I'd be fine with that too but it will make the close button harder to reach (on phones especially but tablets also, I guess, if you are right-handed).

**Comment by resoai** [comment]
It just looks miles better to me :)

**Comment by rchl** [comment]
OK, I'll create PR fixing both. :)
