### ISSUE TITLE
Feature Request: Tile opacity and 'group' backgrounds

### ISSUE THREAD

**Issue by xAPPO** [resoai/TileBoard#3]
Feature Request:  

  Consider allowing each tile background image to have an opacity set within the config.js 

  Consider allowing a background image to be defined in config.js for each group and for that too to have an optional opacity value.

**Comment by Evgeny-** [comment]
What do you mean by group background?

**Comment by xAPPO** [comment]
When you define a group like the 'First Group' in your default config.js - that's what I'm meaning.  So that it is then a background to all the items that you then include in that group.   Each group wcould have a background and as they are each defined with a width and a height you should be able to size the backgrounds accordingly.  They would sit above the page background and behind the tiles and they would be removed (along with the group tiles) when you changed pages.

**Comment by Evgeny-** [comment]
Tbh do not see reason for doing background for groups in our case, though we can make some basic style object for groups, so you'll be able to make background for them. In the other hand background opacity for tiles have sense, will look into it

**Comment by xAPPO** [comment]
OK.. it’s not a big need for me.  It just allows people to create visually nicer presentations as you can’t use the main background for this as it’s static across all pages. i.e. maximises customisation.

 I suppose one usage might be where you are displaying groups that are in fact rooms, and you might put an outline floorplan or image of the room behind the items that are in that group to provide easier identification of where the particular item is e.g. for lights or door open sensors.

**Comment by xAPPO** [comment]
I have found a way around this request for group backgrounds (by just using an oversized and overlapping tile) which works really well. So I'll withdraw that feature request. 

Thanks for implementing bgOpacity so promptly ..

I'll close this issue now.

**Comment by sy-per** [comment]
> I have found a way around this request for group backgrounds (by just using an oversized and overlapping tile) which works really well. So I'll withdraw that feature request.
> 
> Thanks for implementing bgOpacity so promptly ..
> 
> I'll close this issue now.

Hello,
I have the same request as you for the same need!
How do you do to have a background image for a group?
Thank you
