### ISSUE TITLE
HLS Streaming

### ISSUE THREAD

**Issue by resoai** [resoai/TileBoard#306]
One thing I would really like to have in TileBoard is proper HLS camera streams. I did not investigate it much, but the URL for each stream looks like `/api/hls/{token}/playlist.m3u8` where token by the looks of it is being generated in `request_stream`: 

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/stream/__init__.py#L51

**Comment by resoai** [comment]
Ok, it would appear that you can request url for the stream:

```
this.apiRequest({
    type: 'camera/stream',
    entity_id: item.id,
    format: 'hls'
}, function(data) {
    var url = data.result.url;
    alert(url);
});
```

@rchl @akloeckner anyone up for implementing `CMAERA_STREAM` tile?

**Comment by akloeckner** [comment]
I'm not. That's above my skill level. And I have no use case for it...

**Comment by rchl** [comment]
I wouldn't have a way to test it so it would be tricky to work on it.
Maybe I should consider getting a camera and then I would have the incentive to work on it at least. :)
Do you have any that you could recommend @resoai?

**Comment by resoai** [comment]
> I wouldn't have a way to test it so it would be tricky to work on it.
> Maybe I should consider getting a camera and then I would have the incentive to work on it at least. :)
> Do you have any that you could recommend @resoai?

I’m using Hikvision with their own NVR. They are much cheaper than Mobotix and Axis. They definitely are still pain in the ass but are widely used and well built. If you are looking for something less “commercial grade”, than probably any camera that exposes RTSP stream would do.

**Comment by rayzorben** [comment]
> I wouldn't have a way to test it so it would be tricky to work on it.
> Maybe I should consider getting a camera and then I would have the incentive to work on it at least. :)
> Do you have any that you could recommend @resoai?

I'd be willing to share my rtsp stream with you over the internet for testing.

**Comment by rchl** [comment]
I'm not familiar with any of that so not sure if that would be enough. There is talk about HLS here. How does that relate to RTSP? Is HLS basically a playlist format that includes a URL for the RTSP stream?

Which [integration](https://www.home-assistant.io/integrations/) is used for this, how the configuration looks like and where is that API documented that @resoai mentioned in the [comment above](https://github.com/resoai/TileBoard/issues/306#issuecomment-561608222)?

And thanks for the offer but I could probably work with some test stream like at https://www.wowza.com/html/mobile.html

**Comment by resoai** [comment]
I've created a very rough and dirty code for rudementary HLS support.

**Comment by resoai** [comment]
HLS is indeed a playlist format which is playable directly in the browser. HomeAssistant has adeed `stream` component a while ago which repackages RTSP streams but did not officially provide any information about the API. Please feel free to tweak the code, I only had a very little time to play with it.

**Comment by rchl** [comment]
That HLS script is huge. :)

**Comment by resoai** [comment]
I know, I don't even know if we need it but I was desperate to quickly add functionality no matter what.

**Comment by rayzorben** [comment]
I am using tileboard as a dashboard being cast to my TV via chromecast. For that I wanted live streaming tiles of my camera without having to click. I added the following to support that to `index.html`:

```
<div ng-if="item.type === TYPES.CAMERA_STREAM"
  class="item-entity-container -below">
    <div class="item-camera">
      <camera-stream item="activeCamera" entity="entity" freezed="false"></camera-stream>
    </div>
</div>
```

In order to get the video to fit correctly I modified `scripts/directives.js` and added height 100% as well:
```
el.style.width = '100%';
el.style.height = '100%';
```

Works like a charm, but the only issue is it moves my whole group down from the top. Trying to figure that out.
