### ISSUE TITLE
Issue: maps.googleapis.com displaying error 403 after last update

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#31]
```
The HTTP 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.
```

any clue what is causing this?

**Comment by nayaj** [comment]
<img width="396" alt="skarmklipp" src="https://user-images.githubusercontent.com/40382766/41762233-674e6a4e-75fa-11e8-8887-228f33494f8a.PNG">

(sorry for my swedish  browser)

**Comment by nayaj** [comment]
when i open it from a local dir it works.. so gotta be something on my end.. sorry, closing this

**Comment by resoai** [comment]
I believe Google starts to block the requests. Perhaps with some of the recent API changes they want and API key when they get several concurrent requests. I would suggest to use Yandex map for now and we will do a bit of reading about GM.

**Comment by nayaj** [comment]
any prerequisites for yandex?

**Comment by resoai** [comment]
Nope. It just works.

**Comment by nayaj** [comment]
Sweet, works
