### ISSUE TITLE
Access objects in entities

### ISSUE THREAD

**Issue by pointlevel** [resoai/TileBoard#315]
Hello! 

Great board, great job! 

How can i access an entities objects, like for the weather?

Im trying `&weather.smhi.attributes.forecast[1].temperature` like i can do in homeassistant, but it only prints [object Object],[object Object]...etc.

**Comment by rchl** [comment]
Have a look at entity data in Developer Tools => State in Homeassistant. Maybe that will help you find out the problem. If not, post the data here and also post your tile configuration.

**Comment by pointlevel** [comment]
This is the Attributes for the entity weather:
`temperature: 4
humidity: 89
pressure: 998
wind_bearing: 218
wind_speed: 12
visibility: 38.9
attribution: Swedish weather institute (SMHI)
forecast: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
cloudiness: 62
friendly_name: Home`

And i am trying to access each object in the attribute "forecast". The each forecast looks like this:

`{'datetime': '2019-12-06T12:00:00', 'temperature': 4, 'templow': -3, 'precipitation': 3.0, 'condition': 'partlycloudy'}`

And i finally trying to call it from tileboard like this: 

`'&weather.smhi_home.attributes.forecast[1].temperature`

But the result is `[object Object]`

**Comment by rchl** [comment]
I think TileBoard doesn't parse such string properly when there is indexed access to an array. You can probably just use a function instead of string. Something like
```
function (item, entity) {
  return entity.attributes.forecast[1].temperature;
}
```

**Comment by pointlevel** [comment]
Thanks! Any suggestion on how to implement it in this example-code?

`list: [1,2,3,4,5].map(function (id) {
      var forecast = "&sensor.dark_sky_overnight_low_temperature_" + id + "d.state - ";
      forecast += "&sensor.dark_sky_daytime_high_temperature_" + id + "d.state";
      forecast += "&sensor.dark_sky_daytime_high_temperature_" + id + "d.attributes.unit_of_measurement";

      var wind = "&sensor.dark_sky_wind_speed_" + id + "d.state";
      wind += " &sensor.dark_sky_wind_speed_" + id + "d.attributes.unit_of_measurement";

      return {
         date: function () {
            var d = new Date(Date.now() + id * 24 * 60 * 60 * 1000);
            return d.toString().split(' ').slice(1, 3).join(' ');
         },
         icon: "&sensor.dark_sky_icon_" + id + ".state",
         //iconImage: null, replace icon with image
         primary: forecast,
         secondary: wind
      }
   })`

**Comment by rchl** [comment]
Here's a start, you should be able to complete it.
```
list: [1,2,3,4,5].map(function (id) {
  return function(item) {
    var sensor = this.states['sensor.dark_sky_daytime_high_temperature_' + id + 'd'];
    // ...
  };
}
```
This takes advantage of the fact that if you return an array of functions, those will be called and then you'll have access to states from `this.states`.

**Comment by pointlevel** [comment]
Sorry, but i dont get the idea!

**Comment by pointlevel** [comment]
Solved it like this: 

```
list: [1,2,3,4,5].map(function (id) {
                        return {
                           date: function () {
                              var weekday = new Array(7);
                              weekday[0] = "Sön";
                              weekday[1] = "Mån";
                              weekday[2] = "Tis";
                              weekday[3] = "Ons";
                              weekday[4] = "Tor";
                              weekday[5] = "Fre";
                              weekday[6] = "Lör";
                              var d = new Date(Date.now() + id * 24 * 60 * 60 * 1000);
                              return weekday[d.getDay()];
                           },
                           icon: function() {
                              var sensor = this.states['weather.smhi_home'];
                              return sensor.attributes.forecast[id].condition;
                           },
                           primary: function() {
                              var sensor = this.states['weather.smhi_home'];
                              var forecast = sensor.attributes.forecast[id].templow + " - ";
                              forecast += sensor.attributes.forecast[id].temperature + "°C";
                              
                              return forecast;
                           },
                           //secondary: ''
                        }                   
                     })
```

Thanks for pointing me in the right direction.
