### ISSUE TITLE
Progress bar for TYPES.TEXT_LIST

### ISSUE THREAD

**Issue by mortydk** [resoai/TileBoard#316]
Hi,

First i want to say thanks for this great dashboard. Very easy to use and good looking!

Is it currently possible to make some sort of linear progress bar? Could really use something like that in text_list for memory usage, disk usage etc. Just haven't been able to find a solution so far.

Thanks
Morten

**Comment by resoai** [comment]
http://textart4u.blogspot.com/2012/03/loading.html

**Comment by mortydk** [comment]
Thanks for the respons resoai :)

It's a solution, but not exactly what i was hoping for hehe.

Would i be able to change bgcolor of a specific line (class="item-list--item) from config.js?

And use something like this:
http://jsfiddle.net/9px8p/
