### ISSUE TITLE
Feature_request: color customization

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#32]
Would be nice to be able to assign text/icon color for specific tiles/entities. For example my Sonos media_players use albumpictures as background and when its a light background the controls are hard to see.

**Comment by resoai** [comment]
You can adjust any  colours in the css file as desired however for background of media player I would suggest to simply make the opacity 50% or so:

```
bgSuffix: '@attributes.entity_picture',
bgOpacity: 0.5
```

**Comment by nayaj** [comment]
Dont seem to get it working.

{
   position: [7, 1],
   width: 2,
   title: 'Sonos One - Köket',
   id: 'media_player.kitchen',
   type: TYPES.MEDIA_PLAYER,
   showSource: true,
   state: '@attributes.media_title',
   bgSuffix: '@attributes.entity_picture',
   bgOpacity: 0.5
},

**Comment by resoai** [comment]
It should work. You might want to clear browser's cache and close the window.
