### ISSUE TITLE
panning when scrolling

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#323]
With the new panning feature, my scrolling becomes awkward:

I have the menu of the left and pages set up such that groups fit my portrait mobile screen. I have multiple groups on a page, so I need to scroll left and right so see them.

With swipin to change pages, my scrolling would be exactly horizontal. Now, with the panning, my page also moves up and down when scrolling, which looks strange.

I must admit, on my bigger ipad, it actually looks ok as it is now, because the page only fills part of the screen. So, I can move it around as I like. However, on my mobile, the screen fits the page height very well, so Group titles keep leaving the screen when I scroll, which does not look good at all.

I'd like to have the page EITHER scroll OR pan. And not both at the same time.

**Comment by rchl** [comment]
> I'd like to have the page EITHER scroll OR pan. And not both at the same time.

That's how it's supposed to work and how it works for me on Chrome. Are you able to check in Chrome, just to see and report if that's what you expect?

**Comment by akloeckner** [comment]
> Are you able to check in Chrome, just to see and report if that's what you expect?

Yes, I checked in Chrome and that's as expected there! So, it's a Firefox/safari issue.
