### ISSUE TITLE
History Graphs not working in Tileboard but everything else works OK

### ISSUE THREAD

**Issue by DeviousPenguin** [resoai/TileBoard#328]
Hi I thought I may be able to resolve this issue myself but I seems I'm unable to. The issue it that the history graphs simply do not work for me in Tileboard UI. Everything else works great, I can turn switches on/off etc. and sensors update OK. I'd like to fix this and have history graphs on Tileboard if possible.

It seems to be some sort of CORS issue, here is the error I get from Firefox Browser console when I long press a tile to make the history show:

```log
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://secret_ha_url.duckdns.org/api/hist…020-01-06T08:11:20.392Z?filter_entity_id=switch.lmine1_power. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://secret_ha_url.duckdns.org/api/hist…020-01-06T08:11:20.392Z?filter_entity_id=switch.lmine1_power. (Reason: CORS request did not succeed).
```

Now my hardware set up is a little bit odd, I'm running Tileboard on a different machine to HA which is why this may an issue, I'll detail my set up here:

HA machine: Rpi 4 running Raspbian from SSD. Latest HA running under a 'VENV'.
Tileboard machine: Synology DS213 running NGINX under latest Synology OS. This is also adding a NGINX reverse HTTPS proxy for the HA machine, allowing SSL access to HA for Alexa integration.

To access HA directly I use a let's encrypt SSL cert, and duck DNS for forwarding. So if I go to https://secret_ha_url.duckdns.org/ then it goes to my HA install on port 443.

To access Tileboard I use a let's encrypt SSL cert, and again duck DNS for forwarding. So if I go to https://secret_tileboard_url.duckdns.org/ then it goes to my Tileboard page, after being logged in with a HA user.

Here is the config settings in my Tileboard 'config.js' file:

```js
   serverUrl: 'https://secret_ha_url.duckdns.org',
   /* wsUrl: The URL to your HomeAssistant Websocket connection.
    * If HomeAssistant is behind SSL, replace ws:// with wss://
    */
   wsUrl: 'wss://secret_ha_url.duckdns.org/api/websocket',
```

It looks to be a CORS error in my Browser console, and I admit I'm not too familiar with how CORS should be set up. By the looks of it I need to set up some HTTP headers, and I should be able to do this on my Synology NGINX settings, which domain do I need to set the headers in? Should I change the headers for https://secret_tileboard_url.duckdns.org/ or https://secret_ha_url.duckdns.org ? Thanks

**Comment by rchl** [comment]
I think it should work if you configure [cors_allowed_origins](https://www.home-assistant.io/integrations/http#cors_allowed_origins) in Homeassistant. In your case you should probably add the `https://secret_tileboard_url.duckdns.org` origin there.

**Comment by DeviousPenguin** [comment]
Thanks so much, after fiddling around with NGINX conf files for what seemed like forever, I totally missed the CORS settings right there in Home Assistant! 

I added `https://secret_tileboard_url.duckdns.org` to my HA HTTP config, and restarted HA, and now my history graphs are working. Thanks very much!
