### ISSUE TITLE
Is it possible to change the colours of the history chart?

### ISSUE THREAD

**Issue by DeviousPenguin** [resoai/TileBoard#329]
I was wondering if it's possible to change the default colours of the graph elements in the history charts in Tileboard?

I've quite like something other than the default colours, I've looked at the docs:

>  options: { elements: {point: {radius: 3}}}, // Chart options. Refer to https://www.chartjs.org/.

and I've looked at the chartjs docs also, and there doesn't seem to be an easy way to change the elements of the chart, unless I'm missing something.

If someone has changed the colours, are they able to share an example? Thanks

**Comment by akloeckner** [comment]
I believe, colors cannot be changed right now. The underlying library has “beautiful pre-sets colors“ and a separate option `colors` to override them. This option is not currently implemented in TileBoard...

https://jtblin.github.io/angular-chart.js/

**Comment by akloeckner** [comment]
This is where it would have to be added:

https://github.com/resoai/TileBoard/blob/2c9902385164d9d9b80ff5806838e55d9ade2ab2/scripts/controllers/main.js#L1630

https://github.com/resoai/TileBoard/blob/2c9902385164d9d9b80ff5806838e55d9ade2ab2/index.html#L159

**Comment by akloeckner** [comment]
I just saw that you want to change the default colors. That should be possible according to the library link I posted first. Just put this in your `config.js`:

```
Chart.defaults.global.colors = ['#FF0000'];
```

**Comment by DeviousPenguin** [comment]
Thanks, I didn't know the settings could be changed in that way.

I've added a small array of colours now in my config.js so now the graph colours match the colours used in my tileboard:

```js
Chart.defaults.global.colors = [ "#fdcc01", "#60bcbc", "#0c5adf" ];
```
