### ISSUE TITLE
Feature_request: view two or more cameras side by side in cameras tab

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#33]
My wife and i use cameras as baby monitors when our daughter is asleep upstairs. In september we are having another child and wife wants to see side-by-side cameras.

Our previous cameras had this feature in an app but our current Dlink cameras does not.

Can this be done?

**Comment by resoai** [comment]
You can create a separate page put two camera tiles either side by  side or one on top of the other. You can adjust the refresh interval as desired.
