### ISSUE TITLE
Cameras in Tileboard

### ISSUE THREAD

**Issue by Steeleio** [resoai/TileBoard#331]
I have an Wyze Camera that is set up in Hass.io using rtsp. I cannot get the camera to display in Tileboard. I have tried it with this config:
{
   position: [0, 0],
   id: 'camera.front_gate',
   type: TYPES.CAMERA_THUMBNAIL,
   bgSize: 'cover',
   width: 2,
   state: false,
   fullscreen: {
      type: TYPES.CAMERA,
      refresh: 1500, // can be number in milliseconds
      bgSize: 'contain'
   },
   refresh: function () { // can also be a function
      return 3000 + Math.random() * 1000
   }
}
and with this config:
{
   type: TYPES.CAMERA,
   id: {},
   bgSize: 'cover',
   width: 2,
   state: false,
   fullscreen: {},
   refresh: 2000,
   filter: function (item, entity) {
      return "rtsp://username:password@192.168.1.1/live";
   }
}
Thank you for your help!

**Comment by resoai** [comment]
RTSP will obviously not work. Make sure that `camera.front_gate` is actually a correct  entity id and that camera is being displayed properly in HA.

**Comment by Steeleio** [comment]
Yes, I changed it to the actual entity id from HA but it does not show in Tileboard.

**Comment by resoai** [comment]
What does the error say?

**Comment by Steeleio** [comment]
It doesn't give an error. The tile is created it's just empty.

**Comment by resoai** [comment]
Developer console?

**Comment by Steeleio** [comment]
I'll check that as soon as I get home from work.

**Comment by Steeleio** [comment]
This is the error:
GET https://steeleio.duckdns.org:8123/api/camera_proxy/camera.garage_camera?token=af4bdde64ebe812e12bc93ce9050b25c7aa324c7ce9336f6c218edf50d34711f&_i=7 500 (Internal Server Error)

**Comment by resoai** [comment]
First of all it is never a good idea to expose your real domain in the interest of security. HTTP 500 is an internal server error which is weird. Are you using Nginx as proxy?

**Comment by Steeleio** [comment]
I know better than that. I was just in a hurry. It is setup through DuckDNS. I did not set up another proxy.

**Comment by resoai** [comment]
Does it work localy i.e. without Duck?

**Comment by Steeleio** [comment]
I haven't tried. I don't have a problem with it in HA.

**Comment by resoai** [comment]
You do understand that `/api/camera_proxy/...` is being served by HA and has nothing to do with TileBoard, right?

**Comment by Steeleio** [comment]
Yes. I am just trying to figure out how to get it to show in TileBoard.

**Comment by resoai** [comment]
Try opening that link (to the camera still) directly in browser.

**Comment by Steeleio** [comment]
The one from HA (local:8123/...) or the rtsp address?

**Comment by resoai** [comment]
The one from HA, RTSP stream can not be played directly in browsers.

**Comment by Steeleio** [comment]
I get the 500 error. There is an error in HA "error getting new camera image:null" but it's only there once and the camera is showing in the frontend.

**Comment by resoai** [comment]
That makes sence, since you only request image from the UI.

**Comment by resoai** [comment]
Hold on, Wyze Cameras are only serving RTSP and not a still image. I presume in your config `still_image_url` is blank, rght? 

Try changing tile type from `CAMERA` to `CAMERA_STREAM` in TileBoard config. This is untested but could work.

**Comment by Steeleio** [comment]
That did it! Thank you so much for your help!

**Comment by resoai** [comment]
You are welcome. In order to avoid errors in the log, set `still_image_url` to a static image in `www` directory.

**Comment by Steeleio** [comment]
Will do. Thanks again.
