### ISSUE TITLE
Problem with "popup/history" window

### ISSUE THREAD

**Issue by mortydk** [resoai/TileBoard#332]
Hi,

Whenever i press/longpress a tile (TYPES.LIGHT works fine), i dont get a popup with the info - which as far as i know, is the idea for weather, sensor, alarm etc..
Instead it shows in the top section of index.html

![image](https://user-images.githubusercontent.com/5820987/72685288-f8402b00-3ae8-11ea-8c06-a2ea3b67d4dc.png)

For me this happens for weather, sensor and alarm and has been like this since i started using Tileboard.
Do you know what can cause this problem? The only console error i get is this:

![image](https://user-images.githubusercontent.com/5820987/72685344-92a06e80-3ae9-11ea-9025-e2d145a29bc9.png)

Hope you can lead me in the right direction :)
Let me know if you need some information

Thanks
Morten

**Comment by rchl** [comment]
Your main.css is probably outdated or customized. It should match https://github.com/resoai/TileBoard/blob/master/styles/main.css exactly if you have pulled latest version.

**Comment by mortydk** [comment]
Thanks for you response rchl :)

I will try to update the css. I have customized it, but mainly colors though. Am i right to assume that the tiles css, has nothing to do with how history-popup is working? So i can focus on that.

**Comment by rchl** [comment]
To avoid such problems in the feature, you should customize things in custom.css file. The one that you are getting loading error for in the console (btw. That error is expected if not having any customizations).

**Comment by mortydk** [comment]
I see! So whatever is in custom.css, will overwrite the styles in main.css?

**Comment by rchl** [comment]
That file is loaded after main.css, so per CSS behavior, rules there will overwrite original ones if they have same specificity.

**Comment by mortydk** [comment]
Makes sense.. Thanks mate
