### ISSUE TITLE
POPUP_IFRAME - no way to close window with iframe content

### ISSUE THREAD

**Issue by ciechompl** [resoai/TileBoard#335]
when content from POPUP_IFRAME goes full window (e.g. youtube movie) nice "X" from left top corner disappearing, so there is no way to close such window and the only what we can do is to reload the page. 
Would be great to force this "X" to be permanent or any click outside of the iframe window could close it.

**Comment by rchl** [comment]
I'm not sure I understand how you could not un-fullscreen a movie so that the toolbar appears.

Or maybe I don't see the problem because it was already fixed?
