### ISSUE TITLE
[Feature Request] Multiple devices/zones in device tracker tile

### ISSUE THREAD

**Issue by darrenpeters** [resoai/TileBoard#337]
Hi,

Is it possible to add multiple device trackers in a single tile?  This is currently possible with the Lovelace map card.  I tried changing "id: 'device_tracker.blah'" to taking an array instead of a string, but that didn't seem to do the trick.

**Comment by resoai** [comment]
Device tracker is only meant for a single device/person.

**Comment by darrenpeters** [comment]
Is it possible to do with a custom tile?  Or would I have to roll my own TYPE?

**Comment by resoai** [comment]
CUSTOM tile allows you to define HTML within it but it would be easier to make one based on the existing device_tracker one.
