### ISSUE TITLE
Feature Request: RGB Slider or Wheel for lights

### ISSUE THREAD

**Issue by sonata7245** [resoai/TileBoard#34]
Hi Im not sure if this is possible already or not but having a slider or wheel to set the color of lights is about the only thing I am missing on this dashboard. Thanks for all the work you have put into this!

**Comment by nayaj** [comment]
Here is the state of an Ikea tradfri lamp with a color set

{
  "min_mireds": 250,
  "max_mireds": 454,
  "brightness": 254,
  "hs_color": [
    240,
    100
  ],
  "rgb_color": [
    0,
    0,
    255
  ],
  "xy_color": [
    0.136,
    0.04
  ],
  "friendly_name": "Vardagsrum",
  "supported_features": 51,
  "icon": "mdi:lamp"
}

**Comment by resoai** [comment]
Unfortunately this is not something which can be implemented at the moment
