### ISSUE TITLE
Title Bar on Popup type windows (camera, door, iframe, etc) Cutting off Images and Pages

### ISSUE THREAD

**Issue by KHouse75** [resoai/TileBoard#342]
I recently updated to the latest version of TileBoard and I noticed that the popup style windows now have a title bar instead of just the X overlay in the upper right.

This is causing cameras, images and url content to be shifted down and the bottom cut off.

I've done some digging around and haven't yet come up with an easy solution.  How can I go about getting the photo fully contained in the windows like previously instead of cut off at the bottom?

Here's an example of how the older version worked.  The entire photo is visible:
![NoTitle](https://user-images.githubusercontent.com/24616556/75202678-0281c480-573a-11ea-9634-3d0ecc9a6461.jpeg)

Here's an example of the new version with the title bar.  The bottom of the photo is cut off:
![Title](https://user-images.githubusercontent.com/24616556/75202686-09103c00-573a-11ea-8739-b8e6f927369f.jpeg)

**Comment by KHouse75** [comment]
What I came up with to workaround this was to add a custom css entry to set the title bar to 0px then copied the *-popup--close items from the old main.css to the new custom.css as *-popup-close to globally override what was in the main.css.  If there's a better way, please let me know.

**Comment by resoai** [comment]
You can control how image in camera is being sized using bgSize parameter.

**Comment by KHouse75** [comment]
I'm using bgSize: 'contain' which should always resize the image to make sure the entire thing is visible but with the title bar, the image gets pushed down 50px so the bottom is cut off by the popup element.

I tracked it down to the following height css properties, added them to custom.css and changed them from 100% to 100% - 50px.  Works perfectly now.  You lose a a bit of size with the title bar but the entire images are now visible.

```
.camera-popup--camera,
.door-entry-popup--camera,
.iframe-popup--camera {
  height: calc(100% - 50px);
}

.camera-popup--iframe,
.door-entry-popup--iframe,
.iframe-popup--iframe {
  height: calc(100% - 50px);
}
```
