### ISSUE TITLE
Entity font and title sizing

### ISSUE THREAD

**Issue by oneseventhree** [resoai/TileBoard#347]
When I change font-size to 100px it cuts out the top and bottom of the icon:

.item-entity--icon {
  font-size: 80px;
  line-height: 80px;

Any idea of how I can make the icons bigger without the cut offs?

Also is there a way to make make the media player buttons bigger and have the volume buttons even bigger than the other buttons on the tile?

thanks in advance

**Comment by rchl** [comment]
Make the tile bigger or icon smaller. If you are doing such drastic font-size changes you'll have to tweak various other things too.
