### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by stefan-STMODE** [resoai/TileBoard#348]
i'm new to all this but found something during the install
i made a dir www in the homeassistant folder
/usr/share/hassio/homeassistant/www
then i used    git clone https://github.com/resoai/TileBoard.git
restarted homeassistant en have to go to this link to open the tilebaord:
https://(my.website):8123/local/TileBoard/index.html
capital T and B

**Comment by resoai** [comment]
So, what exactly is your question?

**Comment by stefan-STMODE** [comment]
it was more a finding about the link,

on github under  how to use the link is was with lowercase letters

TileBoard will be available at http://HASS_IP:8123/local/**t**ile**b**oard/index.html and will prompt you for your login credentials after restarting Home Assistant

but if u use clone the folder is downloaded as **T**ile**B**oard

for the rest thanks for the work u did, i loaded the default example config and it looks great
will try to customize it later
