### ISSUE TITLE
`dateFormat` does not change header date.

### ISSUE THREAD

**Issue by erichiller** [resoai/TileBoard#349]
Underneath `header.left` I have:

```json

         {
            type: HEADER_ITEMS.DATE,
            dateFormat: 'EEEE, MMM dd',
            styles: {
              fontSize: '48px',
            }
         }
```

But the `dateFormat` never changes. No matter what I set `dateFormat` to, I still get the default `dateFormat: 'EEEE, LLLL dd'`
![image](https://user-images.githubusercontent.com/5379325/76529739-537f0180-6438-11ea-939a-20b8d06e5bf1.png)

**Comment by erichiller** [comment]
I found how to make it work. Even though `dateFormat` is what's mentioned in the example config, after looking through the source, it is actually looking at the `format` field. Maybe the sample config and docs should be updated?

fix being:

``` js
        {
            type: HEADER_ITEMS.DATE,
            format: 'EEEE, MMM dd',
            styles: {
              fontSize: '48px',
            }
         }
```

**Comment by rchl** [comment]
It will now use dateFormat and fall back to format.
