### ISSUE TITLE
Feature Request: input_datetime

### ISSUE THREAD

**Issue by oakbrad** [resoai/TileBoard#35]
Being able to enter date and/or time for input_datetime would be great for creating an alarm clock.

**Comment by nayaj** [comment]
Offtopic but to see @oakbrad in here is amazing, inspired me so much for my HA setup ❤️

**Comment by resoai** [comment]
We need the think of a way to visually represent it.

**Comment by Evgeny-** [comment]
We've implemented basic support, please check this out

**Comment by resoai** [comment]
![screenshot_2018-07-11 tileboard 1](https://user-images.githubusercontent.com/11579512/42584820-f7edf6ba-852b-11e8-8305-12d1788a5b25.png)
![screenshot_2018-07-11 tileboard](https://user-images.githubusercontent.com/11579512/42584821-f807d4d6-852b-11e8-8d18-086c61e67755.png)
