### ISSUE TITLE
DarkSky not working

### ISSUE THREAD

**Issue by oneseventhree** [resoai/TileBoard#350]
DarkSky has stopped working for me. I get this:
[https://ibb.co/mqXQhg5](url)

DarkSky works on HA but for some reason not with Tileboard. I also had it working on my tablet for days after it stopped working on my laptop but as soon as I edited the code it stopped working on my tablet too.

``
var CONFIG = {
   customTheme: CUSTOM_THEMES.TRANSPARENT, // null, CUSTOM_THEMES.MATERIAL, CUSTOM_THEMES.MOBILE, CUSTOM_THEMES.COMPACT, CUSTOM_THEMES.HOMEKIT, CUSTOM_THEMES.WINPHONE, CUSTOM_THEMES.WIN95
   transition: TRANSITIONS.ANIMATED_GPU, //ANIMATED or SIMPLE (better perfomance)
   entitySize: ENTITY_SIZES.NORMAL, //SMALL, BIG are available
   tileSize: 150,
   tileMargin: 6,
   serverUrl: 'http://' + location.hostname + ':8123',
   wsUrl: 'ws://' + location.hostname + ':8123/api/websocket',
   authToken: null, // optional long-lived token (CAUTION: only if TileBoard is not exposed to the internet)
   //googleApiKey: "XXXXXXXXXX", // Required if you are using Google Maps for device tracker
   //mapboxToken: "XXXXXXXXXX", // Required if you are using Mapbox for device tracker
   debug: false, // Prints entities and state change info to the console.
   pingConnection: true, //ping connection to prevent silent disconnections

   // next fields are optional
   events: [],
   timeFormat: 24,
   menuPosition: MENU_POSITIONS.LEFT, // or BOTTOM
   hideScrollbar: false, // horizontal scrollbar
   groupsAlign: GROUP_ALIGNS.HORIZONTALLY, // or VERTICALLY
   onReady: function () {},

   header: { // https://github.com/resoai/TileBoard/wiki/Header-configuration
      styles: {
         padding: '35px 15px 0',
         fontSize: '28px'
      },
      right: [],
      left: [
         {
            type: HEADER_ITEMS.DATETIME,
            dateFormat: 'EEEE, LLLL dd', //https://docs.angularjs.org/api/ng/filter/date
         }
      ]
   },

   /*screensaver: {// optional. https://github.com/resoai/TileBoard/wiki/Screensaver-configuration
      timeout: 300, // after 5 mins of inactive
      slidesTimeout: 10, // 10s for one slide
      styles: { fontSize: '40px' },
      leftBottom: [{ type: SCREENSAVER_ITEMS.DATETIME }], // put datetime to the left-bottom of screensaver
      slides: [
         { bg: 'images/bg1.jpeg' },
         {
            bg: 'images/bg2.png',
            rightTop: [ // put text to the 2nd slide
               {
                  type: SCREENSAVER_ITEMS.CUSTOM_HTML,
                  html: 'Welcome to the <b>TileBoard</b>',
                  styles: { fontSize: '40px' }
               }
            ]
         },
         { bg: 'images/bg3.jpg' }
      ]
   },*/

   pages: [
      {
         title: 'Main page',
         bg: 'images/bg3.jpg',
         icon: 'mdi-home-outline', // home icon
         groups: [
            {
               title: '',
               width: 2,
               height: 3,
               items: [
                  {
                     position: [0.27, 0.04],
                     width: 2,
                     height: 2,
                     title: 'Lights',
                     subtitle: '',
                     id: 'light.kitchen_room',
                     type: TYPES.LIGHT,
                     states: {
                        on: "On",
                        off: "Off"
                     },
                     icons: {
                        on: "mdi-lightbulb-on",
                        off: "mdi-lightbulb",
                  }
                  },
                  {
                     position: [2.27, 0.04],
                     width: 2,
                     height: 2,
                     type: TYPES.SWITCH,
                     id: 'switch.kitchen_leds',
                     title: 'LEDs',
                     subtitle: '',
                     states: {
                        on: "On",
                        off: "Off"
                     },
                     icons: {
                        on: "mdi-led-strip-variant",
                        off: "mdi-led-strip-variant",
                  }
                  },
                  {
                     position: [4.27, 0.04],
                     width: 2,
                     height: 2,
                     type: TYPES.SWITCH,
                     id: 'switch.kitchen_rangehood',
                     title: 'Rangehood',
                     subtitle: '',
                     states: {
                        on: "On",
                        off: "Off"
                     },
                     icons: {
                        on: "mdi-fan",
                        off: "mdi-fan-off",
                        icon_style_active: "color: white; font-size: 800%; margin-top: 25px",
                  }
                  },
                  {
                     position: [2.27, 2.11],
                     width: 2,
                     height: 1.8,
                     //classes: ['-compact'], // enable this if you want a little square tile (1x1)
                     type: TYPES.WEATHER,
                     id: 'weather.dark_sky',
                     title: '',
                     state: '&sensor.dark_sky_summary.state', // TOP RIGHT label with weather summary (e.g. Sunny)
                     icon: '&sensor.dark_sky_icon.state',
                     //iconImage: '&sensor.dark_sky_icon.state', // use this one if you want to replace icon with image
                     icons: { //Big Icon
                        'clear-day': 'clear',
                        'clear-night': 'nt-clear',
                        'cloudy': 'cloudy',
                        'rain': 'rain',
                        'sleet': 'sleet',
                        'snow': 'snow',
                        'wind': 'hazy',
                        'fog': 'fog',
                        'partly-cloudy-day': 'partlycloudy',
                        'partly-cloudy-night': 'nt-partlycloudy'
                     },
                     fields: { // most of that fields are optional
                        temperature: '&sensor.dark_sky_temperature.state', // BIG TEMP
                        temperatureUnit: '&sensor.dark_sky_temperature.attributes.unit_of_measurement', //CELCIUS
                        windSpeed: '&sensor.dark_sky_wind_speed.state',
                        windSpeedUnit: '&sensor.dark_sky_wind_speed.attributes.unit_of_measurement',
                        humidity: '&sensor.dark_sky_humidity.state',
                        humidityUnit: '&sensor.dark_sky_humidity.attributes.unit_of_measurement',
                  
                        list: [
                           // custom line
                           'Feels like: '
                              + '&sensor.dark_sky_apparent_temperature.state'
                              + '&sensor.dark_sky_apparent_temperature.attributes.unit_of_measurement',
                  
                           // another custom line
                           'Pressure: '
                              + '&sensor.dark_sky_pressure.state'
                              + '&sensor.dark_sky_pressure.attributes.unit_of_measurement',
                  
                           // yet another custom line
                           '&sensor.dark_sky_precip_probability.state'
                              + '&sensor.dark_sky_precip_probability.attributes.unit_of_measurement'
                              + ' chance of rain'
                        ]
                  }
                  },                
                  {
                     position: [5.32, -1.02],
                     width: 2,
                     height: 1,
                     title: '      Living Room TV',
                     id: 'media_player.living_room_tv_kd_75x8500e',
                     type: TYPES.MEDIA_PLAYER,
                     hideSource: true,
                     hideMuteButton: false,
                     state: false,
                    //state: '@attributes.media_title',
                     subtitle: '@attributes.media_title',
                     bgSuffix: '@attributes.entity_picture',
                     hidden: function (item, entity) { return entity.state == 'off' }
                  }
               ]
            },
         ]
      }
   ],
}
``

**Comment by robbz23** [comment]
I think this is an issue with the Dark Sky component in HA.  I can't see that it is creating a bunch of sensors anymore that Tileboard can access.  I was able to fix most of it using this setup.

 {
                     position: [0, 0],
                     height: 2,
                     width: 1,
                     type: TYPES.WEATHER,
                     id: 'weather.dark_sky',
                     
                     
                     icons: { //Big Icon
                        'clear-day': 'clear',
                        'clear-night': 'nt-clear',
                        'cloudy': 'cloudy',
                        'rain': 'rain',
                        'sleet': 'sleet',
                        'snow': 'snow',
                        'wind': 'hazy',
                        'fog': 'fog',
                        'partly-cloudy-day': 'partlycloudy',
                        'partly-cloudy-night': 'nt-partlycloudy'
                     },
                     fields: { // most of that fields are optional
                        temperature: '@attributes.temperature', // BIG TEMP
                        temperatureUnit: 'C', //CELCIUS
                        pressure: '@attributes.pressure',
                        pressureUnit: 'hPa',
                        windSpeed: '@attributes.temperature',
                        windSpeedUnit: 'm/s',
                        humidity: '@attributes.humidity',
                        humidityUnit: '%'
                     }
                  },

**Comment by resoai** [comment]
You have to create DarkSky sensor, not weather.
