### ISSUE TITLE
Weather list example typo

### ISSUE THREAD

**Issue by IllMakeTheBeer** [resoai/TileBoard#352]
Very minor but this threw me for a little while before I was able to spot the issue

I used the weather list example tile to while getting started with TileBoard.  My icons were not showing and assuming I did something dumb, went looking. After some time (and understanding what was going on in the example code) I realized the issue with the example code:

icon: "&sensor.dark_sky_icon_" + id + ".state",

Should be:
icon: "&sensor.dark_sky_icon_" + id + "**d**.state",

This brings it in line with all the other sensor references in the sample code and the icons appear perfectly.

**Comment by rchl** [comment]
The example was updated in https://github.com/resoai/TileBoard/pull/676 to use OpenWeatherMap so this is no longer relevant.
