### ISSUE TITLE
Variable in Tile's Title Field 

### ISSUE THREAD

**Issue by ned-kelly** [resoai/TileBoard#353]
Hi Guys,

As the title suggest - I want to ideally run a function, in the title field so I can 'dynamically' change/set the title of the tile, based on another sensor value in HA (Much like how the `value: function() {}` works...

Does anyone have any suggestions?

So far I've tried setting a global variable, and then variable when the value is set - however this doesn't seem to work...

![image](https://user-images.githubusercontent.com/17648709/77615643-946c2f80-6f7b-11ea-8f84-cfdbb8def3ac.png)

![image](https://user-images.githubusercontent.com/17648709/77615728-c4b3ce00-6f7b-11ea-875b-3373824bde59.png)

Cheers,

**Comment by resoai** [comment]
Both variable and anonymous function work just fine for title and state.

**Comment by ned-kelly** [comment]
Looks like I was just being a noob - HA returns the integer value as a string - not actually an integer...

Thanks for clarifying though!

Cheers,
