### ISSUE TITLE
How to set the state of a switch via an action function.

### ISSUE THREAD

**Issue by ned-kelly** [resoai/TileBoard#354]
Hi Guys,
Another quick q that I couldn't find in the docs...

Does anyone know how to set a state (ie a switch to on) from a custom action?

Basically I'm trying to turn the device on/off from a action - and also perform other tasks (such as disable the button in the UI for a few seconds).

![image](https://user-images.githubusercontent.com/17648709/77642523-83d2ae00-6fa9-11ea-8968-9c48f52bb2d6.png)

**Example is not working** The state is changing in Angular, but no commands are actually being sent to HA via the WS connection (so the device does not actually turn on|off).

Here's a quick snip to help paint a better picture of what I'm trying to achieve.

Cheers,

**Comment by resoai** [comment]
```
 action: function(item, entity) {
         this.apiRequest({
           type: "call_service",
           domain: "...",
           service: "...",
           service_data: {
             entity_id: item.id,
             ...
           }
         });
      }

```

**Comment by ned-kelly** [comment]
Perfect, thanks for clarifying!
