### ISSUE TITLE
Icon not showing correctly for covers

### ISSUE THREAD

**Issue by ZARichardWright** [resoai/TileBoard#355]
I have a Cover in home assistant when i try display this on a tile, every thing works except the icons.
I have tried changing to a TYPES.LOCK no luck, i have also tried extracting the icon: using a function and &template neither seem to work even thou if i set the title to the same value i get valid icons strings.

{
                            position: [1, 3],
                            type: TYPES.SWITCH,
                            id: 'cover.richard_garage_door',
                            states: {
                                on: "closed",
                                off: "open"
                            },
                            icons: {
                                on: "mdi-lightbulb-on",
                                off: "mdi-lightbulb",
                            }
                        },

**Comment by resoai** [comment]
Ae you sure states are `on` and `off` for this entity?

**Comment by rchl** [comment]
Closing due to no response.
