### ISSUE TITLE
Page in pages?

### ISSUE THREAD

**Issue by ned-kelly** [resoai/TileBoard#356]
Would it be possible to create a 'page in page'? 

The goal here is to make a sub-page that opens when you click & hold a button where i can add more tiles and actions related directly to the parent (in my case I'm planning on making a TV Remote Control as a sub-page item).

Thanks,

**Comment by resoai** [comment]
No, but you can play with pop-up IFRAME.

**Comment by ned-kelly** [comment]
> No, but you can play with pop-up IFRAME.

This is what I'm currently doing, and integrating my HA Remote - It's not the most elegant solution so was wondering if there was a better alternative. 

Thanks,
