### ISSUE TITLE
Input number slider only working when bottom is set to true

### ISSUE THREAD

**Issue by atomic10** [resoai/TileBoard#357]
I added a slider to my config and noticed that the slider will not move - with a mouse on my PC or a tablet/phone touchscreen. The icon doesn't even change from arrow to pointed finger on my PC when I hover over the slider box.

![Tileboard slider 1](https://user-images.githubusercontent.com/16368168/77888992-d9b09a00-72b8-11ea-857c-c1f91b2a80d3.PNG)

If I add the bottom: true field, it works as intended.

![Tileboard slider 2](https://user-images.githubusercontent.com/16368168/77889063-f947c280-72b8-11ea-84cc-7ed71277c782.png)

The input number works correctly in home assistant. Just can't seem to get it working in Tileboard.

**Comment by KenBrockman33** [comment]
I have also been experiencing a similar problem and it appears to be linked to the default tilesize. If I set tilesize in the main config.js to 150 sliders work fine, if you change the tile size, i.e. to 100, sliders stop working. Hopefully this is a simple fix, but as a work around you can change the default tilesize to 150 and resize all of your tiles.

**Comment by atomic10** [comment]
Thanks for that Ken. Had me scratching my head for a while but that makes sense.
Appreciate you letting me know.
