### ISSUE TITLE
Using with Synology hass.io 

### ISSUE THREAD

**Issue by sinegovsky-ivan** [resoai/TileBoard#358]
Hi!
I'm trying to install this addon for home assistant at Synology NAS.

As i see at instruction:
`Create a directory called tileboard inside www directory in HA's config path and move all of the files there.
`
but i don't have the www folder.  I have only these folders:
[ivan@homeserver:/volume1/docker/hass.io/homeassistant$ ls
automations.yaml  configuration.yaml  deps  groups.yaml  home-assistant.log  home-assistant_v2.db  scenes.yaml  scripts.yaml  secrets.yaml  tts]

I created folder manually, restarted HA, but without success:

http://192.168.31.250:8123/local/tileboard/index.html - 404

How to install this addon to hass.io?

**Comment by tyler-danielson** [comment]
Simply create a new folder "www".  The web server is built in, and HA will see it once the folder is created.

**Comment by sinegovsky-ivan** [comment]
I'm tried to create www folder inside docker/hass.io/homeassistant

but i got 404 error at http://192.168.31.250:8123/local/tileboard/index.html

**Comment by tyler-danielson** [comment]
Oh sorry, you also have to restart HA.

**Comment by sinegovsky-ivan** [comment]
did it. no luck :(

**Comment by sinegovsky-ivan** [comment]
oh sorry, my bad.
i must enter local/TileBoard/index.html instead of local/tileboard/index.html.

All fine now. Thank you!

**Comment by tyler-danielson** [comment]
Great!
