### ISSUE TITLE
Camera authentication errors

### ISSUE THREAD

**Issue by bram2202** [resoai/TileBoard#359]
I'm using TileBoard on a tablet mounted on the wall to control my home.
In TileBoard I’ve setup a camera that shows the front door, but the camera only shows intermittent picture, with empty pictures in between.

In home-assistant i get the error: `Login attempt or request with invalid authentication from [IP of tablet] `
The config of TileBoard has a `authToken`, and everything else works as intended. 

~~So I tried the `trusted_networks` in Hass, and added the tablet as a `trusted_users`, 
the errors stopped and the camera image is stable!
But that’s not the solution, i don't wat to use `trusted_networks`, this disabled used authentication.~~
Edit: trusted_networks did not stop the the Login attempt errors

Switched from TYPES  `CAMERA_THUMBNAIL` to `CAMERA` because is THUMBNAIL deprecated in Hass.
I tried `CAMERA_STREAM` but its to much for the tablet.

Hass: `0.107.7`
Tileboard: `latest master`

Config:
```
                  {
                     position: [0, 0],
                     id: 'camera.frontyard',
                     type: TYPES.CAMERA,
                     refresh: 500,   
                     bgSize: 'contain',
                     width: 3,
                     height: 2,
                     state: false,            
                     fullscreen: {
                        type: TYPES.CAMERA,
                        refresh: 500,
                        bgSize: 'contain'
                     },
                     refresh: function () {
                        return 300
                     }  
                  },
```

**Comment by matt5mith** [comment]
I get exactly the same problem, also running 0.107.7. However, the local IP of my router gets blocked instead, presumably because I’m using a domain name to access HA, so it gets rerouted via the router. That then means I can’t access HA locally from any client until I unblock the IP. For now I’ve had to stop using Tileboard, unfortunately.

**Comment by gezquerra** [comment]
The same error here with version 0.107.7. Once Tileboard is loaded after a few minutes it starts reporting error 401 for all cameras (TYPE.CAMERA). I have tried trusted network authentication and long live token with the same result.

**Comment by radinsky** [comment]
Same for me. It was caused by one of the cameras that uses static images as a source (local file)

**Comment by tjedrak** [comment]
Same for me. Had to switch to `CAMERA_THUMBNAIL`.

**Comment by matt5mith** [comment]
> 
> 
> Same for me. Had to switch to `CAMERA_THUMBNAIL`.

You'll probably see lots of deprecation warnings in your HA log now, and it will on doubt stop working at some point in the future.  You can of course hide the notices until such time:

```
logger:
  logs:
    homeassistant.components.camera: error
```

**Comment by Xitro01** [comment]
Same issue here, hope this gets resolved asap!

**Comment by resoai** [comment]
Check if `access_token` for the image is changing by comparing the URL of the image being requested with the entity state in HA.

**Comment by resoai** [comment]
This should now be fixed, please grab the latest code.
