### ISSUE TITLE
Feature_request: Define Unit_of_Measurement for sensor

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#36]
Trying to implement my SNMP bandwith montoring sensors but cant figure out how to customize my code to get it to work. Would be nice to be able to define this for sensors

https://www.home-assistant.io/components/sensor.snmp/

```
{
   position: [7, 2],
   width: 2,
   height: 1,
   title: '',
   id: {}, // since we are binding each list item to different sensor, so we simply use an empty object
   type: TYPES.TEXT_LIST,
   state: false,
   list: [
      {
         title: 'Internet Speed IN',
         icon: 'mdi-speedometer',
         value: '&sensor.internet_speed_in.state'
      },
	  {
         title: 'Internet Speed OUT',
         icon: 'mdi-speedometer',
         value: '&sensor.internet_speed_out.state'
      },
	  {
         title: 'WAN Download Average',
		 icon: 'mdi-download',
         value: '&sensor.wan_traffic_in_mean.attributes.unit_of_measurement',
	  },
	  {
         title: 'WAN Upload Average',
         icon: 'mdi-upload',
         value: '&sensor.wan_traffic_out_mean.state'
      },
      ]
},
```
![console](https://user-images.githubusercontent.com/40382766/41808909-551c06e2-76e5-11e8-8077-13d8f1c6b7df.JPG)
![unit_of_measurements](https://user-images.githubusercontent.com/40382766/41808911-5af85944-76e5-11e8-8e3e-27a701d73337.JPG)
![unit_of_measurements_ha](https://user-images.githubusercontent.com/40382766/41808914-5f9947b0-76e5-11e8-8a0d-a0046fa359d7.JPG)

**Comment by resoai** [comment]
This is already implemented. You can define it with the `unit` field.

**Comment by nayaj** [comment]
Could you give me an example how to input it in my config example

**Comment by resoai** [comment]
There you go:
```
      {
         title: 'Internet Speed IN',
         icon: 'mdi-speedometer',
         value: '&sensor.internet_speed_in.state',
         unit: 'Mbps',
      },
```

You can also reference state or attributes of the sensor i.e. `'&sensor.internet_speed_in.attributes_unit_of_measurement'` but in this case it will always be Mbps so why bother :)

**Comment by nayaj** [comment]
Thank you. Works fine.
