### ISSUE TITLE
[Request] Floor Plan Integration into TileBoard

### ISSUE THREAD

**Issue by CarpeDiemRo** [resoai/TileBoard#368]
@resoai 
There is any possibility to integrate the floor plan that is developed in Lovelace into TileBoard?
![Screenshot 2020-05-08 at 11 34 18](https://user-images.githubusercontent.com/38489167/81387896-1ecdb480-9120-11ea-8248-ef7010959842.png)

**Comment by tyler-danielson** [comment]
I just layered images and buttons.  They recently added photo tiles that work well.

**Comment by CarpeDiemRo** [comment]
Thanks for your answer. 
My use case is this. I already have the ploor plan written in lovelace. You say that I can port the already build code into TileBoard?

**Comment by tyler-danielson** [comment]
Oh, I see what you are saying.  I think the only way to do this would be to create a tab within lovelace that is in panel mode and then use that link as an Iframe within tileboard.  Not clean, but I can't think of another method at the moment.  My suggestion was to rebuild it in tileboard with individual buttons and images, which is what I did.

**Comment by CarpeDiemRo** [comment]
I tried with iframe but looks really bad. I really don't want to write again the code into TileBoard. 
![Screenshot 2020-05-10 at 13 28 45](https://user-images.githubusercontent.com/38489167/81496712-4f4d5400-92c2-11ea-8fa9-819464e9141c.png)

**Comment by resoai** [comment]
You can try Kiosk mode. 

https://www.home-assistant.io/blog/2017/07/15/release-49/#kiosk-mode

**Comment by FaiekA** [comment]
@tyler-danielson -  Hi Come across this tread apologies -i see it been closed - Hoping for some assistance - been busy with it for about two weeks and learnt a lot just reading the forum still a newbie. My tileboard’s looking great need some help with my floor plan got images layered - now how would i toggle a switch to call up a image
![Home](https://user-images.githubusercontent.com/52759676/87249828-b70a5180-c461-11ea-8dae-5775c3680939.PNG)
@tyler-danielson - i see you've done this -sample code would be great.  
I have layered the lights-on over my image in the Tv Room need to toggle it now.
I would really appreciate any assistants sample codes would be great
Thanks in advance
