### ISSUE TITLE
Camera Tile assumes Dashboard runs on same webserver as API

### ISSUE THREAD

**Issue by jamesmillard** [resoai/TileBoard#37]
Camera Proxy URLs are relative and therefore 404 when the dashboard is running on a different host.

As the config includes serverUrl - this could be prepended.

**Comment by resoai** [comment]
In most cases you can simply specify `CAMERA_THUMBNAIL` as a tile type which would work just fine grabbing exactly the same image via API. Since `camera_proxy` might want a password it has been decided to leave this task for a user to decide. Most of the tiles have a filter field:

```
           type: TYPES.CAMERA,
            id: 'camera.front_gate',
            refresh: 1500,
            bgSize: 'cover',
            filter: function (item, entity) {
                  return CONFIG.serverUrl 
                    + entity.attributes.entity_picture 
                    + (CONFIG.password ? '&api_password=' + encodeURIComponent(CONFIG.password) : '');
            }, 
```
