### ISSUE TITLE
invoking startScreensaver() and stopScreensaver() command on TILEBOARD?

### ISSUE THREAD

**Issue by kpiersci** [resoai/TileBoard#370]
I'm trying to figure out how to use the stopScreensaver command. I have HASSIO/Tileboard running on a Raspberry and a button on my touch-UI that opens up a full-screen camera stream when pressed (see below). This works fine. But when pressing the button, I'd like to stop the default Tileboard screensaver so that the camera video remains on the screen until I close the pop-up. When the full-screen pop-up closes, I'd like to automatically re- startScreensaver(). 

Is this scenario supported? Failing this, can I have a button with a dedicated action of toggling screensaver on and off?

If so, can someone share a complete code snipit please?
```
{
 position: [0, 0],
 id: 'camera.camera4',
 type: TYPES.CAMERA_THUMBNAIL,
 bgSize: 'cover',
 title: 'Camera 4',
 width: 2,
 state: false,
 fullscreen: {
   type: TYPES.CAMERA_STREAM,
   objFit: 'contain',
   bufferLength: 5
                   },
 refresh: function () { // can also be a function
    return 3000 + Math.random() * 1000
}
```

**Comment by resoai** [comment]
That is easily achievable by changing line 74 of `screensaver.js` to include the check for open camera:

```
if(newState !== $scope.isShown && !$scope.activeCamera) {
```

We do need to decide if we want to make it a default functionality or to introduce some sort of attribute to check against. @rchl what is your opinion? To me it does look logical not to start screensaver if camera popup is open.

**Comment by rchl** [comment]
I agree. When watching a stream you want to disable screensaver (same as when watching youtube in a browser for example).

**Comment by resoai** [comment]
Agreed! I've pushed an update, so @kpiersci you can grab the latest code and enjoy!
