### ISSUE TITLE
gauge no content

### ISSUE THREAD

**Issue by shiftux** [resoai/TileBoard#371]
hello
i'm struggling getting a gauge to work.
basically I copy-paste the example code for a `TYPES.GAUGE` tile from the wiki and all I change is the ID of the sensor. this produces an empty tile for me. Using the same sensor in a `TYPES.SENSOR` tile works fine and the value is displayed...
could it be that the this block is out of date in the wiki?
```
                     value: function (item, entity) {
                        return entity.state;
                     },
```
or how could I debug this?
thanks for the help

**Comment by rchl** [comment]
That `value` function is the default so setting it to the same value changes nothing.

By saying you get empty tile, do you get the `title` at least if it's set in your configuration?

Also, what kind of sensor it is. You might need a custom `value` function if it's some non-number sensor.

**Comment by shiftux** [comment]
@rchl, thanks for the reply
yes, i do get a tile, it's gray and has no content (except for the state, that is shown in the little frame at the top right).
the sensor is provided from this integration [here](https://www.home-assistant.io/integrations/swiss_hydrological_data/). and as mentioned, as sensor-tile it works fine. 
how would i find out what i have to define as value function?

**Comment by rchl** [comment]
Might be able to help if you make a screenshot of the `state` for that sensor from HA's `States` view.

**Comment by shiftux** [comment]
the interesting value is given under `state`. from looking at it I would presume that the default value function would do what it should...
![HA_state_view](https://user-images.githubusercontent.com/6205026/82294124-ef376b80-99ad-11ea-9707-fa3f9cbf25e4.png)
![tileboard_gauge_tile](https://user-images.githubusercontent.com/6205026/82294129-f1012f00-99ad-11ea-9c5b-3fd4115b3f2a.png)

**Comment by rchl** [comment]
I've tried on a sensor that has float value like that and it worked.
Here is the code and look (not tried to make it pretty :)):
```js
            {
              position: [0, 1.5],
              width: 1.5,
              height: 1,
              title: 'My Gauge Title',
              subtitle: '',
              type: TYPES.GAUGE,
              id: 'sensor.aeon_multisensor_relative_humidity',
            },
```
![Screenshot 2020-05-19 at 09 03 47](https://user-images.githubusercontent.com/153197/82295265-c912cb00-99af-11ea-89b5-b2a16af84030.png)

Maybe check browser (inspector) console for any relevant errors.

If there are none then there is also a chance that you don't have the latest code. That is most likely whats happening here.

**Comment by shiftux** [comment]
i created an empty tileboard with just that one gauge.
errors i get in the inspector are 

```
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for http://192.168.X.Y:8123/local/tileboard/scripts/vendors/angular.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://192.168.X.Y:8123/local/tileboard/scripts/vendors/angular-chart.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://192.168.X.Y:8123/local/tileboard/scripts/vendors/hls.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

i'm guessing the extension ones are irrelevant. is the gauge based on angular and angular-chart?

**Comment by rchl** [comment]
None of those are relevant. Again, I think your code doesn't include the gauge feature.
Rigth click the page, choose "view page source" and search for "types.gauge". If you can't find it then you are not on latest code.

**Comment by shiftux** [comment]
i pulled very recently. it's there

![Screenshot 2020-05-19 at 20 38 49](https://user-images.githubusercontent.com/6205026/82365313-cbf1d800-9a10-11ea-986e-37fe330cd5e8.png)

**Comment by rchl** [comment]
Hmm. Can you try the tile snippet I've posted here and with your sensor ID?

You have never posted the exact configuration you are using for your tile so maybe there is some mistake there. Otherwise, I'm running out of ideas. You might need to debug this by changing the code and seeing where it fails.

**Comment by shiftux** [comment]
copied your snippet
also created a new sensor with just a constant float value as template output
both did not help... 

current code: 
```
   pages: [
      {
         title: 'Weather page',
         bg: 'images/bg2.png',
         icon: 'mdi-weather-partly-cloudy',
         groups: [
              {
               title: '',
               width: 3,
               height: 4,
               items: [
                 {
                    position: [0, 1.5],
                    width: 1.5,
                    height: 1,
                    title: 'My Gauge Title',
                    subtitle: '',
                    type: TYPES.GAUGE,
                    id: 'sensor.total_power_cost',
                  }
                ]
             }
         ]
      }
   ]
}
```

**Comment by shiftux** [comment]
i did not.
i gave up at some point... :/

**Comment by shiftux** [comment]
but fine with me if you want to close the issue...

**Comment by rchl** [comment]
Same tile (of course with different sensor ID) works just fine here:
![Screenshot 2020-08-24 at 09 44 46](https://user-images.githubusercontent.com/153197/91017373-73713e80-e5ee-11ea-9632-4680896f7ce3.png)

So I would suggest:
 - make sure you are on the latest master branch
 - make sure you have no local changes that could affect it
 - try private window
 - try different browsers/devices
 - try with a minimal configuration file
