### ISSUE TITLE
Popup like door_entry but for other purposes

### ISSUE THREAD

**Issue by jnpetersen** [resoai/TileBoard#372]
I'm looking to find if its possible to do something similar to the door_entry popup but just for standard things?

I want to have a single button that can be pushed, that will bring up an overlay of more tiles for things like lights in the room you pressed.  If nothing is pressed for lets say 5 seconds, then the overlay disappears back to the previous screen it was on.

I know I can do pages and then do a window.openPage to load a specific page, but I'd like to reduce the number of pages to basically the 1 page.

Is this possible?

**Comment by resoai** [comment]
If you know JS, you can create your own tile based on the door entry one, it already includes the logic which allows you to add tiles and the inactivity timeout.

**Comment by jnpetersen** [comment]
Ok, I was just checking to see if I was missing something before I went digging through the code.  I also couldn't get the door_entry option to open, but I wasn't sure if its because I removed the camera section as I don't have a live feed I can pull up, but I wanted to see about using the screen to show open doors and the lock status.

**Comment by jnpetersen** [comment]
I got it working... now I'm doing some changes I need and will hopefully get them submitted to you for other people, if you like them.
