### ISSUE TITLE
Text Input Tile

### ISSUE THREAD

**Issue by nnielzz** [resoai/TileBoard#373]
First of all, I understand that this is not really an overall "issue". Apologies if this isn't the right place.

I integrated my Home Assistant with Google Assistant. I created some scripts so I can send a "broadcast"-command to the Google Home. This is all working great, but I miss the option in Tileboard to create a Text Input Tile.

That way, I can enter a custom message which will be send to the Google Home.

Is there any way I could so this? My Angular JS skills are basic at most.

It would look something like this:
[https://i.imgur.com/f4aJ34Y.png](https://i.imgur.com/f4aJ34Y.png)

**Comment by rchl** [comment]
Maybe a tile like that would work for you:
```js
                  {
                     position: [0, 0],
                     width: 1, height: 1,
                     id: {},
                     title: 'Say something',
                     type: TYPES.CUSTOM,
                     state: false,
                     action: function(item, entity) {
                          const text = prompt('What to say?');
                          this.apiRequest({})
                     },
                  },
``
The argument to `apiRequest` would have to be adapter to work with the specific API you want to call.

**Comment by rchl** [comment]
Does this work for you @nnielzz ?

**Comment by nnielzz** [comment]
@rchl Yep! Sorry for the late reply.
I already found a solution that's exactly what you suggested.

Thanks and happy holidays

**Comment by nnielzz** [comment]
@rchl After updating to the latest version of TileBoard. It seems like my code isn't working anymore.
My js knowlegde is limited, but I can follow code most of the time.
I managed to solve it previously by adding some code in the main.js (creating a new scope, if I'm saying that coreect)

Since the main.js file isn't in the directory anymore I tried to implement your code.
But...I'm receiving an "Message formatted incorrectly"-error message. (incorrect format)

I've created the following
`{
                        title: 'Aangepast Bericht',
                        width: 3,
                        height: 1,
                        items: [
                            {
                                position: [0, 0],
                                type: TYPES.CUSTOM,
                                title: 'Custom Message',
                                id: {},
                                width: 3,
                                customHtml: '<div class="form__group field"><input type="input" class="form__field" placeholder="Bericht" name="bericht" id="bericht" ng-model="bericht" required /><label for="name" class="form__label">Bericht in Engels...</label></div><div id="MsgClick" class="item-button -bottom-right"><i class="mdi mdi-send"></i></div>',

                                action: function(item, entity) {
                                    var text = document.getElementById("bericht");
                                    this.apiRequest(item, {
                                        type: "call_service",
                                        domain: "rest_command",
                                        service: "assistant_broadcast",
                                        service_data: {
                                            command: text.value
                                        }
                                    });
                               },
                            }
               ]
            },`

[Image of what it looks like](https://imgur.com/a/8bnt9ID)

You have any idea?

**Comment by rchl** [comment]
The `rest_command.assistant_broadcast` API must be enabled in your HA. You most likely have to define it manually first, as explained in https://www.home-assistant.io/integrations/rest_command/

**Comment by nnielzz** [comment]
Good suggestion, but I have already defined that in my configuration file.
I think I'm not using the apiRequest right.

I did some trail and error coding and figured it out.

See code below:
```
                        title: 'Aangepast Bericht',
                        width: 3,
                        height: 1,
                        items: [{
                            position: [0, 0],
                            type: TYPES.CUSTOM,
                            title: 'Custom Message',
                            id: {},
                            width: 3,
                            customHtml: '<div class="form__group field"><input type="input" class="form__field" placeholder="Bericht" name="bericht" id="bericht" ng-model="bericht" required /><label for="name" class="form__label">Bericht in Engels...</label></div><div id="MsgClick" class="item-button -bottom-right"><i class="mdi mdi-send"></i></div>',
                            action: function (item, entity) {
                                var text = document.getElementById("bericht").value;
                                console.log(text);
                                document.getElementById('MsgClick').onclick =
                                    this.apiRequest({
                                        type: "call_service",
                                        domain: "rest_command",
                                        service: "assistant_broadcast",
                                        service_data: {
                                            command: text
                                        }
                                    });
                            },
                        }]
```
