### ISSUE TITLE
Weather Tileboard

### ISSUE THREAD

**Issue by mostline** [resoai/TileBoard#377]
Hi Alexey,
Can you update wether example? Because as you know dark sky is out of game here.. What about openweather? Thanks!

**Comment by resoai** [comment]
I'm not using OpenWeather, if anyone is I'd be glad to accept a PR however I think that HA opted to use Met.no as the default weather provider.

**Comment by mostline** [comment]
Hi Alexey, in any case i think you are need to change in readme info from dark sky to met.no or openweather - to stay your project on-line. Thanks!

**Comment by Shogun1978** [comment]
I managed to integrate openweathermap and also custom sensor data (from a local weather station on the balcony here). But I was not able to integrate this data in the screensaver. Maybe someone could give an example. Here is my setup for a tile with openweather (incl. weather items, they are placed them in the images folder):

                     type: TYPES.WEATHER,
                     id: {},
                     state: '&weather.openweathermap.state', //function () {return 'Sunny'},
                     icon: '&sensor.owm_weather_code.state',
                     icons: {
                             '200': 'tstorms',
                             '201': 'tstorms',
                             '202': 'tstorms',
                             '210': 'tstorms',
                             '211': 'tstorms',
                             '212': 'tstorms',
                             '221': 'tstorms',
                             '230': 'tstorms',
                             '231': 'tstorms',
                             '232': 'tstorms',
                             '300': 'chancerain',
                             '301': 'chancerain',
                             '302': 'chancerain',
                             '310': 'chancerain',
                             '311': 'chancerain',
                             '312': 'chancerain',
                             '313': 'chancerain',
                             '314': 'chancerain',
                             '321': 'chancerain',
                             '500': 'rain',
                             '501': 'rain',
                             '502': 'rain',
                             '503': 'rain',
                             '504': 'rain',
                             '511': 'sleet',
                             '520': 'rain',
                             '521': 'rain',
                             '522': 'rain',
                             '531': 'rain',
                             '600': 'snow',
                             '601': 'snow',
                             '602': 'snow',
                             '611': 'snow',
                             '612': 'snow',
                             '613': 'snow',
                             '615': 'snow',
                             '616': 'snow',
                             '620': 'snow',
                             '621': 'snow',
                             '622': 'snow',
                             '701': 'fog',
                             '711': 'fog',
                             '721': 'fog',
                             '731': 'fog',
                             '741': 'fog',
                             '751': 'fog',
                             '761': 'fog',
                             '762': 'fog',
                             '771': 'fog',
                             '781': 'fog',
                             '800': 'clear',
                             '801': 'mostlysunny',
                             '802': 'mostlysunny',
                             '803': 'mostlycloudy',
                             '804': 'cloudy',
                            },
                     fields: {
                        temperature: '&sensor.aussentemperatur.state',
                        temperatureUnit: '°C',
                        windSpeed: '&sensor.windgeschwindigkeit_2.state',
                        windSpeedUnit: ' kmh',
                        humidity: '&weather.openweathermap.attributes.humidity',
                        humidityUnit: ' %',
                        list: [
                           'Pressure '
                              + '&weather.openweathermap.attributes.pressure'
                              + ' hPA',

                        ]
                     }

**Comment by Ned-Tom** [comment]
Hello y'all,

@resoai In my case i can't use “met.no” it say's "Unknown"
i use @Shogun1978 solution only completely from open “OpenWeathermap”.

![Screenshot from 2020-07-03 08-51-54](https://user-images.githubusercontent.com/3158863/86445122-21105180-bd12-11ea-9608-151212b4b4e8.png)

Configuration :
```yml
weather:
  - platform: openweathermap
    api_key: <Your Key>
```

Tile:
```js
{
    position: [0, 0],
    height: 2,
    width: 2,
    type: TYPES.WEATHER,
    id: {},
    state: '&weather.openweathermap.state',
    icon: '&weather.openweathermap.state',
    icons: { // https://peter.build/weather-underground-icons/
       'sunny': 'clear',
       'partlycloudy': 'partlycloudy',
       'cloudy': 'cloudy',
       'rainy': 'rain'
    },
    fields: {
       temperature: '&weather.openweathermap.attributes.temperature',
       temperatureUnit: '°C',
       windSpeed: '&weather.openweathermap.attributes.wind_speed:',
       windSpeedUnit: ' kmh',
       humidity: '&weather.openweathermap.attributes.humidity',
       humidityUnit: ' %',
       list: [
          'Pressure '
          + '&weather.openweathermap.attributes.pressure'
          + ' hPA'
       ]
    }
}
```

**Comment by mostline** [comment]
Hi,
all good now, there solution:
https://community.home-assistant.io/t/how-to-extract-temperature-from-weather-card/143260

**Comment by flaviomrib87** [comment]
Hi,

I'm trying to have the forecast but I'm not able anyone did the forecast with openweathermap?



here you can found mine for normal weather,

 {
					position: [0, 0],
					height: 2,
					//classes: ['-compact'], // enable this if you want a little square tile (1x1)
					type: TYPES.WEATHER,
					title: 'Sao Juliao do Tojal',
					id: 'weather.openweathermap',
					state: false, //'&weather.home.state', // label with weather summary (e.g. Sunny)
					icon: '&weather.openweathermap.state',
					//iconImage: '&sensor.dark_sky_icon.state', // use this one if you want to replace icon with image
					icons: 
					{
						'clear-day': 'clear',
						'clear-night': 'nt-clear',
						'cloudy': 'cloudy',
						'rain': 'rain',
						'sleet': 'sleet',
						'snow': 'snow',
						'wind': 'hazy',
						'sunny':'sunny',
						'fog': 'fog',
						'partlycloudy':'partlycloudy',
						'partly-cloudy-night': 'nt-partlycloudy'
					},
					fields: 
					{ // most of that fields are optional
					  summary: '&weather.openweathermap.state',
					  temperature: '&weather.openweathermap.attributes.temperature',
					  temperatureUnit: '&sensor.openweathermap_temperature.attributes.unit_of_measurement',
					  windSpeed: '&weather.openweathermap.attributes.wind_speed',
					  windSpeedUnit: ' km/h',
					  humidity: '&weather.openweathermap.attributes.humidity',
					  humidityUnit: '&sensor.openweathermap_humidity.attributes.unit_of_measurement',
						list:   [
								// another custom line
								 'Pressure '
									+ '&weather.openweathermap.attributes.pressure'
								        + '&sensor.openweathermap_pressure.attributes.unit_of_measurement',

								 // yet another custom line
								 'Rain '
								  +  '&sensor.openweathermap_rain.state'
								  + '&sensor.openweathermap_rain.attributes.unit_of_measurement'
								   // + ' chance of rain'
								]
					}
				},

**Comment by dpgdaniel** [comment]
Hi,

I'm still a bit new to the syntax of home assistant and tileboard (great project btw, thank you very much!) and I was trying to achieve the same thing.

This post answers the question on how to solve the forecast issue:
[https://github.com/resoai/TileBoard/issues/315#issuecomment-562842573](url) 
It works for openweathermap and for met.no as well.

Here are my examples for weather tile and weather_list tile, realized with openweathermap:

Weather Tile:
`                        {
                            position: [1, 0],
                            width: 1,
                            height: 2,
                            type: TYPES.WEATHER,
                            id: 'weather.openweathermap',
                            state: '&weather.openweathermap.state',
                            icon: '&sensor.openweathermap_weather_code.state',
                            icons: {
                                '200': 'tstorms',
                                '201': 'tstorms',
                                '202': 'tstorms',
                                '210': 'tstorms',
                                '211': 'tstorms',
                                '212': 'tstorms',
                                '221': 'tstorms',
                                '230': 'tstorms',
                                '231': 'tstorms',
                                '232': 'tstorms',
                                '300': 'chancerain',
                                '301': 'chancerain',
                                '302': 'chancerain',
                                '310': 'chancerain',
                                '311': 'chancerain',
                                '312': 'chancerain',
                                '313': 'chancerain',
                                '314': 'chancerain',
                                '321': 'chancerain',
                                '500': 'rain',
                                '501': 'rain',
                                '502': 'rain',
                                '503': 'rain',
                                '504': 'rain',
                                '511': 'sleet',
                                '520': 'rain',
                                '521': 'rain',
                                '522': 'rain',
                                '531': 'rain',
                                '600': 'snow',
                                '601': 'snow',
                                '602': 'snow',
                                '611': 'snow',
                                '612': 'snow',
                                '613': 'snow',
                                '615': 'snow',
                                '616': 'snow',
                                '620': 'snow',
                                '621': 'snow',
                                '622': 'snow',
                                '701': 'fog',
                                '711': 'fog',
                                '721': 'fog',
                                '731': 'fog',
                                '741': 'fog',
                                '751': 'fog',
                                '761': 'fog',
                                '762': 'fog',
                                '771': 'fog',
                                '781': 'fog',
                                '800': 'clear',
                                '801': 'mostlysunny',
                                '802': 'mostlysunny',
                                '803': 'mostlycloudy',
                                '804': 'cloudy',
                            },
                            fields: {
                                temperature: '&weather.openweathermap.attributes.temperature ',
                                temperatureUnit: '&sensor.openweathermap_temperature.attributes.unit_of_measurement',
                                windSpeed: '&weather.openweathermap.attributes.wind_speed ',
                                windSpeedUnit: ' kmh',
                                humidity: '&weather.openweathermap.attributes.humidity ',
                                humidityUnit: '&sensor.openweathermap_humidity.attributes.unit_of_measurement',
                                list: [
                                    'Cloud Coverage: '
                                    + '&sensor.openweathermap_cloud_coverage.state '
                                    + '&sensor.openweathermap_cloud_coverage.attributes.unit_of_measurement',
                                    'Pressure: '
                                    + '&weather.openweathermap.attributes.pressure '
                                    + '&sensor.openweathermap_pressure.attributes.unit_of_measurement',
                                    'Precipitation: '
                                    + '&sensor.owm_sum_of_rain_and_snow.state '
                                    + '&sensor.openweathermap_rain.attributes.unit_of_measurement',
                                    //'Rain: '
                                    //+ '&sensor.owm_rain_cleaned.state '
                                    //+ '&sensor.openweathermap_rain.attributes.unit_of_measurement',
                                    //'Snow: '
                                    //+ '&sensor.openweathermap_snow.state '
                                    //+ '&sensor.openweathermap_snow.attributes.unit_of_measurement'
                                ]
                            }
                        },`

Weather List Tile:
`                          {
                            position: [2, 0],
                            type: TYPES.WEATHER_LIST,
                            width: 2,
                            height: 2,
                            title: 'Forecast',
                            id: {},
                            icons: {
                                'clear-day': 'clear',
                                'clear-night': 'nt-clear',
                                'cloudy': 'cloudy',
                                'rain': 'rain',
                                'sleet': 'sleet',
                                'snowy': 'snow',
                                'wind': 'hazy',
                                'fog': 'fog',
                                'partly-cloudy-day': 'partlycloudy',
                                'partly-cloudy-night': 'nt-partlycloudy'
                            },
                            hideHeader: false,
                            //secondaryTitle: 'Precipitation + Wind',
                            secondaryTitle: 'Precipitation',
                            //secondaryTitle: 'Wind',
                            list: [1, 2, 3, 4, 5, 6, 7].map(function (id) {
                                return {
                                    date: function () {
                                        var d = new Date(Date.now() + id * 24 * 60 * 60 * 1000);
                                        return d.toString().split(' ').slice(1, 3).join(' ');
                                    },
                                    icon: function() {
                                        var sensor = this.states['weather.openweathermap'];
                                        return sensor.attributes.forecast[id].condition;
                                    },
                                    primary: function() {
                                        var sensor = this.states['weather.openweathermap'];
                                        var forecast = sensor.attributes.forecast[id].temperature + " / ";
                                        forecast += sensor.attributes.forecast[id].templow + " °C";
                                        return forecast;
                                    },
                                    /*secondary: function() {
                                        var sensor = this.states['weather.openweathermap'];
                                        var precipitation = sensor.attributes.forecast[id].precipitation;
                                        if (precipitation == null) {
                                            precipitation = "0";
                                        }
                                        precipitation += " mm";
                                        var wind = sensor.attributes.forecast[id].wind_speed + " kmh";
                                        return precipitation + " " + wind;
                                    },*/
                                    secondary: function() {
                                        var sensor = this.states['weather.openweathermap'];
                                        var precipitation = sensor.attributes.forecast[id].precipitation;
                                        if (precipitation == null) {
                                            precipitation = "0";
                                        }
                                        precipitation += " mm";
                                        return precipitation;
                                    },
                                    /*secondary: function() {
                                        var sensor = this.states['weather.openweathermap'];
                                        var wind = sensor.attributes.forecast[id].wind_speed + " kmh";
                                        return wind;
                                    },*/
                                }
                            }),
                            state: false,
                        }`

**Comment by rchl** [comment]
The bundled example was updated in https://github.com/resoai/TileBoard/pull/676 . It's now close to posted examples here.
