### ISSUE TITLE
Anonymous function help...

### ISSUE THREAD

**Issue by kovaccs** [resoai/TileBoard#379]
Hi Alex!
Tileboard is an excellent system, I have been using it for days with satisfaction.
However, I've a problem. I want to truncate some of  HA sensors @attributes.friendly_name as it's very long. I would like to expose the substring of the end part of the value, as a titles, to tiles.
Would you help me find the right anonymous function? The examples you provide do not work for me. :-O
Kovaccsaba

**Comment by resoai** [comment]
Hi there. You can get to the attributes using an anonymous function like so: `this.states[item].attributes.friendly_name`

**Comment by kovaccs** [comment]
Thank You for this rapid answer!
Unfortunately I am not an experienced js programmer, so I don't know exactly what the item means and what the entity parameters are.

In this example, I would like to extract part of the title value:
 {
    position: [2.2, 1.2],
    width: 2.2,
    height: 1.5,
    title: 'Telefon/helyzet',
    id: {}, // since we are binding each list item to different sensor, so we simply use an empty object
    type: TYPES.TEXT_LIST,
    state: false,
    list: [
       {
        ....
       }
       {
         //title: '&sensor.battery_state.attributes.friendly_name',
         id: "sensor.battery_state',
         title: function (item, entity) {
            return (entity.attributes.friendly_name);
         },
         icon:  '&sensor.battery_state.attributes.icon',
         value: '&sensor.battery_state.state',
        },
...
The above function returns empty value. And next, how to substring the good return value?
Kovaccsaba

**Comment by resoai** [comment]
```
title: function (item, entity) {
  return this.states[item].attributes.friendly_name;
},
```

**Comment by kovaccs** [comment]
Sorry, but it doesn't work! Empty value comes back in title.
What value should be given to the item and entity?

**Comment by resoai** [comment]
Oh, I've almost completely forgotten about `this.parseFieldValue('...')`. You can try:

```
title: function () {
  this.parseFieldValue('&sensor.battery_state.attributes.friendly_name');
}
```

**Comment by kovaccs** [comment]
This is much better here :-)

title: function () {
  return this.parseFieldValue('&sensor.battery_state.attributes.friendly_name');
}

**Comment by kovaccs** [comment]
Thank you!
This became my solution:
title: function () {
var t = this.parseFieldValue('&sensor.battery_state.attributes.friendly_name');
return t.substring(14);

Good!  Thank's everithing!
}
