### ISSUE TITLE
Personal updates

### ISSUE THREAD

**Issue by twistp** [resoai/TileBoard#380]
Hey Alexey @resoai 

First of all thank you for putting this framework together. This is the best UI for home assistant I have seen so far. I am running TileBoard on a rapberry pi/sunfounder configuration and it looks great and serves to exactly what i needed (i will post some pictures soon). I have made several changes/improvements/additions to TileBoard and was wondering if you would like to review them and eventually incorporate to the distribution code. I am not the best developer but I manage my way around ;)

Here are my mods:

1. Page Loader - I created a simpler way of registering pages and tiles. 
2. Screensaver - Added the ability to have multiple themes, themes organized on a object db, ability to set a time for when the screensaver can play, ability to play videos as screensaver.
3. Fixed the issue with the weather status. Weather status were displaying without a space. Ex. Partly Cloudy would show partlycloudy. Now you can display anything.
4. Created a weather card based on Met.io and sun with 5 days forecast
5. Added wind bearing conversion to cardinal
6. Incorporated animated icons for weather
7. Changed night icons to be called based on sun.sun below_horizon
8. Ability to hide an entire Tile group base on condition
9. Garbage Collection - Added functionality for a Tile to display information and alert  about Garbage collection days
10. Added some functionality for Sonos     

Because there are several changes I decided to check with you first instead of doing pull requests.

Let me know your thoughts.

Cheers
Pedro

**Comment by rchl** [comment]
You have a much higher chance of your PRs being integrated if you separate them into individual PRs. If you drop a PR with everything at once then that will likely not work.

But since most of your changes are new features, it's good that you are asking @resoai as I don't want to decide what should go in and what not.

Fixes are surely welcome though.

**Comment by twistp** [comment]
Cool .... I will work on separating everything and PR'ing them

Cheers

**Comment by rchl** [comment]
Just maybe wait for @resoai's response because I can't promise you that all your changes are in scope of the project.

**Comment by resoai** [comment]
Guys, I really have very little time to keep an eye in this project so if anything is to be added and @rchl thinks it is OK, please go ahead :)

**Comment by amitn322** [comment]
> Hey Alexey @resoai
> 
> First of all thank you for putting this framework together. This is the best UI for home assistant I have seen so far. I am running TileBoard on a rapberry pi/sunfounder configuration and it looks great and serves to exactly what i needed (i will post some pictures soon). I have made several changes/improvements/additions to TileBoard and was wondering if you would like to review them and eventually incorporate to the distribution code. I am not the best developer but I manage my way around ;)
> 
> Here are my mods:
> 
> 1. Page Loader - I created a simpler way of registering pages and tiles.
> 2. Screensaver - Added the ability to have multiple themes, themes organized on a object db, ability to set a time for when the screensaver can play, ability to play videos as screensaver.
> 3. Fixed the issue with the weather status. Weather status were displaying without a space. Ex. Partly Cloudy would show partlycloudy. Now you can display anything.
> 4. Created a weather card based on Met.io and sun with 5 days forecast
> 5. Added wind bearing conversion to cardinal
> 6. Incorporated animated icons for weather
> 7. Changed night icons to be called based on sun.sun below_horizon
> 8. Ability to hide an entire Tile group base on condition
> 9. Garbage Collection - Added functionality for a Tile to display information and alert  about Garbage collection days
> 10. Added some functionality for Sonos
> 
> Because there are several changes I decided to check with you first instead of doing pull requests.
> 
> Let me know your thoughts.
> 
> Cheers
> Pedro

Can you post your sample config for weather forecast using met.mo ? I have been really trying to figure out how to do the forecast card :(

Thank You in Advance.
Amit

**Comment by rchl** [comment]
Feel free to submit individual PRs but I'll close this question since it was answered.
