### ISSUE TITLE
Feature Request - Load Image Slideshow from URL 

### ISSUE THREAD

**Issue by amitn322** [resoai/TileBoard#382]
Hello,
Thanks a lot for this awesome dashboard. I was wondering if it would be possible to somehow Load image slideshow during screensaver from a URL. For example, I could serve a JSON file with the list of image URLs, or may be slideshow all images in a folder , without having to specify the image names for each image? The idea is to be able to dump a lot of images in a location and the dashboard play those images just like a Picture Frame without having to specify every single image name in the configuration. 

Thank You,
Amit

**Comment by resoai** [comment]
Sure. As an example, this is how your would load images from Flickr album:

```
    if (CONFIG.screensaver && CONFIG.flickrApiKey) {
    var url = 'https://api.flickr.com/services/rest/?method=flickr.photosets.getPhotos'
            + '&photoset_id=' + CONFIG.flickrAlbum + '&api_key=' + CONFIG.flickrApiKey + '&format=json&nojsoncallback=1';
            
    var req = new XMLHttpRequest();
    req.open('GET', url, true);
    req.onreadystatechange = function() {
        if (req.readyState === 4) {
            var res = JSON.parse(req.responseText);
            if (res.photoset) res.photoset.photo.forEach(function(p) {
                CONFIG.screensaver.slides.push({
                    bg: 'https://farm' + p.farm + '.staticflickr.com/' + p.server + '/' + p.id + '_' + p.secret + '_h.jpg'
                });
            });
        }
    };
    req.send(null);
}
```

**Comment by amitn322** [comment]
Cool thanks, I am thinking of creating a local photo hosting site and serve the images from there. I will give it a try !

**Comment by ajaxhanna68** [comment]
Hi sir,
I'm a noobie, 
Where should I placed below config,

if (CONFIG.screensaver && CONFIG.flickrApiKey) {
    var url = 'https://api.flickr.com/services/rest/?method=flickr.photosets.getPhotos'
            + '&photoset_id=' + CONFIG.flickrAlbum + '&api_key=' + CONFIG.flickrApiKey + '&format=json&nojsoncallback=1';
            
    var req = new XMLHttpRequest();
    req.open('GET', url, true);
    req.onreadystatechange = function() {
        if (req.readyState === 4) {
            var res = JSON.parse(req.responseText);
            if (res.photoset) res.photoset.photo.forEach(function(p) {
                CONFIG.screensaver.slides.push({
                    bg: 'https://farm' + p.farm + '.staticflickr.com/' + p.server + '/' + p.id + '_' + p.secret + '_h.jpg'
                });
            });
        }
    };
    req.send(null);
}
