### ISSUE TITLE
New type of popup

### ISSUE THREAD

**Issue by resoai** [resoai/TileBoard#388]
A few users have asked for a popup which would be able to show a number of tiles. There is definitely something to it and we are already doing something similar with a door entry popup. How do you @rchl and @akloeckner feel about it? How would you call this type of popup?

**Comment by akloeckner** [comment]
I think, that is a great idea. We could make regular tiles for every current popup. Those tiles could be re-used in the most modular way then. Plus, the configuration would be much more consistent.

On the downside, configuration will become more complex. Unless we introduce some shortcuts. The shortcuts should be compatible with the current popup configurations.

I'd call this `popup` simply. And re-factor every current popup to use the new popup.

**Comment by DeviousPenguin** [comment]
It would be really nice to have a popup type thing for 1x1 light tiles for example.

The popup could have brightness and colour controls, maybe with some sort of template?

**Comment by resoai** [comment]
Not sure as to refactoring of all popups since there are some differences as to how popups behave. I've created a very simple test tile on dev branch, it opens a popup fullscreen, just like door entry one.

https://github.com/resoai/TileBoard/commit/fc9f8eb5b2e4c1e5135b100ba74d5f0fb27010e9

**Comment by akloeckner** [comment]
Nice! I'll try and make a history tile to be tested in the new popup. As of now, I see the following challenges for the popup settings:
* Set up the history tile to be full width
* Make the popup fit around the single tile

Also, I'd name the option `popup` instead of `layout`. And I'd make this popup be usable in every tile `TYPE` through primary and secondary actions or better yet by simply defining the `popup` option.

Another thing: what is the `page` option supposed to do?

**Comment by resoai** [comment]
Great! `layout` and `page` is something which is being inherited from the actual `page` definition, there is where you can define size of the tiles etc. At the moment you can use `$scope.openPopup();` via `action` and `secondaryAction`.

**Comment by rchl** [comment]
I think there would need to be a way to have the popup adjust its size to inner tiles as otherwise, it looks quite weird with tiles taking only a bit of space of the popup.

Or have tiles size adjust to popup size but that would be against current behavior of TileBoard.

**Comment by resoai** [comment]
Yes, adjusting size (and position) of the popup to the tiles is indeed needed. This would involve a bit of math calculating top right and bottom left tile positions and taking into account padding.

**Comment by akloeckner** [comment]
Here's my work-in-progress `history` tile: https://github.com/akloeckner/TileBoard/tree/history-tile

It's working fine in the new popup, I believe. Next would be to adjust the sizes and positions...

Something to keep note of: Tiles in the popup might themselves trigger popups. How to handle that?

**Comment by akloeckner** [comment]
As to the `page` and `layout` options: In `config.js` those are called `pages`, `groups` or `items`, aren't they? I have never come across a `layout` option, nor a `page` option?!

**Comment by akloeckner** [comment]
> Yes, adjusting size (and position) of the popup to the tiles is indeed needed.

I am beginning to doubt that will be possible, see here: https://stackoverflow.com/questions/9539378/stretching-a-div-to-fit-absolutely-positioned-content

**Comment by rchl** [comment]
We don't have to restrict ourselves to CSS. It can be done with JS.

**Comment by resoai** [comment]
To be honest I don't remember how we have it and I don't have access to the PC but usual two tricks I remember have been:

```
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
```

and 

```
    display: flex;
    flex-direction: column;
    margin-top: 50%;
```

**Comment by resoai** [comment]
There is always flex:

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_center-flex

**Comment by resoai** [comment]
Tested and it works great for centering popup however there is a problem getting popup of the right size with relative positioning. Perhaps we could simply find top right and bottom left tile, multiply it by timeline and add padding, or there is some other way of doing it which I can't think of.

**Comment by akloeckner** [comment]
I just pushed another commit to https://github.com/akloeckner/TileBoard/tree/history-tile , which allows to add a fullsize history with some `customStyles`.

**Comment by akloeckner** [comment]
And another commit that actually reuses your new popup for the history popup. The customStyle is a mess, still...
https://github.com/akloeckner/TileBoard/commit/31301c631e04075782988972c6a4a33db4f70166

**Comment by akloeckner** [comment]
I found a simple way to size the popup according to the items using `groupStyles`. That's why I renamed the popup option to `popup`. This struct can contains `page` and `group` fields, thus also uniforming the otions with normal groups. Popups canbe "full-sized" by setting `width` and `height` to something absurdly high (e.g. 100).

It's all in my branch: https://github.com/akloeckner/TileBoard/tree/history-tile

**Comment by resoai** [comment]
Looks good (from the mobile). If there is a chance @rchl could have a look at it, I'd be happy to have it merged!

**Comment by rchl** [comment]
I've tried quickly but seen some exceptions in the console and some things not working. Also, why does that branch combine "history-tile" into the mix also. It makes it harder to check the relevant functionality.

**Comment by akloeckner** [comment]
I just needed a real use case. I quickly fixed up a PR. But I'm on the road, so it have flaws...
