### ISSUE TITLE
Placeholder page for unavailable media_players

### ISSUE THREAD

**Issue by syphernl** [resoai/TileBoard#39]
One of my mediaplayers is configured like this:
```
        {
          position: [0, 0],
          width: 2,
          id: 'media_player.kodi_bedroom',
          type: TYPES.MEDIA_PLAYER,
          state: '@attributes.media_title',
          bgSuffix: '@attributes.entity_picture', // show picture of current media as a background
          bgOpacity: 0.5,
        },
```

This works, however, if it is offline it shows a transparant tile and the title is set to `@attributes.media_title` since there is none. 
It would be nicer if we could have configure some kind of placeholder instead (like HA webinterface has)

**Comment by resoai** [comment]
You can use states map for it like so:

```
 type: TYPES.MEDIA_PLAYER,
             states: {
                on: 'On',
                off: 'Off'
             },
             state: '@attributes.media_title',
```

**Comment by syphernl** [comment]
@resoai Thanks, that does solve the "ugly" display of the `@attributes..` 👍

**Comment by syphernl** [comment]
A placeholder picture would still be a nice-to-have though ;-)

**Comment by resoai** [comment]
It is no longer necessary to add a state map, if the player is off, it will not show ugly `@attributes`
