### ISSUE TITLE
show box fields if

### ISSUE THREAD

**Issue by themsk666** [resoai/TileBoard#391]
i try to show on first page in a box, alerts if some values are not good.
example if cpu temp is high a row appear in the box on first page.
i try like this but with no results:

```
{
  position : [ 0.1, 3.1 ],
  width : 6.2,
  height : 0.6,
  title : false,
  type : TYPES.TEXT_LIST,
  id : {},        // using empty object for an unknown id
  state : false,  // disable state element

  events : [ {
    command : 'alert_cpu',
    action : function(e){
      list : [ {
        type : TYPES.SENSOR,
        title : 'CPU',
        icon : 'mdi-thermometer',
        value : '&sensor.cpu_temp.state',
      } ]
    }
  } ]
}
```

**Comment by rchl** [comment]
`events` is a property of the root of the CONFIG object.

When the particular event is fired, the function is called and it's up to you then to modify the tile and trigger a view update (`angular.element(window).triggerHandler('view:updated')` should work).
