### ISSUE TITLE
how to change this gauge's background-color?

### ISSUE THREAD

**Issue by wxyfx** [resoai/TileBoard#393]
![20200807162704](https://user-images.githubusercontent.com/44796469/89625798-0316ad80-d8cb-11ea-92ed-440b0f4bc532.png)
how to change this gauge's background-color?

**Comment by rchl** [comment]
There is not really an option to change the color of any tile. If you want to do that you need to modify colors in the CSS/LESS file (they are defined at the beginning of the main.less file).

That said, the gauge did not have any color assigned to it so I will assign some in https://github.com/resoai/TileBoard/pull/400 which will hopefully make it look a bit better than boring gray.

**Comment by rchl** [comment]
The default background color is updated now.
To customize it see my previous answer.
