### ISSUE TITLE
Feature_request: meta CSS settings for mobile devices

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#40]
Would be really nice if it was possible to get some sample configuration for mobile devices.

Its way to zoomed in by default and menu icons lapse over tiles when scrolling.

Im not a CSS genius but to have meta site locked to for example 70% zoom would really help.

Cheers

**Comment by nayaj** [comment]
![1b6caa9f-af9c-4e60-b155-a0b256e32cb6](https://user-images.githubusercontent.com/40382766/41820726-76ef304a-77d6-11e8-9302-b29c14f0cd5f.jpeg)

**Comment by resoai** [comment]
Dashboards are not really designed for mobile devices.

**Comment by tranthangdong** [comment]
> Dashboards are not really designed for mobile devices.

Could you please give some help us fixed by ourself
