### ISSUE TITLE
popup closing immediately

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#405]
@dtx360, I am experiencing the popup closing immediately on my mobile, if I long press a tile which is afterwards not covered by the popup. It seems to depend somehow on how long I press the original tile. So, it might just be me. Do you see this, too? 

(I have similar experiences with the light sliders' back button getting clicked immediately after opening the sliders, which is why I don't use them anymore. So, it might be a more general issue.)

#404

**Comment by rchl** [comment]
Do you have an example tile config?

**Comment by dtx360** [comment]
> @dtx360, I am experiencing the popup closing immediately on my mobile, if I long press a tile which is afterwards not covered by the popup. It seems to depend somehow on how long I press the original tile. So, it might just be me. Do you see this, too?

@akloeckner, I did not have these issues your describing before updating to the latest master code to try out the popup tile improvments from the latest pull requests. Sadly the popup tile broke on update and now I get a js error on pushing tile: 
![147121AB-553E-435A-993A-69DA716D30F8](https://user-images.githubusercontent.com/54236204/90988127-aedd2000-e590-11ea-8830-e3c07341f6b5.jpeg)

**Comment by rchl** [comment]
I had something like that but that was due to some cached files. That shouldn't happen normally I think because URLs have random seed but just to be sure can you try in private/incognito window?

**Comment by akloeckner** [comment]
The one file that has no random number is `index.html`. That's why I always have to refresh twice, if I change that file...

**Comment by dtx360** [comment]
Hmm nope, tried using private window. And remove all files except config.js and inserted the latest tileboard-master folder. Tried on multiple devices. Same error.
![Screenshot from 2020-08-23 23-03-50](https://user-images.githubusercontent.com/54236204/90988752-7ee44b80-e595-11ea-82bf-a4b835815765.png)

**Comment by dtx360** [comment]
Maybe my secondAction doesn't work anymore with your updates?

`					   secondaryAction: function(item, entity) 
					   {
					   		return this.$scope.openPopup(item, entity);
					   },`

**Comment by rchl** [comment]
Yes, that's it. Fixin in #406

**Comment by dtx360** [comment]
Thanks @rchl, that did fix my problem. Tried it by inserting your commit manually on main.js. Don't know if this fixes @akloeckner 's orginal topic error? I have no issues with sliders. Everything works as expected on firefox, safari and Amazon Fire HD 10 with Fully kiosk.

**Comment by akloeckner** [comment]
> Do you have an example tile config?

Any tile in position [0,0] with a small popup on secondary action will do. Just make sure the tile is outside the core popup area. 

Long-press the tile and lift your finger as soon as the popup appears. My impression is: If you lift your finger fast enough, the remaining fraction of a second is registered as a click by the newly appeared popup 'blur' frame and the popup is closed immediately. If you're not fast enough, the ghost click does not happen. If you're too fast, the popup won't open.

I'm on Firefox mobile here.

**Comment by akloeckner** [comment]
I knew i had read about something like that before. 'Ghost click' is actually the right term, as it seems.

See last hint here: http://hammerjs.github.io/tips/#%22after-a-tap,-also-a-click-is-being-triggered,-i-don't-want-that!%22

And the article mentioned in the way back machine: https://web.archive.org/web/20131020102624/https://developers.google.com/mobile/articles/fast_buttons

**Comment by akloeckner** [comment]
Maybe, it's just an option away... https://github.com/RyanMullins/angular-hammer/commit/6a1d974272ad650b57b29427212921c0f502996c

**Comment by rchl** [comment]
I'd really would like there to be a solid reproduction for this.

It's normal that click event is handled after touch event if touch event is not prevented but that can be avoided if we know exactly when and where it happens.

So I think we need to understand the issue first, before jumping into workarounds and delaying handlers.

**Comment by rchl** [comment]
Can you try using `hm-tap` instead of `ng-click` for the popup close handler?
`hm-tap` should still trigger on Desktop so it should be fine in that regard.
When using that, I can see an issue that I have to click twice to close the popup but it could be due to devtools triggering a context menu at the same time.

**Comment by akloeckner** [comment]
I'll try that. I'll also set up an example in that course.

**Comment by akloeckner** [comment]
> Can you try using `hm-tap` instead of `ng-click` for the popup close handler?

That seems to fix the issue. Popup is also still closing on one click.

Is there any reason speaking against using `hm-tap` in all places where `ng-click` is currently used? Because: I just constructed an example where the same ghost click happens on the closing `X`. Fixed it with `hm-tap`, too. And I'm pretty sure, we can construct lots of things like that. For example: The sliders on the `light` tile, a `switch`tile in a popup, ...

BTW: That is the example I am using:
```
                  {
                          position: [0,0],
                          type: TYPES.SENSOR,
                     id: testEntity,
                     title: 'COVID-19 in Köln',
                     secondaryAction: function(item, entity) {return this.$scope.openPopup(item, entity, item.popup);},
                     popup: {
                        items: [
                           {
                              position: [0, 0],
                              type: TYPES.HISTORY,
                              id: testEntity,
                              title: '',
                              state: false,
                              offset: 5*24*3600*1000,
                           },
                        ]
                     }
                  },
```

**Comment by rchl** [comment]
I think we can switch out all `ng-click` to `hm-tap`.

**Comment by rchl** [comment]
Fix released in https://github.com/resoai/TileBoard/releases/tag/v2.0.2
