### ISSUE TITLE
remove screensaver on movement

### ISSUE THREAD

**Issue by jordibadiag** [resoai/TileBoard#409]
Hi, 
is there any way to stop screensaver on movement detected?
Thanks for all and thanks so much for Tileboard

**Comment by rchl** [comment]
You mean on motion detected on specific sensor?

**Comment by jordibadiag** [comment]
Yes. finally I did it with python sending a keypress on movement detected (mqtt) to disable the screensaver. It works fine!

**Comment by rchl** [comment]
You can just set up an automation to send a specific event. It's explained in the readme https://github.com/resoai/TileBoard#events

**Comment by jordibadiag** [comment]
Thanks so much, but in my case the screen with tileboard is in another machine, so I need something to receive from HA machine to disable. I appreciate it

**Comment by rchl** [comment]
Not sure what you mean. The events are triggered from HA and received by TileBoard. So it should work in your setup.

**Comment by jordibadiag** [comment]
Now I got it! thanks, its more easy!!!
