### ISSUE TITLE
Feature Request: lock

### ISSUE THREAD

**Issue by avandeputte** [resoai/TileBoard#41]
I have an August lock.   Could you add support for entity types of lock?

The two states are locked and unlocked.  Let me know if there is any other information that would be useful.  Once there is support for locks and covers (garage doors),  then my whole house can be represented with this awesome dashboard!   Can't wait!

![image](https://user-images.githubusercontent.com/20116257/41826712-962fff48-77f9-11e8-8eb6-2b9283bbd068.png)

**Comment by resoai** [comment]
Unfortunately I don't have a lock myself but I can try to blindly make it. Would you be willing to test it and be my  eyes? :)

**Comment by resoai** [comment]
OK, I think I've done it. Would you be able to test it? I've also updated README and tile examples.

**Comment by avandeputte** [comment]
Awesome!  Yes, I will test it this evening.

**Comment by avandeputte** [comment]
Tested - works great!

FYI - You have a typo in TILE_EXAMPLES.md - mispelled "unlocked"
