### ISSUE TITLE
get sensor attributes 

### ISSUE THREAD

**Issue by themsk666** [resoai/TileBoard#410]
cant get json type attributes from sensor in TYPE.TEXT_LIST, in TYPE.SENSOR works fine

the tile code:
`                        id: 'sensor.plex_recently_added',
                        type: TYPES.TEXT_LIST,
                        state: false,
                        list:[
                        {
                         title:  function(item, entity) { 
                             return this.parseFieldValue('&sensor.plex_recently_added.attributes.data[1].title');
                           },
                         icon: 'mdi-office-building',
                        value:  function(item, entity) {
                            return this.parseFieldValue('&sensor.plex_recently_added.attributes.data[1].title');
                        },
                          },
                ]
                        
`
sensor attributes are in this format:
`data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $number - $rating - $runtime
  line4_default: $genres
  icon: 'mdi:eye-off'
- airdate: '2020-08-20T10:41:21Z'
  aired: '2020-07-31'
  release: '$day, $date $time'
  flag: false
  title: The Umbrella Academy
`
the return of functions are : [object Object]

its a bug or i have to update some code in tileboard js files?
regards

**Comment by themsk666** [comment]
found a solution using:
` return this.states['sensor.plex_recently_added'].attributes.data[1].title;`

**Comment by rchl** [comment]
Looks like you found the solution.
