### ISSUE TITLE
Camera aspect ratio

### ISSUE THREAD

**Issue by tungmeister** [resoai/TileBoard#413]
the camera_stream tile doesn't appear to respect the aspect ratio of the camera stream - it shrinks horizontally to fit resulting in the aspect ratio being wrong - could this be padded to preserve the aspect ratio?

types.camera:
![image](https://user-images.githubusercontent.com/127809/91726377-0afb0200-eb98-11ea-966d-19b64884f488.png)

types.camera_stream:
![image](https://user-images.githubusercontent.com/127809/91726110-a0e25d00-eb97-11ea-851c-1e57ee3f1b34.png)

**Comment by resoai** [comment]
You simply need to change objFit:

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by tungmeister** [comment]
@resoai where do I need to specify this?

**Comment by rchl** [comment]
You'll find it referenced on https://github.com/resoai/TileBoard/blob/master/TILE_EXAMPLES.md
