### ISSUE TITLE
Date alongside time

### ISSUE THREAD

**Issue by c0nt4x** [resoai/TileBoard#414]
Hi

I’m totally new to js and I’m using the default downloaded config.js to try and learn.

What I can’t figure out is how to get the date to show alongside the time in the header because currently the date shows below the time in the default file.

**Comment by c0nt4x** [comment]
Bump this one 😀

**Comment by rchl** [comment]
Custom CSS like this maybe:
```css
.date {
  display: inline-block;
}
```

**Comment by rchl** [comment]
From my testing, it looks like this should work so closing.
