### ISSUE TITLE
Tiles Shift down with each vertical menu. 

### ISSUE THREAD

**Issue by NightShaman** [resoai/TileBoard#415]
Using the vertical menu, each menu down the list shifts the cells down further with each menu. Home looks great by the time I get to the 5th or 6th menu it's pretty noticeable.

![aa009be2cc16265b53170c3d38b1d2017b6993f6_2_517x258](https://user-images.githubusercontent.com/12952292/92017386-4d981800-ed19-11ea-99e9-609840023064.png)

![4c21637bf81fb0a5b146b8a814853492b32c04fd_2_517x340](https://user-images.githubusercontent.com/12952292/92017395-5557bc80-ed19-11ea-8107-0fef1139a580.png)

.

**Comment by rchl** [comment]
It's caused by a hack that is enabled when you set `hideScrollbar: true`.

I'm fixing this in #418
