### ISSUE TITLE
Pull variables from type.script

### ISSUE THREAD

**Issue by ouahirog** [resoai/TileBoard#416]
How to directly pull variables from type.script
now i use  this.apiReques call_service to pull three variables:
                                type: 'call_service',
                                 service: 'turn_on',
	                         domain: 'script',
                                 service_data: { entity_id: "script.common_timer", variables:{"duration":"00:10","entity_id":"switch.mp1_mp11","operation":"switch.toggle"} }

**Comment by rchl** [comment]
I'm adding support for that in https://github.com/resoai/TileBoard/pull/417
Feel free to try early as I haven't.

**Comment by ouahirog** [comment]
> I'm adding support for that in #417
> Feel free to try early as I haven't.

it's ok after my testing,
thanks very much.
