### ISSUE TITLE
Google Maps API key

### ISSUE THREAD

**Issue by avandeputte** [resoai/TileBoard#42]
using google maps for locator does not work.   Every request fails with http 403 (forbidden).

The detailed message (from developer tools) is:  "The Google Maps Platform server rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account"

So bottom line,  there has to be a place where a user can add an API key in config.js

**Comment by resoai** [comment]
You can use Yandex map for now, Google Maps are weird, sometimes they work just fine, sometimes they start throwing 403 errors.

**Comment by avandeputte** [comment]
Per https://developers.google.com/maps/documentation/maps-static/intro

and additional http get parameter is needed for the API key.

`https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=600x300&maptype=roadmap
&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=YOUR_API_KEY
`

**Comment by avandeputte** [comment]
yes,  but this should be an easy fix for those wanting google (for more detailed landmark info).
Just need somewhere to store an API key,  and the url changed accordingly.

No big hurry.

**Comment by resoai** [comment]
Sure, I will fix it but I wanted to get to the bottom of it :)

**Comment by resoai** [comment]
Thanks! I've added support for Google API key.

**Comment by resoai** [comment]
Could you please confirm it is working for you?

**Comment by avandeputte** [comment]
yes,  I will confirm the api key, cover and lock all at once this evening.
 I am quite excited about it!

**Comment by avandeputte** [comment]
Tested - API key works great!
