### ISSUE TITLE
People Images Disappear and Re-appear

### ISSUE THREAD

**Issue by c0nt4x** [resoai/TileBoard#422]
Hi

I have two tiles set up to track occupancy but the images keep sliding up out of the tile then sliding back in after a few seconds.

Is there any way to stop this behaviour?

**Comment by rchl** [comment]
Can you post the code of the tile?

**Comment by resoai** [comment]
It is sliding away to show the map. I remember there was a way to avoid showing the map and only show the image but I don’t have access to my PC at the moment.

**Comment by resoai** [comment]
From the top of my head, try setting zoom levels to an empty array like so: `zoomLevels: []`.

**Comment by c0nt4x** [comment]
> Can you post the code of the tile?

```
   {
                        position: [0, 0],
                        title: 'Martin',
                        type: TYPES.DEVICE_TRACKER,
                        id: 'person.martin',
                        states: {
                           home: "Home",
                           not_home: "Away",
                         },
                         width: 1,
                         height: 1,

```

**Comment by c0nt4x** [comment]
> From the top of my head, try setting zoom levels to an empty array like so: `zoomLevels: []`.

That worked! Thank you so much.
