### ISSUE TITLE
No ICON show in tablet but shows on desktop and its working on both devices.

### ISSUE THREAD

**Issue by ajaxhanna68** [resoai/TileBoard#426]
![eed9de25-b7f3-4320-8c03-6a37fb1f5612](https://user-images.githubusercontent.com/65640464/93694382-aa7b3700-fb3d-11ea-9981-6fb3369409c5.jpg)
![7ac5a707-8a71-4b47-a090-c80b30ef6677](https://user-images.githubusercontent.com/65640464/93694385-acdd9100-fb3d-11ea-91b3-017a03468edf.jpg)

all

need help, please.
I have both vertical and horizontal icon shows on my desktop but no icon shows on my samsung tablet....
Without the icons but the tiles is working.

Please assist. thank you

_Originally posted by @ajaxhanna68 in https://github.com/resoai/TileBoard/issues/287#issuecomment-694791076_

**Comment by akloeckner** [comment]
Hmm. Is your tablet connected to the internet? Icons are loaded from online sources, if I'm not mistaken. You could also try the current version of Tileboard. Maybe things are resolved there automagically.

**Comment by rchl** [comment]
In https://github.com/resoai/TileBoard/releases/tag/v2.0.1 the icons are bundled rather than loaded from the Internet so this is hopefully fixed.
