### ISSUE TITLE
Error when running on ipad with safari after iOS 14 upgrade

### ISSUE THREAD

**Issue by bmf7777** [resoai/TileBoard#427]
after ios 14 upgrade on ipad with safari, i'm getting an error dialog box: the dialog box appears twice ... and the error will re-appear in <1 hour

![IMG-4104](https://user-images.githubusercontent.com/33107137/93721643-6fc9cc80-fb46-11ea-8634-d6dcabbe62db.jpg)

**Comment by rchl** [comment]
TileBoard doesn't include any ui3.htm/js. This looks like some code from some IP camera that you are probably loading in an iframe? Not necessarily fault of TileBoard.

**Comment by bmf7777** [comment]
thanks ... i will investigate
