### ISSUE TITLE
Request: Dynamic Screensavers

### ISSUE THREAD

**Issue by MikeKMiller** [resoai/TileBoard#428]
Currently per the documentation screensavers must be explicitly defined i.e...

    slides: [
          { bg: 'images/bg1.jpeg' },
          {
             bg: 'images/bg2.png',
             rightTop: [ // put text to the 2nd slide
                {
                   type: SCREENSAVER_ITEMS.CUSTOM_HTML,
                   html: 'Welcome to the <b>TileBoard</b>',
                   styles: { fontSize: '40px' }
                }
             ]
          },
    ]

My question/request is is it possible to change (even just locally) this to loading a group of screensavers dynamically or even just provide min/max numbers and a path? For example, I have all my images named like 1.jpg, 2.jpg, 3.jpg, etc... So rather than having to go through and define each in the array it would be nice to have a way to simply enter it like:

    slides: [
          {
             path: 'images/',
             extension: '.jpg',
             counter-min: '1',
             counter-max: '8',
             rightTop: [
                {
                   type: SCREENSAVER_ITEMS.CUSTOM_HTML,
                   html: 'Welcome to the <b>TileBoard</b>',
                   styles: { fontSize: '40px' }
                }
             ]
          },
    ]

Then changing the slides from time to time would just be a matter of changing the two numbers.

Any ideas on how I could do this?

**Comment by cgarwood** [comment]
I'm doing dynamic generation for mine. 

For my screensaver definition I just have:
```
screensaver: {
    timeout: 300,
    slidesTimeout: 12,
    rightBottom: [],
    rightTop: [],
    leftTop: [],
    slides: [
      {
        bg: secrets.weather_radar_url,
        id: "weather-map"
      }
    ]
  },
```
and then at the bottom of config.js I have the following, which queries a php file on my webserver that returns a json list of all image files in a specific folder. If you know all the images are in the format 1.jpg, 2.jpg, 3.jpg etc you could simplify this 
```.
/*
 * Get a JSON list of URLs to pictures from the local webserver and
 * create screensaver slides for them.
 */
getPictures();
function getPictures() {
  // Use mapping to query a different URL for each tablet
  var mapping = {
    [device_ids.living_room]: "default",
    [device_ids.master_bedroom]: "default",
    [device_ids.nursery]: "nursery",
  };
  var path = "default";
  if (mapping[device.deviceId]) {
    path = mapping[device.deviceId];
  }
  var xhr = new XMLHttpRequest();
  xhr.open("GET", secrets.get_pictures_path + path);
  xhr.onload = function() {
    var items = JSON.parse(xhr.responseText);
    // Create slides for each picture
    for (var i = 0; i < items.length; i++) {
      CONFIG.screensaver.slides.push({
        bg: secrets.pictures_url_prefix + items[i],
        rightTop: [ssWeather],
        rightBottom: [ssClock]
      });
    }
  };
  xhr.send();
}
```

`CONFIG.screensaver.slides.push({});` is the key to dynamically add slides

**Comment by MikeKMiller** [comment]
Ok, that is a great idea!!! I can do that, thanks for sharing.
