### ISSUE TITLE
Title outgrowing tile for camera

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#429]
I just noticed that the title overflow is not hidden for camera tiles (and a few more). Is there a specific reason for it? 

https://github.com/resoai/TileBoard/blob/538d00a40a7418f4058cd3eae795e676a0ade9e6/styles/main.css#L618

**Comment by resoai** [comment]
We don’t know what to say :)

**Comment by akloeckner** [comment]
:-) Ok. I'll propose a simplification of the code. This seems to become my hobby-horse. ;-)

**Comment by resoai** [comment]
I really appreciate what you and @rchl are doing for the project.
