### ISSUE TITLE
Feature Request: Javascript Tile

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#43]
A standard tile like a light, script, switch, etc tile, but when tapped fires a custom defined Javascript function.

I would use this in combination with Fully Kiosk Browser to launch other apps, such as Netflix or Plex, from my dashboard, or to add a button to turn on/off the tablet's motion detection or screen.

**Comment by resoai** [comment]
I've added a custom tile (only as a test for now). Here is how you use it:
```

                  {
                     position: [2, 3],
                     type: TYPES.CUSTOM,
                     title: 'Custom',
                     id: { counter: 0 },
                     icon: 'mdi-gesture-tap',
                     action: function(item, entity) {
                        item.state = ++entity.counter;
                     }
                  },
```

**Comment by cgarwood** [comment]
Perfect. I'll try to test it out this evening when I get home

**Comment by cgarwood** [comment]
Tested out tonight and it works great. Thanks!
