### ISSUE TITLE
Unused WebSocket connections are not disconnected.

### ISSUE THREAD

**Issue by cadavre** [resoai/TileBoard#430]
I noticed that each refresh (f5) of browser page with opened Tileboard leaves WebSocket connection and creates a new one. This results in this:

<img width="393" alt="Zrzut ekranu 2020-09-24 o 14 54 25" src="https://user-images.githubusercontent.com/461796/94147780-0c0d0f80-fe76-11ea-9faa-d02b95976288.png">

Breaking things down into pieces:

This is how **Home Assistant Lovelace** handles the connections:
<img width="154" alt="Zrzut ekranu 2020-09-24 o 14 56 23" src="https://user-images.githubusercontent.com/461796/94147883-3363dc80-fe76-11ea-8d0f-fb715175af9f.png">

If you open HA once it will add new connection (new browser connected) and each refresh (f5) closes old connection and opens new one resulting in constant *single* connection opened.

On the other hand this is when you open **Tileboard** and start to refresh (f5):
<img width="44" alt="Zrzut ekranu 2020-09-24 o 14 56 25" src="https://user-images.githubusercontent.com/461796/94147994-5bebd680-fe76-11ea-89ce-f29ed2207a97.png">

**Comment by rchl** [comment]
Yes. I've noticed recently that my poor PI will just stop responding after refreshing TileBoard a couple of times. I thought it was related to connections.

**Comment by rchl** [comment]
Actually, I can see the same with the native frontend. Here I'm reloading it multiple times:
![websocket](https://user-images.githubusercontent.com/153197/94180972-1abbec80-fe9f-11ea-8455-6f509679214d.gif)

**Comment by rchl** [comment]
We could try to close the connection but I think the HA core should handle that regardless if we clean up or not so create HA issue: https://github.com/home-assistant/core/issues/40555
