### ISSUE TITLE
Feature Request: Support for fans

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#44]
Add support for turning fans on/off and setting speed. Perhaps tapping the tile can toggle it on/off and holding on the tile can bring up a list to select the speed? Most (possibly all?) `fan.` entities have a defined list of speeds, it can't be set to an arbitrary number or % so I don't think a slider would work.

Here's a state/attribute dump from one of my fans:
```
state: on
speed_list: auto,lowest,low,medium,high
model_name: Ceiling Fan
supported_features: 5
friendly_name: Living Room Fan
device_manufacturer: home_decorators
manufacturer_device_model: home_decorators_home_decorators_fan
speed: low
```

**Comment by resoai** [comment]
What kind of brand of the fan are you  using?

**Comment by cgarwood** [comment]
I'm using these Hampton Bay fan zigbee fan modules via a Wink hub

https://www.homedepot.com/p/Hampton-Bay-Universal-Wink-Enabled-White-Ceiling-Fan-Premier-Remote-Control-99432/206591100

**Comment by resoai** [comment]
Thanks. Looks nice :)

**Comment by avandeputte** [comment]
Just bought the exact same thing last week but I haven't installed it.   So +1 on the feature request!

**Comment by resoai** [comment]
And the service would be `fan.turn_on` and `fan.turn_off` ?

**Comment by cgarwood** [comment]
Correct.

There's also a `fan.set_speed` service which takes a `speed` value from the `speed_list` in the fan attributes.

**Comment by resoai** [comment]
I shall add initial support for fans i.e. turning it on and off and than we could move to a bit more interesting tasks :)

**Comment by resoai** [comment]
Ok guys, whenever you are at home, please have a go at it:
```

                  {
                     position: [2, 3],
                     type: TYPES.FAN,
                     title: 'Ceiling fan',
                     id: 'fan.i_am_you_biggest_fan',
                     icons: {
                        on: 'mdi-fan',
                        off: 'mdi-fan-off'
                     },
                     states: {
                        on: 'On',
                        off: 'Off'
                     }
                  }
```

**Comment by cgarwood** [comment]
just tested it and it works great!

**Comment by resoai** [comment]
Good!

**Comment by resoai** [comment]
When fan is off, do you still see `speed_list` in the attributes or just `supported_features: 5`?

**Comment by resoai** [comment]
Could you please test if you are able to select the speed of the fan now? If speed_list is present than icon will not be displayed (perhaps we could mess around with styling later)

**Comment by cgarwood** [comment]
It calls the set_speed services correctly and adjusts the speed.

Couple thoughts on the display/UI side. Clicking on the speed both toggles it on/off and then pops up the speed selector. Would be better to not trigger the on/off toggle until the speed is selected. Might be good to have the speed selector come up after a long press instead, so a regular tap anywhere on the tile toggles on/off, and if you want to change the speed you can press and hold. Right now if you tap it to turn it off and accidentally hit the speed selector you could end up turning it back on or having to tap back off of it.

My personal preference would be to show the speed in the small spot in the top right corner where it shows the on/off state, and keep the bigger fan on/off icon.

**Comment by resoai** [comment]
Having a long-press is a bit unnecessary here and to be frank is something which creates a lot of problems in the code. Having speed in state would be OK if you didn't have to tap it. I have been moving the icon around the select making it 1/2 size of original icon but it all looked ugly and unnatural. Maybe we will find a better way to represent it in future. 

For now I might have solved the issue with toggling of the fan. Could you please check?

**Comment by cgarwood** [comment]
Tested it out tonight and it's not toggling on/off when the speed select pops up so we're good there
