### ISSUE TITLE
Abbreviate merge process

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#443]
With the new structure, whenever I merge a branch (which I do often), a lengthy process is started. Is there a way to abbreviate that in some way? I wouldn't mind to just disbale it on my end, since it makes it really annoying to merge multiple branches... @rchl

**Comment by akloeckner** [comment]
Also, please let me know when you're done with automatic code changes. I just merged/rebased my local branches. But now they're conflicting again. :-)

**Comment by rchl** [comment]
> a lengthy process is started

On merging, the `npm install` is being run. Is that what you mean? It takes only a few seconds here.

We could not run it but then after merging or pulling new changes you might end up with your local `node_modules` dependencies not being up to date and that can cause things breaking in unexpected ways.

(I am done with linting changes (or any major refactorings) now)

**Comment by akloeckner** [comment]
That's probably it then:
```
husky > post-merge (node v14.5.0)

> tileboard@1.0.2 preinstall /home/homeassistant/.homeassistant/www/tileboard
> npx npm-force-resolutions

[ .................] / preinstall:tileboard: sill lifecycle tileboard@1.0.2~prein
```

It takes 26s here. (On my pi admittedly, but still, that's just where I'm working...)

Could we add this step to the build script instead? If that's the only thing that could fail, it would make sense... And I would have that single command then to slow me down.

**Comment by rchl** [comment]
> Could we add this step to the build script instead?

We could but then that would add an overhead each time you run `npm run build` or `npm run dev` instead. Which seems worse to me.

Instead of running `npm i` automatically, maybe I'll make it just print a message to remind that running `npm i` might be necessary...

**Comment by rchl** [comment]
I'm printing a message now.

**Comment by akloeckner** [comment]
Thanks! Also, I got this when committing:
```
 husky > pre-commit (node v14.5.0)

> tileboard@1.0.3 lint /home/homeassistant/.homeassistant/www/tileboard
> eslint scripts

husky > commit-msg (node v14.5.0)
sh: 1: commitlint: not found
husky > commit-msg hook failed (add --no-verify to bypass)
```

Something wrong on my side, or did you forget to commit a file?

**Comment by rchl** [comment]
I think that's exactly what can happen when you don't run npm i. I've added a new dependency in some of latest commits and you don't have it installed locally.
