### ISSUE TITLE
Make linter fix errors on its own?

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#445]
In home assistant, the pre-commit hook fixes linter problems automatically. You just have to review, git add and git commit again. Can we enable that here, too? That would not make us have to manually fix every space and comma...

**Comment by akloeckner** [comment]
@rchl

**Comment by rchl** [comment]
We sure can.

But personally I'm just running with eslint enabled that fixes all issues automatically on saving the file. You should try that.

**Comment by akloeckner** [comment]
So, you install eslint via npm and run it as some kind of background process? Or as a plugin to your editor?

**Comment by rchl** [comment]
It's an editor plugin. I'm Using Sublime Text so `LSP` + `LSP-eslint` packages work great for that.

For VSCode there is an `Eslint` extension that will do that.

**Comment by akloeckner** [comment]
OK. I see. I'll try some options. Probably I'll just resolve to running `eslint --fix scripts/` manually before committing... :-)

**Comment by rchl** [comment]
Or `npn run fix`

**Comment by akloeckner** [comment]
I resolved to running `yarn fix`. Just need to get it into my habits. :-) I don't have the nerves to change to a different editor. ;-)

I'll close the issue to reduce the number of issues a bit...
