### ISSUE TITLE
webmanifest broken? 

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#446]
I tried to re-install Tileboard as an app after the recent restructure. But Firefox does not offer me `install` anymore. Only a regular `add to home screen`. I guess something broke with the webmanifest since I created it...

**Comment by akloeckner** [comment]
Hmm... The `add to home screen` does what I expect. It's working on the iPad. Maybe the icons/menus have just changed in Firefox...

**Comment by rchl** [comment]
Works for me too on Chrome.
