### ISSUE TITLE
IFRAME tile keeps reloading every few seconds

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#452]
It looks like the URL loaded through IFRAME tile is reloading every few (6 or so here) seconds. That seems very wasteful and unexpected.

I don't see any code that is explicitly reloading the URL so I guess it's just caused by angular doing the digest phase on new changes being received from the API.

**Comment by resoai** [comment]
Strange, I did not experience it before our major refactoring, I'm afraid I still can't test the new code.

**Comment by rchl** [comment]
This is not specific to refactoring but it might be specific to the events that my instance of HA is reporting. Maybe due to just some frequent events received from the sensors).

**Comment by rchl** [comment]
Sorry, I'm stupid. IFRAME tile supports `refresh` and I had it set to 10s. :)

**Comment by resoai** [comment]
:)
