### ISSUE TITLE
Suggestion: Offline MDI

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#453]
MD icons are currently loaded from the web. This might cause some issues, like #426 I believe. Also, this is the only resource not bundled with Tileboard. I suggest to include the icons in the bundle, if possible.

It seems, this might be a suitable approach: https://google.github.io/material-design-icons/#icon-font-for-the-web (second method)

**Comment by resoai** [comment]
I agree. Having icons in a font file is an adequate solution.

**Comment by rchl** [comment]
We are using https://materialdesignicons.com/ and not the official google funt but it's should be as easy (just need to use `npm install @mdi/font` and maybe update rollup config to handle font files).

**Comment by akloeckner** [comment]
> maybe update rollup config

:-) OK... I'll have to leave that to you then.

**Comment by rchl** [comment]
Yes, that's a font (not an icon font) used by one of the themes. I suppose @resoai wanted a font that can display his language. :) Is it still relevant for you @resoai ?

**Comment by resoai** [comment]
@rchl Roboto is a nice font in general and being Russian I decided to include Cyrillic subset of letters, so in a way, yeah, this is still relevant :)

**Comment by rchl** [comment]
This required a [fix in rollup plugin](https://github.com/Anidetrix/rollup-plugin-styles/pull/148) but thankfully the auto was responsive and it was integrated and released quickly. :)
