### ISSUE TITLE
Add smart curtain switch

### ISSUE THREAD

**Issue by mnayef95** [resoai/TileBoard#454]
![](https://ae01.alicdn.com/kf/Hd4d0b28d87b44609bc02d9fc404cb9ddV/Tuya-Smart-Curtain-Switch-WiFi-Roller-Shade-Touch-Switches-Alexa-Echo-Google-Home-Assistant-Enable-Phone.jpg)
I have this switch, and I need to create a new tile that shows three buttons to open, close, and stop.

**Comment by resoai** [comment]
Use `COVER` tile for it.

**Comment by mnayef95** [comment]
@resoai Do you have an example?

**Comment by resoai** [comment]
You define it just like any other tile (i.e. switch) and simply change the typer to `COVER`.

**Comment by mnayef95** [comment]
Thank you @resoai
