### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#456]
Should we opt in for hacktoberfest? I'd be happy to plant a  tree with contributing here...

Basically, the repo needs to be labelled `hacktoberfest`. But individual PRs can be labelled, too. Should be, actually, if we don't succeed to merge them before November.

https://hacktoberfest.digitalocean.com/hacktoberfest-update?utm_medium=email&utm_source=hacktoberfest&utm_campaign=main_&utm_content=response

Side-effect of labelling will probably be more PRs.

**Comment by rchl** [comment]
So far I've only seen pretty poor contributions related to hactoberfest. People tend to try to game the system by fixing typos or making low quality contributions.

But we could reject those so I'm not against it. And I wouldn't mind if you would benefit from it either. So I'm not against.

**Comment by resoai** [comment]
I’m all in!

**Comment by rchl** [comment]
I don't have permission to set the topic for the repo but I've added the label to existing PR.
