### ISSUE TITLE
Switch from npm to yarn

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#457]
Sorry, but I'll have to switch from `npm` to `yarn`. That basically means using `yarn ...` to run commands rather than `npm ...`. Command parameters are slightly different also.
 - `npm i` -> `yarn`
 - `npm i some-package` -> `yarn add some-package`
 - `npm run dev` -> `yarn dev`, `npm run build` -> `yarn build`, etc..

The problem is that `npm` doesn't natively support `resolutions` in `package.json` so I'm using a third party `npm-force-resolutions` package to add support for that through `preinstall` hook. But the problem is that in some cases the hook doesn't run (for example it doesn't trigger in dependabot PRs) and then that reverts forced resolution.

(We need to use `resolutions` because `angular-chart.js` ships with outdated `chart.js` dependency so we need to force the latest version of it manually.)

The alternative is to create and publish our own release of `angular-chart.js` with updated dependencies.
Please let me know if you have any preferences.

**Comment by resoai** [comment]
I think yarn is fine.

**Comment by akloeckner** [comment]
I have no preferences whatsoever. :-)

**Comment by rchl** [comment]
Done in https://github.com/resoai/TileBoard/pull/460
