### ISSUE TITLE
TYPES.SLIDER and 0 values.

### ISSUE THREAD

**Issue by rtsam** [resoai/TileBoard#464]
When using a slider tile. Values with 0 show visually as the slider being in the middle of the tile (50%). This doesn't accurately represent the value. For example to set to 10% I have to move the slider backwards.

I have been updating the code as follows to fix this. It would be good to somehow integrate this into the code. Either for everyone, or as perhaps with a boolean value on the tile to tell it how to display 0

getSliderConf 

         //var value = +attrs[def.field] || 0;
         var value = +attrs[def.field] || +entity.state || 0;

         //value: value || +entity.state || def.value || 0, 
         value: (value === 0) ? (0) : (value || +entity.state || def.value || 0),

**Comment by akloeckner** [comment]
I'm working on a consolidation of the code. Also to fix #425. I see you issue and will incorporate that fix!

**Comment by akloeckner** [comment]
@rtsam can you please re-check if possibly this is solved in the latest release? If not, can you please share your `SLIDER` config along with the corresponding `input_number` in home assistant? 

I am trying to reproduce your issue and I don't succeed. :-)

**Comment by rtsam** [comment]
No problem. So I tried setting the default slider in the example "state" to 0... and that works.

"field" does not. 

   position: [1, 1],
   id: 'cover.front_blind',
   title: 'Front Stairs Blind',
   type: TYPES.SLIDER,
   unit: '%',
   state: false,
   field: 'current_position',
   bottom: false, // puts slider on bottom
   value: '@attributes.current_position',
   slider: {
      max: 75,
      min: 0,
      step: 1,
      title: "Position",
      field: "current_position",
      value: '@attributes.current_position',
      request: {
         type: "call_service",
         domain: "cover",
         service: "set_cover_position",
         field: "position"
      }
   }

**Comment by rtsam** [comment]
closed	current_position: 0
battery_level: 20
Vera Device Id: 28
friendly_name: Front Blind
supported_features: 15

**Comment by rchl** [comment]
Should be resolved by https://github.com/resoai/TileBoard/pull/493, I believe.
