### ISSUE TITLE
Add support for smart tv

### ISSUE THREAD

**Issue by mnayef95** [resoai/TileBoard#486]
It's will be nice if there was support for smart tv, like open Netflix and YouTube, or mute, unmute tv, or change volume, turn on or off, change input source, etc...

**Comment by resoai** [comment]
https://github.com/resoai/TileBoard/blob/master/TILE_EXAMPLES.md#media_player

**Comment by rchl** [comment]
media player handles most of those use cases apart from opening Netflix or YouTube. There is no standard way to do that so you need an integration specific to your TV and trigger some custom commands (different for different TVs).

I have Sony Bravia and its custom integration provides a way to open apps (it's an Android TV) so it's a matter of creating custom scripts for each app you want to open and adding SCRIPT tiles in TileBoard to trigger them.

I don't think TileBoard needs to provide anything extra here.
