### ISSUE TITLE
head / clock font size and margins

### ISSUE THREAD

**Issue by avandeputte** [resoai/TileBoard#49]
On an Amazon Fire HD8 tablet, the clock in the header is much too large for the screen.   It also runs into the tiles.   Removing the header by commenting out the head parameter in config.js works fine,  however I was wondering if there are less drastic options.  Could the font size and margin for the clock be configurable in config.js (similar to the groupMarginCss option)?

**Comment by resoai** [comment]
I've added an option for defining custom clock styles. Simply add following (and any other styles you wish) to CONFIG:

```
  clockStyles: {
     'fontSize': '50px'
  }
```

Would you be able to test it and post a screenshot from your tablet with final settings? This way we could add recommended settings in README for other users to use. Thanks!

**Comment by avandeputte** [comment]
Yes,  I will do that tonight.  Thank you!

**Comment by avandeputte** [comment]
it takes fontsize of 36 to fit.   See attached before and after screenshot.  It doesn't look great, but it fits, and I am not a css wiz.

This is with Fully Kiosk Browser on a Amazon Fire HD 8 tablet, which has a 8" touchscreen; 1280 x 800 resolution at 189 ppi



![fontsize36](https://user-images.githubusercontent.com/20116257/42060865-46132fc6-7af6-11e8-97ca-314d4a03d44f.png)
![default](https://user-images.githubusercontent.com/20116257/42060866-461fbdae-7af6-11e8-8997-621590890b3a.png)

**Comment by resoai** [comment]
Are + and -  on the light tile clickable OK?

**Comment by avandeputte** [comment]
Yes,  they are clickable no problem.

the padding over make the the clock cover the word "climate".
But this works fine:
 clockStyles: {
     		'fontSize': '36px',
		'padding': '10px 10px 10px'	 
  	 },
That's a little better.  The only thing that I think would be better is if the content would shift down a bit to make more room for the header.   Or if the clock was at the bottom right instead of top left.


![screenshot_2018-06-28-17-31-16](https://user-images.githubusercontent.com/20116257/42061907-b8a6b9a6-7af9-11e8-82f2-ffdbaca480e4.png)

**Comment by avandeputte** [comment]
The other thing that would be nice to be able to tweak is the width of the page selector area.    It looks great on the desktop,  but it could be more compact on a tablet and still look great.

**Comment by resoai** [comment]
In CSS `padding`:  is defined as  `top`, `right`, `bottom` and `left`. You can also use individual properties:


  ```
  padding-top
    padding-right
    padding-bottom
    padding-left
```

**Comment by resoai** [comment]
There is also groupMarginCss - CSS margin statement to override the default margin for groups

`groupMarginCss: '20px 40px'`

**Comment by avandeputte** [comment]
OK,  now I feel kind of silly.  Just by making the top groupMarginCss 130px I was able to not even have to use the clock styling you just implemented.   I still think it's a good option though.

![screenshot_2018-06-28-17-52-58](https://user-images.githubusercontent.com/20116257/42062721-7e5364f4-7afc-11e8-9772-996075b9742f.png)

**Comment by resoai** [comment]
Looks perfect! Yes, a healthy amount of customization is always good :)
