### ISSUE TITLE
Popup Timed or Trigger Closure

### ISSUE THREAD

**Issue by jeremywillans** [resoai/TileBoard#496]
Is it possble to implement or advise how to use the following features?
- popup card auto close after a certain duration (either since open or since last action?)
- add logic to button on a popup card to close, after performing action.

For example, I have a popup card for music selection, and I would like the popup card to close after you select an option. Right now it will just remain on the popup until you close it or click outside the popup.

**Comment by akloeckner** [comment]
You can override any actions a tile may perform by setting its `action` parameter to an anonymous function. The default is something like that:
```
action: function (item, entity) { this.$scope.openPoup(item, entity); }
```

Also, you can close the popup manually, by calling `this.$scope.closePopup()`. So, you could do something like the following. Be aware that the timeout might unexpectedly close other popups, if you close the popup manually. We have something implemented to avoid that for the door entry popup. But to make it usable for the user, we'd have to move the `popupTimeout` variable to `$scope.popupTimeout`.
```
action: function (item, entity) {
   this.$scope.openPoup(item, entity); 
   $timeout(function () {
      this.$scope.closePopup();
   }, timeout_in_millliseconds);}
```

Likewise you can override any tile action in your popup, e.g., by first calling its default action and then closing the popup:
```
action: function (item, entity) {
   this.$scope.entityClick({}, item, entity); 
   $timeout(function () {
      this.$scope.closePopup();
   }, shorter_timeout_in_millliseconds_to improve user experience);}
```
