### ISSUE TITLE
Feature Request: Custom Events for Audio and Notifications

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#5]
Another feature I hacked into my HADasboard setup...

Listen for a custom event on the Home Assistant event bus and play and audio file with an optional toast notification or modal popup.

I've used this feature to play a chime when a door opens or closes, as well as playing an alert tone if certain weather alerts are issued or a smoke/co detector goes off. A door chime could pop up a toast notification with which door was opened or closed, and something like a smoke alarm activation could pop up a larger modal dialog with more information.

**Comment by resoai** [comment]
We need to think about it in greater details however we already have a rudimentarry support for events. I'm using one to open a door entry pop-up with fullscreen carema and several buttons to open the gate, turn on outdoor lights and enable intercom. Trigger mimics tap on the tile.

```
[
   {
      trigger: 'script.front_gate_bell_trigger',
      state: 'off',
      tile: { // invisible
         type: TYPES.DOOR_ENTRY,
         id: 'camera.front_door',
         layout: {
            camera: {...}, // camera layout
            page: {},
            tiles: []
         }
      }
   }
]
```

**Comment by Evgeny-** [comment]
In fact our events are too much specific to the door entry. 
More interesting for me, how are events presented in HA. In our case HA trigger state_changed of basic entities like script.front_gate_bell_trigger (even if state not changed)

**Comment by cgarwood** [comment]
In HA you can fire custom events, which come across the websocket in this format:

```
{  
   "data":{  
      "sound":"strings.mp3",
      "tts":"Back Dooropened",
      "command":"play_sound"
   },
   "namespace":"default",
   "origin":"REMOTE",
   "event_type":"hadashboard",
   "time_fired":"2018-06-19T17:32:08.681870+00:00"
}
```

You would just have to subscribe to a specific `event_type` when you connect to the websocket initially.

I like the idea of keeping most of the logic in home-assistant, so you'd have an automation in HA that fired an event to change the display on TileBoard, as opposed to TileBoard needing an automation engine to do things on its own when states change

**Comment by resoai** [comment]
So, say we parse only event_type: tileboard, which commands do we need?

- play_sound
- open_camera
- open_door_entry
- click_tile?
- ....

**Comment by cgarwood** [comment]
Some kind of `navigate` event to switch pages on the dashboard

I'd make use of a `notification` or `toast` event that pops up a toast notification in the corner of the screen

I'd also make use of a `notification` or `modal` event that pops up a modal dialog

Perhaps the ability to define custom events in the config and functions for them to fire would be useful as well. I use Fully Kiosk Browser, so it has options for things like firing TTS on a tablet, or adjusting screen brightness, turning the screen on/off/etc. They're Fully Kiosk Browser specific, so I don't know that including them by default is necessary, but being able to define them in the config would be great.

**Comment by cgarwood** [comment]
Simple javascript functions like:
```
fully.setScreenBrightness(float level)
fully.textToSpeech(String text)
fully.startScreensaver()
fully.stopScreensaver()
```

A full list is at https://www.ozerov.de/fully-kiosk-browser/#websiteintegration

**Comment by resoai** [comment]
Oh wow. Very nice of them. Perhaps we could have something like:

```
command: function(){}
```

**Comment by cgarwood** [comment]
I think something like this would work for defining events in the configuration file:

```
events = {
  'screen_off': function(event_data) { fully.screenOff(); },
  'tts': function(event_data) { fully.tts(event_data['message']); },
  'etc': function(event_data) {}
}
```

Then in HomeAssistant fire an event:
```
{  
   "data":{  
      "message":"Hello",
      "command":"tts"
   },
   "namespace":"default",
   "origin":"REMOTE",
   "event_type":"tileboard",
   "time_fired":"2018-06-19T17:32:08.681870+00:00"
}
```
and the contents of `data:` in the HomeAssistant event get passed into the anonymous function

**Comment by resoai** [comment]
Not exactly, we still want to  be able to react to state changes etc. Let me think about it.

**Comment by resoai** [comment]
Now we have custom events!

```
      {
         command: 'open_doorentry',
         action: function(eventData) {
            this.$scope.openDoorEntry(DOOR_TILE, DOOR_TILE.id);
         }
      },
      {
         command: 'play_sound',
         action: function(eventData) {
            playSound(eventData.sound);
         }
      }
```

When sending events from HA please make sure that you set event_type to `tileboard` and include `command` in data.

**Comment by cgarwood** [comment]
Implemented and README updated with examples
