### ISSUE TITLE
Map slideshow zoom levels

### ISSUE THREAD

**Issue by avandeputte** [resoai/TileBoard#50]
Another enhancement request from me :) 
The zoom levels on maps are not very useful for my family,  especially zoom level 9.  I would be good if it could be configured.  Also the first blank/grey view in the slideshow should be removable.   

![screenshot_2018-06-28-17-40-11](https://user-images.githubusercontent.com/20116257/42062178-ba046612-7afa-11e8-8fde-a20b9430ba91.png)

**Comment by resoai** [comment]
Those are not blank, those are ones with the `entity_picture` perhaps you need to add a `filter` which prefixes them with `CONFIG.serverUrl`. There are also in fact two different slides with the map, one with zoom level 9 and other with 13. Those are part of template in `tile.html`:

```
  <div class="item-slide -map"
                 ng-style="slideMapStyles(item, page, entity.attributes, 9, entity.state)"></div>

            <div class="item-slide -map"
                 ng-style="slideMapStyles(item, page, entity.attributes, 13, entity.state)"></div>
         </div>
```

**Comment by avandeputte** [comment]
OK,  I don't have entity pictures in ha, so that explains the blank tile.
So you think editing tile.html is a good idea?  Won't make upgrades harder or anything?

**Comment by resoai** [comment]
The thing is that making this customizable would  add unnecessary complications and raise questions of other users. It wouldn't be too hard to edit two numbers. At some point tile.html will remain unchanged (once all tile types are implemented).

**Comment by avandeputte** [comment]
yes,  it's not too hard,  let me go do that now :)

I understand you have to reach a balance between making it user friendly enough and customizable.  No worries,  feel free to close :)
