### ISSUE TITLE
Cross origin errors: failed to load head and tile

### ISSUE THREAD

**Issue by rogersmj** [resoai/TileBoard#52]
I'm trying to run TileBoard locally on my Mac, just by opening up index.html in my browser (as suggested in the Community thread) and have it talk to Hass.io running on a RPi. It is receiving events from HA just fine.

However, it's throwing errors about cross-origin requests and I don't get anything showing on my board:

![image](https://user-images.githubusercontent.com/20134/42091127-0806a92a-7b72-11e8-8c2c-001d9c6f8567.png)

I'm guessing this is because it's being run from a file:// protocol. If that's going to be a problem, the project should maybe be bundled with a really simple web server?

**Comment by rogersmj** [comment]
Never mind, I spotted this in the README:

```
Note: If you are opening index.html file locally in Google Chrome than you will face an issue of tiles not being displayed and see an error about cross origin requests not being supported in file:// protocol. in browser's console. You can overcome the problem by starting Chrome with --allow-file-access-from-files switch or simply open the page in Firefox.
```

Still wonder if it should include an optional web server? Closing for now.

**Comment by resoai** [comment]
I think we would simply ask people to copy files to www directory

**Comment by Evgeny-** [comment]
I've reopened it. 
I think most people are using google chrome and open file directly in the browser. So most of users are get this error. And who knows how much of them are left project on this step. 
So my suggestions: 
a) Detect if file opened in chrome via file:// protocol, and then saying to user that is not gonna work
b) Use some plugin for development that will compile html templates right into the one js file
c) Put all templates directly into index.html file, using something like <script type="template"></script>
d) Create a simple webserver with w.g. python

For this project, I'll suggest use c) solution. It's simple and don't require any compilations.

**Comment by rogersmj** [comment]
@resoai , I don't want to do that because my HA server is open to the Internet so I can access it remotely. With the way this project is currently setup, wouldn't dropping this in the www folder expose my config, most importantly my HA password?

Seems like option (c) above would be the best short-term quick fix.

**Comment by resoai** [comment]
Homeassistant will soon move to oauth2 which will fix all our problems

**Comment by Evgeny-** [comment]
This problems already solved

**Comment by amkochaki** [comment]
Hello

I'm accessing my HA via duckdns, but tested it having problems accessing Tilebord, what appears to me is only the background screen and the screensaver also appears. I can access the files from the tileboard directories as well. But I don't know what the screens are not showing. Can someone help me with this please?
