### ISSUE TITLE
Zoomed vision on tablet, and normal on my laptop

### ISSUE THREAD

**Issue by denveronly** [resoai/TileBoard#523]
Hey  there, im trying your integration but i cant make it look good on my tablet. it is like zoomed in.
I tried the WIKI mobile configurations, but i just didn't fix that.
canyou help me sort out why it is not responsive?

**Comment by DeviousPenguin** [comment]
It may be worth looking into adding some extra code into `custom.css`

You may be able to change the views depending on screen size

**Comment by rchl** [comment]
We can't help you since you haven't even provided a screenshot of how it looks and what do you expect.
