### ISSUE TITLE
Customized state not added as css class

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#53]
I have the following on my climate device:

```
{
  position: [0, 0],
  width: 2,
  type: TYPES.CLIMATE,
  id: "climate.hallway",
  title: 'Thermostat',
  state: function () {
    return this.states['sensor.hallway_thermostat_hvac_state'].state;
  }
},
```

The actual state of `climate.hallway` is `cool`, the state of `this.states['sensor.hallway_thermostat_hvac_state'].state` is `cooling`

The generated HTML tag contains the state of climate.hallway, but not the state generated by the `state: function() {}` statement.

```
<div ng-style="itemStyles(item, entity)" class="item ng-scope -climate -cool -th-climate" ng-click="entityClick(page, item, entity)" on-long-press="entityLongClick($event, page, item, entity)" ng-if="entity = getItemEntity(item)" ng-class="itemClasses(item)" style="width: 286px; height: 140px; left: 0px; top: 0px;">
```

**Comment by resoai** [comment]
You see, we are not customising the actual state but rather are simply referencing another one (or even the attribute).  There is no obvious way to set a class of arbitrary sensor let alone, function can in fact refrence multiple ones  or none at all. What you can do is add relevant entries to `classes` in the very same function.

**Comment by cgarwood** [comment]
Successful in adding/removing classes or modifying customStyles from within the state: function(),. Closing this
