### ISSUE TITLE
Camera stream not paused when showing screensaver

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#541]
Reported by @resoai  at https://github.com/resoai/TileBoard/pull/537#issuecomment-732432357

> A separate issue with HLS we have is that pausing the stream is not implemented when page is changed or screensaver starts.
> 
> [https://github.com/resoai/TileBoard/blob/master/scripts/directives.js#L217](https://github.com/resoai/TileBoard/blob/master/scripts/directives.js?rgh-link-date=2020-11-23T21%3A19%3A31Z#L217)

**Comment by rchl** [comment]
I've looked into it and saw that we can pause the video but the HLS script will still keep streaming data. I suppose it's done like that to have a quick resume as soon as video is playing again.

Would just pausing the video but not data stream be OK or would you expect that we completely stop the data stream and playback?

Just stopping the playback at least releases CPU/GPU resources but still uses network.

**Comment by resoai** [comment]
To be honest I would probably stop the stream altogether.
