### ISSUE TITLE
Installation in Docker Container

### ISSUE THREAD

**Issue by lryjnks** [resoai/TileBoard#545]
Hello,

I run Home Assistant via Docker
I have created the folder www/tileboard and copied all files in there.

rename config.example.js to config.js 

At: http://MYIP:8123/local/tileboard/index.html

I only get following Message:

_The directory structure of TileBoard has changed.

Please refer to updated How To Use instructions.

Refer to project's README.md for full instructions._

What am I doing wrong?

**Comment by rchl** [comment]
You have to download the zipped file from the https://github.com/resoai/TileBoard/releases page.

**Comment by lryjnks** [comment]
thx, it works now :)
