### ISSUE TITLE
Streaming integration not set up

### ISSUE THREAD

**Issue by lynxbat** [resoai/TileBoard#547]
I am getting a weird error from the following tile pointing towards a working RTSP stream within HA (amcrest cam).
I googled and search the source and I can't even pin down where the error is coming from. I used the last main release and dev build off master. Same thing.

Here is my example config
```
                  {
                     position: [0, 0],
                     id: 'camera.driveway',
                     type: TYPES.CAMERA_STREAM,
                     bgSize: 'cover',
                     width: 2,
                     state: false,
                     fullscreen: {
                        type: TYPES.CAMERA_STREAM,
                        objFit: 'contain',  // https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
                        bufferLength: 5  // Optional: buffer length in seconds for the HLS buffer, default is 5 seconds
                     },
                     refresh: function () { // can also be a function
                        return 3000 + Math.random() * 1000
                     }
                  },
```

Any advice on what I have wrong

<img width="329" alt="Screen Shot 2020-11-25 at 3 52 58 PM" src="https://user-images.githubusercontent.com/1278669/100280524-4f4b3380-2f36-11eb-937e-2928687a340f.png">

<img width="927" alt="Screen Shot 2020-11-25 at 3 59 32 PM" src="https://user-images.githubusercontent.com/1278669/100281082-4149e280-2f37-11eb-892e-e66621cda085.png">

**Comment by resoai** [comment]
Well, the error is very descriptive. You have not enabled `stream:` component in HomeAssistant.

**Comment by lynxbat** [comment]
Well. Egg meet face.

For anyone who may hit this in google. The relevant HA integration reason why you need `stream:`
```
The stream integration provides a way to proxy live streams through Home Assistant. The integration currently only supports proxying H.264 source streams to the HLS format and requires at least FFmpeg >= 4.
```

Thanks @resoai.

**Comment by lynxbat** [comment]
Closed because I missed an important config item in HA. Not a problem with TB.

**Comment by rchl** [comment]
I've also added a note to the CAMERA_STREAM example here: https://github.com/resoai/TileBoard/blob/master/TILE_EXAMPLES.md#camera-and-camera_stream
