### ISSUE TITLE
Feature request: functions for list values

### ISSUE THREAD

**Issue by rogersmj** [resoai/TileBoard#55]
I want to be able to render other text in the list for sensors that have "on/off" state. For example:

```
{
                           title: 'Garage (1)',
                           icon: 'mdi-garage',
                           value: function() {
                             var val='&binary_sensor.garage_single_bay.state';
                             if(val=="On") {
                               return "Open";
                             } else {
                               return "Closed";
                             }
                           }
                        }
```

This doesn't seem to work right now, it just tries to render the function as a string:

![image](https://user-images.githubusercontent.com/20134/42120624-7367cb20-7bec-11e8-9817-2697b91b451e.png)

Having this would be a very powerful addition to lists.

**Comment by Evgeny-** [comment]
Filters aren't great solution. Probably we should think about make most of properties both functions and strings.

**Comment by Evgeny-** [comment]
Fields in lists now can be used as functions, every function called with context {states, $scope} and has argument tile (that you've proveided in config).

**Comment by stewface** [comment]
Could someone explain to me how to code this up to get it working?

`{
                     position: [1, 1],
                     width: 2,
                     type: TYPES.TEXT_LIST,
                     id: {}, // using empty object for an unknown id
                     **states: {
                        on: "Open",
                        off: "Closed"**
                     },


                     list: [
                     {
                          title: 'Front Door',
                      icon: 'mdi-glassdoor',
                          value: '&binary_sensor.door_window_sensor_158d000153a7ed.state',
                          **states: {
                             on: "Open",
                             off: "Closed"**
                          },
                     },`

Neither position seems to be correct for me (well they both dont work)

**Comment by resoai** [comment]
Text list tile has nothing to do with states. Use anon function to format value however you like:

````
value: function() {
   var val = this.parseFieldValue('&binary_sensor.door_window_sensor_158d000153a7ed.state');
   return val == 'on' ? 'Open' : 'Closed';
}
```

**Comment by stewface** [comment]
Awesome - thank you!! :) 

Working perfectly.

**Comment by markwoitaszek** [comment]
Thank you so much for posting this! Been trying to figure it out for hours.
