### ISSUE TITLE
CAMERA_STREAM doesn't work anymore on the latest versions, while it always worked fine in previous versions of Tileboard

### ISSUE THREAD

**Issue by recklessnl** [resoai/TileBoard#559]
This is the code I used successfully for months, to have the camera streams directly accessible on specific Tileboard pages:

```javascript
{
                     position: [0, 0],
                     width: 5,
                     height: 3,
                     type: TYPES.CAMERA_STREAM,
                     id: 'camera.front_door_cam',
                     bgSize: 'contain',
                     state: false,
                     bufferLength: 5,
                     fullscreen: {
                        objFit: 'cover',
                        type: TYPES.CAMERA_STREAM,
                        entity: 'camera.front_door_cam',
                        bufferLength: 5
                     },
                     refresh: function() { return 3000 + Math.random() * 500; },
                     
                  },
```
This has always worked fine, but for some reason I do not see any streams anymore - it's just a blank screen. Similarly, when I click on it, it will also have a blank screen, no streaming happening.
I did put ``stream:`` in my config.yaml in HASS, and I can access the live stream in regular Home Assistant Lovelace just fine, which seems to point to Tileboard being the issue. For example, on one of my Lovelace pages, I have this code:

```yaml
- type: picture-entity
   entity: camera.front_door_cam
   camera_view: live
   show_state: false
```

Which shows the camera stream directly, it works perfectly fine.

Any ideas on how to get the camera stream to work again in Tileboard?

**Comment by rchl** [comment]
- What browser / device are you trying this on? Does it misbehave on all of them, even the modern ones?
- Can you open TileBoard in a browser with developer tools opened and check if there are any relevant errors in the console
- If not, can you check the Network tab in developer tools and check if there are any failing requests?

**Comment by recklessnl** [comment]
> * What browser / device are you trying this on? Does it misbehave on all of them, even the modern ones?
I'm testing on both Fully Kiosk Browser on an Android tablet, as well as the latest version of Firefox (83.0, 64 bit).


> * Can you open TileBoard in a browser with developer tools opened and check if there are any relevant errors in the console
Yes, in Firefox I get this error:

```
GET http://192.168.1.23:8123/local/tileboard/index.html/api/hls/b316fca4b00192b4bc475fe7d764b94d6c9fj3e365b5488c5d0bf292a2cf5339/master_playlist.m3u8  [HTTP/1.1 404 Not Found 0ms]
```

Seems like it's looking for the HLS stream in the wrong location? Again, the streams work fine from within Home Assistant and the Lovelace frontend.

**Comment by rchl** [comment]
What do you have `CONFIG.serverUrl` set to?

**Comment by recklessnl** [comment]
From my config.js:
``serverUrl: "http://192.168.1.23:8123/local/tileboard/index.html",``

**Comment by rchl** [comment]
It should be just the HA origin so `http://192.168.1.23:8123`

**Comment by recklessnl** [comment]
That fixed it! Thank you @rchl, appreciate the help!
