### ISSUE TITLE
Scene type tile not showing

### ISSUE THREAD

**Issue by sonata7245** [resoai/TileBoard#57]
Im having trouble setting up a scene tile. I have a scene titled Movie_Night in home assistant and added the following to config.js
			  {
				  position:[0,1],
				  id: 'scene.Movie_Night',
				  type: TYPES.SCENE,
				  state: false,
				  icon: 'mdi-movie-roll',
			  },
however when I load the dashboard no tile shows up. Any ideas?

**Comment by Evgeny-** [comment]
Are you sure that is your id correct? It's case sensitive.

**Comment by sonata7245** [comment]
It was supposed to be lower case but that didn't fix the issue.

**Comment by Evgeny-** [comment]
Make sure that entity `scene.movie_night` is exist. And make sure you have no other tiles in the [0, 1] position. And what about other tiles? Do they work?

**Comment by sonata7245** [comment]
Ah well... I mistakenly placed the tile inside of the bracket for one of my sliders. Issue fixed, thanks for the help!
