### ISSUE TITLE
Just a "hey" and a thanks!

### ISSUE THREAD

**Issue by thanksmister** [resoai/TileBoard#582]
I just came here to say hey and thanks for a great web app.   I am the developer and maintainer of WallPanel which Home Assistant users use to display their dashboards on their Android tablets.  

However, as Lovelace grows and becomes more complex, some users with older devices are unable to render Lovelace dashboards.  I have been recommending your app to these users and justed wanted to say thanks because it has really helped. 

I have been following the project and so glad to see some of the recent updates. If I knew HTML/CSS/JS, I would offer to help, but that is not in my wheel well.  

Here is my Github if you are ever want to stop by https://github.com/thanksmister/wallpanel-android.  

Thanks!

-Mister

**Comment by alphasixtyfive** [comment]
Thank you!
