### ISSUE TITLE
Gauge tile

### ISSUE THREAD

**Issue by benalla** [resoai/TileBoard#585]
Hi all,
I use the guage tile for Speedtest.
How can I remove the yellow marked output?

![image](https://user-images.githubusercontent.com/3511603/104970631-6feeb180-59ec-11eb-8815-809d3927fdd8.png)

**Comment by alphasixtyfive** [comment]
You can do this by setting `state: false` for that tile.

**Comment by benalla** [comment]
Thnks.....that worked just fine.
