### ISSUE TITLE
Not sure how to configure this

### ISSUE THREAD

**Issue by jeroenterheerdt** [resoai/TileBoard#62]
I cloned the repo into my www folder. I have my HA install exposed through duckdns. I have edited the config to say: 
```
serverUrl: "https://xxxx.duckdns.org:8123",
wsUrl: "wss://xxxx.duckdns.org:8123/api/websocket",
passwordType: PASSWORD_TYPES.MANUAL,
password: "mypassword",

```

When I go do `https://xxx.duckdns.org:8123/TileBoard/index.html` I get `404: Not Found`.
Help?

**Comment by resoai** [comment]
Firstly, it should be `/local/Tileboard/index.html` and secondly you should never ever do this as you are exposing your password in plain text to the outside world.

**Comment by jeroenterheerdt** [comment]
thanks - that did the trick. I will think about a way to not expose the password.
