### ISSUE TITLE
Setting up work environment

### ISSUE THREAD

**Issue by MikkelFrid** [resoai/TileBoard#622]
Hi Everyone!

I am trying to set up a work environment. 
I am planning to contribute with a lot of CSS animations and improving the support for phone devices.

I am having trouble getting my local work environment to work. 
I get this message: 

![image](https://user-images.githubusercontent.com/8225933/107028938-85b2f380-67ae-11eb-8e8c-af19cf0a842b.png)

I have configured it like this:
![image](https://user-images.githubusercontent.com/8225933/107028974-91061f00-67ae-11eb-8040-aec2035b2083.png)
![image](https://user-images.githubusercontent.com/8225933/107028989-98c5c380-67ae-11eb-9f30-b12c2bc0230b.png)

Anyone knows what I should do?

Thanks. 
Mikkel

**Comment by MikkelFrid** [comment]
Solved! 

Turns out I had to add my locale network in my trusted netwowrks.

**Comment by rchl** [comment]
`yarn dev` within the project directory starts a development server. You shouldn't just open the HTML file manually as browsers have stricter resource handling in that case.

**Comment by MikkelFrid** [comment]
Thanks. I got it to work!
