### ISSUE TITLE
wrong way to install TileBoard

### ISSUE THREAD

**Issue by osilvab** [resoai/TileBoard#634]
Hi Im installing Tileboard in HA on a raspberry pi4 with 7"touch lcd. I did it via ssh `sudo git clone https://github.com/resoai/TileBoard tileboard ` and updated the config file with the respective authToken but when i tried to open it on the webbrowser i get: 

```
If you see this page then you you have most likely picked a wrong way to install TileBoard.

If you are not a TileBoard developer and just want to use it then go to Releases page and download the TileBoard.zip file attached to the latest release.

You can also check out How To Use instructions for more detailed instructions.
```

there is something I have realized is that in the HA fileeditor that im using to edit the config file, the config.js is shown in red letters while the config.example.js is in black. Not sure if that gives a hint.

**Comment by rchl** [comment]
The text that you've quoted tells you what you should instead of cloning the repo.

If the text is not clear then feel free to suggest how to improve it.

**Comment by osilvab** [comment]
Im not very knowledgable in linux/github things, so Im trying many things for first time.  

As I understand with your comment is that cloning is a different thing that downloading and unzipping the file, is it? 

I did another try using scp to transfer the files but unfortunately i couldnt make it due to rights of the user. 

It seems you know well how to solve it and i will appreciate the help.

**Comment by rchl** [comment]
As the text says, download the `TileBoard.zip` file from the [Releases](https://github.com/resoai/TileBoard/releases) page and unzip. This can be done on the pi while being connected through SSH.

**Comment by osilvab** [comment]
Thanks for the hints, I removed the cloned tileboard folder and did this:

```sudo wget https://github.com/resoai/TileBoard/archive/v2.1.3.zip
sudo unzip v2.1.3.zip
mv TileBoard-2.1.3 tileboard
cd tileboard
sudo cp config.example.js config.js
sudo reboot```

then edited the config.js file to include the authToken. but I'm still getting the same error. I must be missing something else.

**Comment by rchl** [comment]
Where have you extracted it exactly and what URL are you opening (skip the domain for privacy reasons if it's public)?

**Comment by osilvab** [comment]
I extracted it in /usr/share/hassio/homeassistant/www
the URL is http://XXXXXX:8123/local/tileboard/index.html

**Comment by rchl** [comment]
If you have `/usr/share/hassio/homeassistant/www/tileboard/index.html` then `http://XXXXXX:8123/local/tileboard/index.html` should work.

Make sure that the browser cache is refresh (try opening in incognito/private mode or do shift+refresh).

Also, you can manually inspect the `/usr/share/hassio/homeassistant/www/tileboard/index.html` file. It should have a lot of code and not only the message text you saw before.

**Comment by osilvab** [comment]
The file is there, but actually when I open it only the lines of the error message are there....

**Comment by rchl** [comment]
You are downloading the wrong file. It needs to be the `TileBoard.zip` file from the Assets section.

**Comment by osilvab** [comment]
yes, that was my issue. I appreciate your help.  it worked now.
