### ISSUE TITLE
Stacking of groups / multiple groups per row/column (reloaded!)

### ISSUE THREAD

**Issue by mikyjazz** [resoai/TileBoard#638]
Sorry to reopen this issue ... I don't understand why it is not possible to arrange groups on multiple rows or columns ... Windows 8 and the Windows 10 menu do ... It would be enough to consider the single group as an object ( tile) and then obtain a nested grid layout ... The dimensions would be easily controlled by measuring the group with the largest ones that would guide the sizing of the external grid ... I hope I was clear ...
Currently I have a very large screen with a single row of groups (representing rooms) each with a number from 1 to 6 maximum 8 tiles arranged on two rows .... I could create groups developed vertically but they would be very ugly (1x8 ) ... You can imagine that without the ability to stack groups most of the screen is left blank and I only have a long row of tiles in the center ...

**Comment by alphasixtyfive** [comment]
I'm sorry but current implementation only allows the groups to be either all vertical or all horizontal. It is what it is.

**Comment by mikyjazz** [comment]
![grid_tiles](https://user-images.githubusercontent.com/38558161/109501706-453a5300-7a98-11eb-8b24-4c186014a3bb.png)
I had to do it myself ...

**Comment by rchl** [comment]
Implemented in #662
