### ISSUE TITLE
Feature request: Add Automation support

### ISSUE THREAD

**Issue by jeroenterheerdt** [resoai/TileBoard#64]
It would be great if support for triggering automations could be added.

**Comment by resoai** [comment]
Not sure what exactly you mean with triggering automatons but there are plans to have custom functions being triggered by HA events #5

**Comment by resoai** [comment]
I always felt that manually triggering automations is a bit odd. They are really designed to get triggered without human interaction. If someone is really desperate it is easy to create a script which triggers automation: 

```
    - service: automation.trigger
      entity_id: automation.foobar
```

**Comment by jeroenterheerdt** [comment]
I was thinking about @rogersmj suggested. Sometimes the automation is not picked up or not picked up right away and I want to be able to trigger it manually. Would be awesome if I do not have to make a script for it ;)

**Comment by resoai** [comment]
Could you please try it? simply add `TYPES.AUTOMATION` tile.

**Comment by jeroenterheerdt** [comment]
I tried:
```
{
                     position: [2, 1], // [x, y]
                     width: 1,
                     type: TYPES.AUTOMATION,
                     id: 'automation.living_room_dim_lights_when_tv_is_on'
                  },
```
The tile shows but clicking on it doesn't do anything. Newbie here.

**Comment by rogersmj** [comment]
I was just working on a branch to do this, but it appears support was already added in master. @jeroenterheerdt , pull in the latest changes and it should work now.

**Comment by resoai** [comment]
@rogersmj  join our Telegram group! This way we could stay in loop to see who is doing what :)

**Comment by jeroenterheerdt** [comment]
awesome, it works!

**Comment by resoai** [comment]
I would really appreciate if someone could help get README and TILE_EXAMPLES up to date.  We are really behind as qe are missing a lot of tile types like automation, fan, cover etc.

**Comment by drodegeb** [comment]
I've been searching and couldn't find it so far.  What would be the tile configuration to have a "switch" that turns on/off enable/disable an automation instead of triggering it?

**Comment by resoai** [comment]
You just need to  specify it as a `SWITCH` tile.
