### ISSUE TITLE
Feature request: Support for custom html in custom tiles

### ISSUE THREAD

**Issue by landrews33** [resoai/TileBoard#67]
e.g. Something like

		<div ng-if="item.innerHTML">
			<div ng-include="item.innerHTML"></div>
		</div>

		<div ng-if="!item.innerHTML">
			<div class="item-entity">
				<span class="item-entity--icon mdi"
					ng-class="entityIcon(item, entity)"></span>
			</div>

		</div>

**Comment by resoai** [comment]
Please try `item.customHtml`

**Comment by landrews33** [comment]
Works perfectly. Thank You
