### ISSUE TITLE
Question about Device Tracking

### ISSUE THREAD

**Issue by xeryax** [resoai/TileBoard#670]
OK, so i am making an ASSUMPTION about your config based on screenshots --
It looks like when one of your tracked entities is in a predefined location, you show a certain state icon (the photo of the person you are tracking), but when they are elsewhere, you show a map... 
1. Is that what you are doing?
2. How? That is really the feature I want - I dont need a map to my wife's work, or my own home when we are at either of those places... :)
Thanks a lot for TileBoard - Ive been using this for a while, and my family loves it.

**Comment by alphasixtyfive** [comment]
Device tracker tile cycles between picture of the person and map(s) at specified zoom levels. 

https://github.com/resoai/TileBoard/blob/master/TILE_EXAMPLES.md#device_tracker

You can also specify one of three map providers.
