### ISSUE TITLE
Support for timestamps

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#671]
A few versions ago, HA switched to timestamps for sensors such as `uptime`. I suggest, we add support for that by
* checking for the `device_class` to be `timestamp`
* converting the sensor value using `timeAgo()`
* splitting out the unit to be displayed in the tile.

**Comment by rchl** [comment]
I've created the uptime sensor using https://www.home-assistant.io/integrations/uptime/ and it's not returning a timestamp:

![Screenshot 2021-03-22 at 22 55 36](https://user-images.githubusercontent.com/153197/112063474-be8e0880-8b61-11eb-9489-498ecfde0222.png)

I'm on HA core-2021.3.2.

**Comment by rchl** [comment]
I guess your comment can still apply, even if it's not technically a timestamp.

But I'm not not sure what unit we would use for that.

**Comment by akloeckner** [comment]
By "technically a timestamp", you mean something like "seconds since 1970", right? HA uses the "ISO format" for this. See the "Warning" here: https://www.home-assistant.io/docs/configuration/templating/#time. Here's a copy:

> If your template is returning a timestamp that should be displayed in the frontend (e.g., as a sensor entity with device_class: timestamp), you have to ensure that it is the ISO 8601 format (meaning it has the “T” separator between the date and time portion). Otherwise, frontend rendering on macOS and iOS devices will show an error. The following value template would result in such an error:
> 
> `{{ states.sun.sun.last_changed }} => 2021-01-24 07:06:59+00:00 (missing “T” separator)`
> 
> To fix it, enforce the ISO conversion via isoformat():
> 
> `{{ states.sun.sun.last_changed.isoformat() }} => 2021-01-24T07:06:59+00:00 (contains “T” separator)`

Our `timeAgo` natively supports this format. So, this works (conceptually):
```
filter: function(v) { return timeAgo(v); }
```

Unfortunately, I have not found a (simple) way to extract the unit from this... But that would be the proper way, I believe: To chose the unit dynamically based on `timeAgo`.

**Comment by alphasixtyfive** [comment]
I'm starting to think that `timeAgo` is not really a good name for the function :)

**Comment by rchl** [comment]
`timeAgo` uses `new Date(..)` which will work with both the number timestamp and an ISO date (calling it a timestamp is IMO not quite correct but that doesn't matter :)).

The only thing I'm wondering about is what do you consider a "unit" in this case? The result of `timeAgo` will be something like "a day ago" or "an hour ago". So what do you consider the unit in this case?

**Comment by akloeckner** [comment]
Starting off `a day ago`, I'd call 
* the number `a`, 
* the unit `day`
* and drop the `ago`.

But you're right. This might not be finegrained enough, because we will only see `a day` all the time, although maybe `1.5 days` might also be of interest... Maybe use the `filter` and `unit` option (which we have already, right?) to determine behavior?

* neither `filter` nor `unit` given = use "automatic default" `timeAgo` behavior as described above
* either `filter` or `unit` given = do not do anything automatically, because user obviously has own intentions.

We could also possibly implement this as default values for `filter` and `unit`. And the user choses, how to overwrite any of those.

An alternative would be to chose one default `unit`, e.g. seconds. Convert to this by default. And let the user override, whatever they cose to.

**Comment by rchl** [comment]
Note that ideally, we should be showing a localized value so that probably throws a wrench in your reasoning since you would have to have separate logic for some locales. I think it might not really be worth splitting anything. Just show exactly what `timeAgo` shows.

**Comment by akloeckner** [comment]
> Just show exactly what `timeAgo` shows.

Maybe without `ago`, i.e. second parameter `true` in the `moment.js` call. Only "problem" is the size of the string returned. In the default font size, it is not shown completely in the tile. Hence the idea of splitting the unit part off. But you're right in that it might become quite difficult to solve in a (localizedly) generic way...

How about the "alternative" of selecting a default unit (`h`?) and converting that?

**Comment by akloeckner** [comment]
I thought about it some time and could not find a really elegant way to do something clever about the units. The closest I came was this:
```js
                     filter: function(value, item, entity) {
                        //var uptime = moment(new Date(value));
                        //var unit = this.$scope.entityUnit(item, entity);
                        //return uptime.diff(moment(), unit);
                        var timeDifference = Date.now() - new Date(value);
                        var unit = this.$scope.entityUnit(item, entity);
                        switch (unit) {
                           case 's':
                              return (timeDifference/1000).toFixed(0);
                           case 'min':
                              return (timeDifference/60000).toFixed(0);
                           case 'Std.':
                              return (timeDifference/3600000).toFixed(1);
                           case 'Tage':
                              return (timeDifference/86400000).toFixed(1);
                           default:
                              return value;
                        }
                     },
                     unit: function(item, entity) {
                        var timeDifference = (Date.now() - new Date(entity.state))/1000;
                        return timeDifference < 60 ? 's' : timeDifference < 3600 ? 'min' : timeDifference < 86400 ? 'Std.' : 'Tage';
                     },
```

So, I followed your suggestion to output `timeAgo` as is. It's at least a sound default. And (including the word `ago`) it is the semantically correct way to express a timestamp (as a point in time). If the user wants something else, I added a hint in `README.md`. Since the uptime sensor is the most probable application to me and (as a duration) it should actually not include the word `ago`, I added an option to `timeAgo` to make that possible easily.

If someone liked to have something more advanced, they will find a start for it in this comment. ;-)
