### ISSUE TITLE
Localize moment, timeAgo, ...

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#678]
Now since there is an option `locale`, this option should also apply to usages of `moment`, for example in history graphs or in `timeAgo`. Because, now, locales are not 100% consistent.

However, I still don't have an idea, how to "properly" solve this. Apparently, we simply need to load the locale file, but I was advised against that, previously. Checking with angular's dynamic locale, they seem to do this, too. Just in a 3rd-party package.

**Comment by rchl** [comment]
Yes, basically we've ended up with a solution that I was recommending against but hidden in a third-party code and slightly more robust.

And yes, we'd need to dynamically load the moment locale and then call `amMoment.changeLocale(..)`.

I won't argue against it since it's apparently the only way to go if we don't want to include all locales in the bundle.

**Comment by akloeckner** [comment]
Is there any “standard“ way to do this (load JS dynamically)? 

I did some searching, but couldn't find a package or angular command to do it. Except jQuery, which might be overkill? I had a function to do it, basically copied from jQuery. But an externally maintained command might be favourable, I guess?

**Comment by rchl** [comment]
https://www.npmjs.com/package/oclazyload looks pretty nice on first sight and has good documentation.

(Of course, as with most angularjs libraries, it's no longer maintained and has a lot of issues open but it might be just fine for our use case).

**Comment by akloeckner** [comment]
Or could we modify this line to merge the contents of the moment locales into the file of the angular locales? 
https://github.com/resoai/TileBoard/blob/1f5f54177b3b2752b5ca1b0b0eb4f61d4dd79889/rollup.config.js#L102

That way we could rely on the single one mechanism (from dynamic angular locales) to load scripts dynamically. And we just needed to call `amMoment.changeLocale` when resolving this promise:
https://github.com/resoai/TileBoard/blob/1f5f54177b3b2752b5ca1b0b0eb4f61d4dd79889/scripts/controllers/main.js#L17

**Comment by rchl** [comment]
That sounded like a good idea. I've looked into it to see if that will work and ended up implementing it in #680.
