### ISSUE TITLE
Camera Stream doesn't work (v2.3.0)

### ISSUE THREAD

**Issue by radaoggy** [resoai/TileBoard#688]
On the first page I have a stream from the camera. When I switch to another page and then go back to the first, stream doesn't work. The console in chome shows an error: 

> hls.js: 4264 Uncaught (in promise) DOMException: The play () request was interrupted by a new load request.

 I always have to reload the whole page. It used to work.

**This is my setting:**

```
[position: [0, 0],
id: "camera.sub",
type: TYPES.CAMERA_STREAM,
bgSize: "cover",
classes: ["-camera-tile"],
title: "",
width: 3,
height: 2,
state: false,
fullscreen: {
   type: TYPES.CAMERA_STREAM,
   objFit: 'contain',
   id: 'camera.main',
   bufferLength: 5
}]
```

**Comment by rchl** [comment]
Reported an issue upstream https://github.com/video-dev/hls.js/issues/3732
