### ISSUE TITLE
window.CONFIG not defined?

### ISSUE THREAD

**Issue by fatboy00** [resoai/TileBoard#689]
Hi There, 

Apologies if this is a straightforward question problem:  I am getting an error thrown from loading config.js.  Browser warns me that 

"The 'config.js' configuration file has loaded but window.CONFIG is not defined!  Please make sure that it defines a CONFIG variable with proper configuration"

I am a newbie.  
I just loaded version 2.3.0 of Tileboard.  
I do get the nice green screen but with no writing.

Any help would be much appreciated.
<img width="443" alt="Screenshot 2021-04-06 at 11 31 18" src="https://user-images.githubusercontent.com/22557772/113698862-cc4c9d80-96cc-11eb-8541-d8826b79d356.png">

**Comment by rchl** [comment]
Once you "OK" this error, you should see a notification popup saying more precisely what the error is (possibly a syntax error in the config file).

**Comment by fatboy00** [comment]
Thanks for the speedy response.  

I have the following error:  uncaught ReferencError: PASSWORD_TYPES is not defined
<img width="295" alt="Screenshot 2021-04-06 at 12 25 53" src="https://user-images.githubusercontent.com/22557772/113703975-716a7480-96d3-11eb-93ff-6873e329c646.png">

Line 17/18 look like this:

   passwordType: PASSWORD_TYPES.PROMPT_AND_SAVE,
   //password: null,

**Comment by rchl** [comment]
That says it all. There is no `PASSWORD_TYPES` defined anywhere unless you define it yourself somewhere in the `config.js`.

None of that code is from the example config so I'm not sure what are you trying to do there.

**Comment by fatboy00** [comment]
Apologies - I am also not sure what it is supposed to accomplish.  I was just following along from a youtube video.

https://www.youtube.com/watch?v=nPA1qvHNGl8

In the video, he uses something slightly different (PASSWORD_TYPES.MANUAL) but that throws the same error as above. From the overview section:

serverUrl: "http://10.10.10.5:8123​",
wsUrl: "ws://10.10.10.5:8123/api/websocket",
passwordType: PASSWORD_TYPES.MANUAL,
password: "HassAPIpass",

I tried taking both lines out, but that doesn't appear to work either - I get an access token error and then (a few seconds later) page goes to 'site cannot be reached.'

Google seems to show that something needs to be put in here, but I'm not really grokking it.

Appreciate your patience.

**Comment by rchl** [comment]
That's something that was present in old versions of TileBoard but things have changes since then.

Just remove `password` and `passwordType` lines and an authentication page should show up where you would input your credentials.

**Comment by fatboy00** [comment]
Sorry to bother you again, and it might be that this issue is closed and I have a new one.

I removed both lines as suggested.  and I get the following error 'ACCESS TOKEN  Error while receiving Access Token'.   After a few seconds the screen goes to "this site cannot be reached".  

I was thinking that I need a password in my configuration.yaml,  but the documentation appears to suggest not (https://www.home-assistant.io/docs/authentication/providers/)

Thanks for any last hints.
<img width="833" alt="Screenshot 2021-04-06 at 13 19 48" src="https://user-images.githubusercontent.com/22557772/113709758-c9f14000-96da-11eb-95c9-92cd013b4bf0.png">
<img width="1135" alt="Screenshot 2021-04-06 at 13 15 47" src="https://user-images.githubusercontent.com/22557772/113709761-ca89d680-96da-11eb-9b50-0d1103f192e4.png">

**Comment by rchl** [comment]
TileBoard redirects to the OAuth HA page when the token is not saved.

The error page says "Check if there is a typo in homeassitant.local" and indeed there is. Missing "s" in homeassitant. Where does that domain come from, I'm not sure. Possibly somewhere in your HA `configuration.yaml` file.

**Comment by fatboy00** [comment]
you solved it.  

Lesson for me...get more accurate with typing!

Many thanks for your patience.
