### ISSUE TITLE
Time no longer using 24hr format after update from 2.1.3 to 2.3.0

### ISSUE THREAD

**Issue by AndreiGavriliu** [resoai/TileBoard#690]
Hi there, 

I just updated to `v2.3.0` and noticed the clock is no longer formatted correctly. I even used the `config.example.js`, just in case something changed between versions, but no success. Is there anything I missed?

```
var CONFIG = {
   //...
   locale: 'en-us', // locale for date and number formats - available locales: it, de, es, fr, pt, ru, nl, pl, en-gb, en-us (default). See readme on adding custom locales.
   // next fields are optional
   events: [],
   timeFormat: 24,
   menuPosition: MENU_POSITIONS.LEFT, // or BOTTOM
   hideScrollbar: false, // horizontal scrollbar
   groupsAlign: GROUP_ALIGNS.HORIZONTALLY, // HORIZONTALLY, VERTICALLY, GRID
   onReady: function () {},
   //...
```

![Screenshot 2021-04-06 at 16 46 45](https://user-images.githubusercontent.com/3742238/113730705-65dd7480-96f8-11eb-89e4-aa664c4871f0.png)

I checked it with chrome/firefox/safari

Cheers,
Andrei

**Comment by rchl** [comment]
More and more functionality leans toward following the locale specific. So try switching locale to `en-uk`, for example.

Currently, `timeFormat` setting is only being used for time format in charts.

**Comment by AndreiGavriliu** [comment]
That did it, thanks!
