### ISSUE TITLE
Fully Kiosk - TileBoard stuck on HA Auth?

### ISSUE THREAD

**Issue by fatboy00** [resoai/TileBoard#693]
Hi There,

Problem:  Cannot load Tileboard onto fully-kiosk browser

I am a newbie running Fully-Kiosk browser on an Amazon Fire 7.  
I can run the lovelace UI on Fully-Kiosk
I have TileBoard working in Chrome browser

The problem appears to be the display of the Auth page from what I can see on the Fully-Kiosk Admin Page.
Auth is not a problem when I use the lovelace UI.
All I have done is add the correct URL to config.js file.

Any help much appreciated.

Thanks

Attached are screen shots

<img width="810" alt="Screenshot 2021-04-08 at 11 26 18" src="https://user-images.githubusercontent.com/22557772/114011621-562b7080-985d-11eb-87e3-67380cf6730f.png">
<img width="1254" alt="Screenshot 2021-04-08 at 11 25 57" src="https://user-images.githubusercontent.com/22557772/114011625-57f53400-985d-11eb-940a-8a4bcc9f3986.png">
<img width="676" alt="Screenshot 2021-04-08 at 11 19 43" src="https://user-images.githubusercontent.com/22557772/114011627-588dca80-985d-11eb-84f9-8dda05c9be3c.png">

**Comment by rchl** [comment]
I don't know anything about Fully but maybe just compare that "Current page" URL with what opens when you login through lovelace. Is the protocol or IP different?

Also, is there access to console logs anywhere? That might also reveal some issue.

**Comment by alphasixtyfive** [comment]
I also don't have any experience with Fully but you can always opt to using long-lived token instead.

**Comment by fatboy00** [comment]
Thanks both.  I resolved it by 
1.  re-installing fully from the beginning; and 
2. ensuring that the very first Start-URL was TileBoard.

Not really sure why that worked.....but hopefully might help someone else.
