### ISSUE TITLE
Location of custom.css

### ISSUE THREAD

**Issue by alphasixtyfive** [resoai/TileBoard#695]
It looks like we have to change the location of `custom.css` since it becomes impossible to access it when using an add-on. There are two ways we could go about it: 

a) Change the location and make a relevant note about breaking change
b) Link it as an additional file

@rchl What do you think?

**Comment by rchl** [comment]
Are you referring to this issue https://github.com/resoai/TileBoard-addon/issues/12 ?

Because I think that can be fixed in the addon without changing the location.

**Comment by alphasixtyfive** [comment]
Yes, I'm referring to this one. I'm sorry I missed that, all working as expected!
