### ISSUE TITLE
Allow Icons with speed selector in Fans entity

### ISSUE THREAD

**Issue by ktnrg45** [resoai/TileBoard#70]
> Changes in main.css:
> .item-fan {
>   z-index: 5;
>   position: absolute;
>   text-align: left;
>   padding: 15px 3px 0;
> }
> Changes in  index.html:<
>div class="item-entity">
>
Example:
![untitled](https://user-images.githubusercontent.com/38207570/42291789-d2f2054e-7f82-11e8-9a7e-ac60bbf3129a.png)
![untitled2](https://user-images.githubusercontent.com/38207570/42291826-0e7667cc-7f83-11e8-9ab7-59be85bc0a31.png)

**Comment by resoai** [comment]
The problem is that speed title could probably be 2 lines long.

**Comment by ktnrg45** [comment]
In regards to the length of each speed string? Its possible that a regrex function can be used to count the letters of string. However, in homeassistant/components/fan/__init__.py the speeds are listed as:
> SPEED_OFF = 'off'
> SPEED_LOW = 'low'
> SPEED_MEDIUM = 'medium'
> SPEED_HIGH = 'high'

Templates excluded, the longest string would be medium.

**Comment by Evgeny-** [comment]
Please update your code and try with icon

**Comment by Evgeny-** [comment]
I'm closing it
