### ISSUE TITLE
Opening webpage on old iPad

### ISSUE THREAD

**Issue by Danielbook** [resoai/TileBoard#712]
Started configuring tileboard to use on my old iPad 2 thats just lying around and it looks great!

Installed the Add on first by putting it in my www/ folder but now I switched and added the repository to the Supervisor. But now the old web page I visited before can no longer be reached. How can I open the page on my iPad again?

**Comment by rchl** [comment]
Define a port that you want TileBoard to be exposed on:
![Screenshot 2021-05-05 at 15 03 55](https://user-images.githubusercontent.com/153197/117145155-1d76ac80-adb3-11eb-99d1-c0e3ea249136.png)

and then visit the address of your HA using that port.

**Comment by spicerackk** [comment]
I tried doing this and it returns a 404 Not Found page, and I'm not sure why.
