### ISSUE TITLE
Open popup from event

### ISSUE THREAD

**Issue by matthias-trip** [resoai/TileBoard#717]
Hi all,

First of all I would like to say thank you for this wonderful project! 

While creating my TileBoard I had the idea of having it automatically open a `DOOR_ENTRY` popup when the doorbell rings. I can easily set this up in Home Assistant by calling , but have no idea how to get this done in TileBoard.

Is this kind of event automation even possible? Either native in TileBoard or by using native JS?

Thanks!

**Comment by alphasixtyfive** [comment]
You can read about the events here: 
https://github.com/resoai/TileBoard#events


You would need to define `DOOR_ENTRY` tile as a variable and use something like this as an action in the event:

```
action: function() {
    this.$scope.openDoorEntry(TILE_VAR, TILE_VAR.id);
}
```
