### ISSUE TITLE
Disconnects lead to multiple websockets and ultimately DOS

### ISSUE THREAD

**Issue by landrews33** [resoai/TileBoard#72]
If my tablet is disconnected - on reconnect I see three websockets open between the tablet and the server.

If it disconnects again it ends up with nine, and increases by a factor of three each time until the server locks up.

One cause of this seems to be that a reconnect is triggered on both an error and a socket close event. Both of which occur when the connection is lost.    I must admit this doesn't explain the third websocket!

Seems _reconnect needs to follow a singleton pattern.

**Comment by Evgeny-** [comment]
I'm closing it
