### ISSUE TITLE
Tileboard not use `states` dict if `state` is a function

### ISSUE THREAD

**Issue by fantomnotabene** [resoai/TileBoard#723]
if defined
```
states: {
    'home': 'Дома',
    'not_home': 'Не дома'
},
```
and 
```
state: function(i, e) {
    return 'home';
}
```
then state field will contain `home`, not `Дома`

**Comment by alphasixtyfive** [comment]
This is by design. While `states` maps actual state from the entity, `state` overrides everything and sets it to whatever you returns.

**Comment by fantomnotabene** [comment]
So I should define my own dict or smth inside of function
Got it
