### ISSUE TITLE
Driveway Gate / Garage / Rear Gate

### ISSUE THREAD

**Issue by remirr** [resoai/TileBoard#728]
Hi there, 

I have three gates controlled by iSmartGate - with the standard integration and card HA knows the state of whether it is open or closed. I tried your gate component but I was not able to get it to work - I tried the LOCK component, which worked but did not show an icon, only an up down arrow. Any ideas?

![Screen Shot 2021-06-18 at 16 56 00](https://user-images.githubusercontent.com/2309583/122615209-22877680-d056-11eb-9c8d-8122d7e40c58.png)

**Comment by alphasixtyfive** [comment]
You probably want `TYPES.COVER_TOGGLE` and as for the icon you'd have to map it in `icons:` just like for any other tile.
