### ISSUE TITLE
No +/- in TYPES.LIGHT

### ISSUE THREAD

**Issue by Quarco** [resoai/TileBoard#743]
I use last versions of TileBoard with Home Assitant and zWaveJS.
But I cannot control the light intensity because the + and - are not shown into the tile.

HUE lights (still) get these controls, but somehow I don't get it with my zwave devices.
Anyone else having this problem? Or is it a bug?

(Screenshot are both dimmers, Hal = Hue, Keuken = zwave)

![image](https://user-images.githubusercontent.com/41013449/127277448-cad310c3-345a-4044-b3e0-df6e88f4909a.png)

**Comment by atleso** [comment]
I'm missing the +/- for my knx lights as well. I have no other lights so nothing to compare with. Happened after upgrading HA.

**Comment by rchl** [comment]
Can you open `/developer-tools/state` and screenshot the relevant entity (including the attributes)?

**Comment by Quarco** [comment]
![image](https://user-images.githubusercontent.com/41013449/127475073-4bae6789-da5a-419b-84d9-11bfcdbd3177.png)
![image](https://user-images.githubusercontent.com/41013449/127475142-71d43a0c-d8ad-45ca-a7ba-da0880db27e2.png)

**Comment by rchl** [comment]
And how does your tileboard entity look like for the tile that is missing the +/- buttons?

**Comment by Quarco** [comment]
![image](https://user-images.githubusercontent.com/41013449/127475868-153570d9-6b25-4c68-8c14-abf5cbbc2ac6.png)

**Comment by atleso** [comment]
HA state attributes:
```
min_mireds: 166
max_mireds: 370
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 90
color_temp: 290
friendly_name: Bedroom 4 (Office) ceiling lights
supported_features: 0
```


Relevant tile config:

```
{
               title: 'Bedroom 4 (Office)',
               width: 1,
               height: 3,
               items: [
                  {
                     position: [0, 0],
                     width: 1,
                     type: TYPES.LIGHT,
                     title: 'Ceiling lights',
                     id: 'light.bedroom_4_office_ceiling_lights',
                     states: { off: 'Off',  on: 'NA' },
                     icons: {
                        on: "mdi-lightbulb-on",
                        off: "mdi-lightbulb",
                     },
                     state: function (item, entity) {
                        if (Math.round(entity.attributes.brightness / 2.55)) {
                           return Math.round(entity.attributes.brightness / 2.55) + " %"
                        } else {
                           return "Off"
                        }
                     },
                     sliders: [
                        {
                           title: 'Brightness',
                           field: 'brightness',
                           max: 255,
                           min: 0,
                           step: 5,
                           request: {
                              type: "call_service",
                              domain: "light",
                              service: "turn_on",
                              field: "brightness"
                           }
                        },
                        {
                           title: 'Color temp',
                           field: 'color_temp',
                           max: 370,
                           min: 166,
                           step: 5,
                           request: {
                              type: "call_service",
                              domain: "light",
                              service: "turn_on",
                              field: "color_temp"
                           },
                        }
                     ]
                  },
                  
               ]
            },
```

**Comment by rchl** [comment]
Looks like we need to change how we check whether the light supports brightness changes since the `SUPPORT_BRIGHTNESS` flag was deprecated in favor of "color mode".

https://github.com/home-assistant/core/blob/1019ee22ff13e5f542e868179d791e6a0d87369a/homeassistant/components/light/__init__.py#L41-L64

@atleso in your case the light doesn't seem to advertise support for brightness change, only color temperature change. Even if it has the `brightness` attribute...

Does it work in native HA UI to change the brightness?

**Comment by atleso** [comment]
Yes, it works in the native UI, and it also works in Tileboard if I long-press the tile.

![image](https://user-images.githubusercontent.com/30384601/127477865-0583b580-c804-4581-8d89-f2b3a91161f0.png)

**Comment by Quarco** [comment]
Great Thanks for looking into this / patch for upcoming release! 👍 @rchl
