### ISSUE TITLE
Error - Unable to fetch image (a webcam that is not always on)

### ISSUE THREAD

**Issue by opep** [resoai/TileBoard#75]
My tileboard stopped to work without doing anyting. All I did was to upgrade tileboard code.
Starting from the beggining, with default config.js, I could identify that the error that I was getting was related to a webcam that is not always on. And when it's off, I get this error (see the link below):

https://imgur.com/SS2xozu

After removing the camera from the config, now tileboard it's working again. This was not happening before. I don't know if a new update broke something.

**Comment by Evgeny-** [comment]
This is a HA error, you need to look at your HA's log.

**Comment by Evgeny-** [comment]
Ok, i got it. Please tell me what the state of camera when it's off?

**Comment by resoai** [comment]
Can you please try fetching latest code and try again?

**Comment by opep** [comment]
Yes. Give me some minutes.

**Comment by opep** [comment]
I still get the same error "Unable to fetch image.", but now tileboard loads, giving this error in the bottom right of the screen. Also, as the refered camera is in the second page, the error only appears if show the second page. If I come back to the first page, the error are still there, but they disappear as their timeout finish.

**Comment by resoai** [comment]
Are you sure that you are using the latest code? You might want to clear browser's cache.

**Comment by opep** [comment]
Yes, latest code. And cleaned cache too.

**Comment by Evgeny-** [comment]
Do you use CAMERA_THUMBNAIL tile type? Try to replace it with just CAMERA and set `refresh` as a 
2000

**Comment by opep** [comment]
The errors are gone changing to CAMERA and refresh 2000.  I was using CAMERA_THUMBNAIL.
You may take a look with cam below, also getting those errors. It's a public cam for testing.

`   position: [0, 0],
   id: 'camera.bekescsaba_hungria',
   type: TYPES.CAMERA_THUMBNAIL,
   bgSize: 'cover',
   width: 2,
   state: false,
   fullscreen: {
      type: TYPES.CAMERA,
      refresh: 1000, // can be number in milliseconds
      bgSize: 'contain'
   },`

`  - platform: mjpeg
    mjpeg_url: http://195.228.161.126:8080/axis-cgi/mjpg/video.cgi?resolution=640x480
    name: Bekescsaba, Hungria`

**Comment by Evgeny-** [comment]
HA wasn't able to handle thumbnail for this camera. 
Btw, if camera source already in "mjpeg" format, then you don't need refresh field.

**Comment by opep** [comment]
Thanks for clarifying this.

**Comment by Evgeny-** [comment]
If everything is ok i'm closing it

**Comment by opep** [comment]
Thank you.
