### ISSUE TITLE
prompt you for your login credentials after restarting Home Assistant

### ISSUE THREAD

**Issue by pw44** [resoai/TileBoard#754]
TileBoard will be available at http://HASS_IP:8123/local/tileboard/index.html and will prompt you for your login credentials after restarting Home Assistant.

I could not understand how it prompts for login credentials, as it does not appears.

**Comment by pw44** [comment]
thanks for the answer: You need to use the HA addon https://github.com/resoai/TileBoard-addon

I don't have the Addons. I'm on bare metal. Any hint?

**Comment by niklas007** [comment]
same issue here

**Comment by rchl** [comment]
Just use the addon (https://github.com/resoai/TileBoard#run-as-a-home-assistant-addon) unless you have more specific needs.
