### ISSUE TITLE
Tileboard starts to ask for password when including a COVER

### ISSUE THREAD

**Issue by opep** [resoai/TileBoard#76]
My Tileboard doesn't have a password ( password: null,) , but when I include a cover in config.js tileboard starts to ask for a password! Weird.  What is wrong?

{
                     position: [0, 3],
                     type: TYPES.COVER,
                     title: 'Garage door',
                     id: 'cover.garage1'
                     states: {
                        open: 'Open',
                        closed: 'Closed'
                     }
 },

**Comment by cgarwood** [comment]
Usually that means there's a Javascript syntax error in your `config.js`. Based on the snipped you posted it looks like you're missing a `,` after `id: 'cover.garage1'`

**Comment by opep** [comment]
You are right! Thanks for figure it out.  I got the example from
https://community.home-assistant.io/t/new-dashboard-for-ha/57173/266
