### ISSUE TITLE
"Image" tile no longer working

### ISSUE THREAD

**Issue by christophebaraer** [resoai/TileBoard#761]
I used Tileboard (pre-1.0.0) with the "Image" title to display a QR code with details about my guest network and recently updated to the latest version to see the recent improvements the community has added. 

While the update went smooth, I noticed that the image tile was no longer displaying my image. See attached image with details. It looks the details from the config.js with the path to the image isn't fetch properly.

<img width="1440" alt="Screenshot 2021-08-27 at 16 03 15" src="https://user-images.githubusercontent.com/38278243/131140487-2491cf35-9125-4c00-81cb-b6abcd25e202.png">

**Comment by rchl** [comment]
How does the code of your tile look like?

**Comment by christophebaraer** [comment]
Thanks @rchl for the answer. The config hasn't changed from my side : 

```
{
                title: 'Guest network',
                width: 1,
                height: 3,
                items: [{
                        position: [0, 0],
                        type: TYPES.IMAGE,
                        id: {},
                        imageURL: '../unifi++.png'
                    }]
            }
```

but it looks like the path to the image isn't properly filled in the HTML as seen below.

```
element.style {
    background-image: url((unknown));
}
```

Replacing the CSS with the path to the image works just fine.

```
element.style {
    background-image: url(unifi++.png);
}
```

**Comment by rchl** [comment]
An `url` property is expected, not `imageURL`.

Not sure if that has changed and whether it was on purpose...

**Comment by christophebaraer** [comment]
Thanks @rchl 👍👍

I also noticed that when looking into `main.js` to compare a pre-1.0.0 previous version with the latest one and also noticed the change from `imageURL` to `url`. It's now working like a charm! Closing this issue.
