### ISSUE TITLE
Feature request: Custom image for weather icon

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#78]
As far as I can tell, we can only use mdi icons for weather icon. The API I'm using provides its own image and there can be a lot of variants of the icon (see https://om.yr.no/symbol/) so it's hard to map all of those to mdi icons. So I would suggest having support for specifying own icon image instead of using mdi icons.

**Comment by rchl** [comment]
Just realized that not mdi icons are used but included svg icons. Still, it would be a lot of work to try to map those to ones provided by `yr` and probably some wouldn't match exactly.

**Comment by resoai** [comment]
We are actually using Weather Underground icons with images stored in `\images\weather-icons`.

**Comment by resoai** [comment]
So what does YR sensor return? What is the value of the icon?

**Comment by rchl** [comment]
It returns numeric value of the icon in `state` (for example `sensor.yr_symbol.state: 2`) and corresponding URL of the icon image in attributes:
```
attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute. friendly_name: YR Symbol
entity_picture: https://api.met.no/weatherapi/weathericon/1.1/?symbol=2;content_type=image/png
```
I could take a shot at implementing this if you agree it is useful and we can agree on how it should be defined in the config file.

**Comment by rchl** [comment]
I'm not claiming that YR's images are better visually but if the choice is to either do the manual labor of mapping YR's icons to bundled ones (and as I said, there would probably be no 1=1 matches for some icons -- but possibly I'm wrong here) or just using whatever API provides, then I would think that latter is easier and more future proof.

YR does actually also provides icons in SVG format so it would work in all sizes.
For example: https://www.yr.no/grafikk/sym/v2016/svg/01d.svg

There is more information about the API here: https://om.yr.no/info/verdata/spesifikasjon/ (in Norwegian).

Unfortunately the HA component (https://www.home-assistant.io/components/sensor.yr/) doesn't expose URLs of those "new" images (there is "old" and "new" variant of icons), so it would be hard to use those SVG images currently. The component would need to be updated first...

**Comment by resoai** [comment]
We could create a CSS file with classes for YR icons. Let's think about it.

**Comment by rchl** [comment]
> We could create a CSS file with classes for YR icons. Let's think about it.

Sure but that would be catering for one specific sensor instead of having generic solution.

> Couldn't you just use the .attributes.entity_picture of the YR sensor as the icon on the weather tile?

As far as I can see from the code, the value of the `icon` property (also value returned from `iconMap`) is just applied as a class name. So it wouldn't work to specify image URL here.

**Comment by rchl** [comment]
I've implemented this for myself. Feel free to review and decide if it's worth it.
