### ISSUE TITLE
api not defined after refactor

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#79]
After the refactoring commits this morning, I'm getting the following error when loading up TileBoard. TileBoard loads OK with the exception of CAMERA tiles.
```
angular.min.js:123 ReferenceError: api is not defined
    at reloadImage (directives.js:143)
    at m.$digest (angular.min.js:147)
    at updateView (main.js:1443)
    at Object.<anonymous> (main.js:1271)
    at api.js:171
```

**Comment by resoai** [comment]
Did you grab the latest code? There has been an update last hour.

**Comment by cgarwood** [comment]
Haha, thought I had the latest.. Not used to projects that move this fast :)

It's working after pulling the newest commits.
