### ISSUE TITLE
Update MDI Icons

### ISSUE THREAD

**Issue by rcoodey** [resoai/TileBoard#803]
This is more of a request than an issue, but could you please update the MDI icons. The latest is v6.5.95 as of writing. They added a handful of additional home related icons a few versions back that I started using in HA. Thanks!

**Comment by stcbus** [comment]
Agreed. Ran into this today, missing newer icons like one for recessed lights.

**Comment by rchl** [comment]
Updated in https://github.com/resoai/TileBoard/releases/tag/v2.9.0 and https://github.com/resoai/TileBoard-addon/releases/tag/v1.3.4
