### ISSUE TITLE
Media player controls don't adapt to size

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#82]
I have media player component in 2x2 size and in that layout controls don't align nicely IMO. I would expect progress bar to be at the bottom at least. Maybe play/pause button on the left of it.

I have it in that layout because:
a) album covers are square
b) 1x1 is a bit too small.
<img width="338" alt="double-height-media" src="https://user-images.githubusercontent.com/153197/42573280-f327876e-851b-11e8-9543-ff9bff0af693.png">

**Comment by rchl** [comment]
BTW. What's the stance on using flex box. I think it's sufficiently supported by browsers now.

**Comment by rchl** [comment]
Also, it would be nice to have some more space for album title / track / Artist. Would be nice to present all those three in non-truncated form. Currently there is just not enough space in top-right corner to show them all.

**Comment by rchl** [comment]
For comparison here is media player widget from HA's UI:
<img width="515" alt="ha-mp" src="https://user-images.githubusercontent.com/153197/42573491-852fb74e-851c-11e8-9eaf-c69b92c68ddd.png">

**Comment by Evgeny-** [comment]
I agreed, our media_player isn't nearly perfect.

**Comment by Evgeny-** [comment]
Real question here isn't about flexboxes, but about adaptive layout, how it should looks like in our case. Because media_player can also have select in it.

**Comment by rchl** [comment]
I think flexbox would make it easier to create adaptive layout.

**Comment by Evgeny-** [comment]
May be, but it's not a main problem here

**Comment by Evgeny-** [comment]
Ok please update your code and try now. 1x1 seems now supported

**Comment by rchl** [comment]
You meant 2x2 I guess...

It looks nice now, thanks.
It surely can be improvement more but doesn't look out-of-place now.

One thing though, 'Source' text shows up permanently. It doesn't really make sense in my case at least (Sonos One speaker) so would be nice to not show it when there is no `attributes.source`.

![source](https://user-images.githubusercontent.com/153197/42593445-be6710e0-854c-11e8-886f-7c4bda110193.png)

**Comment by Evgeny-** [comment]
I meant 1x1, which wasn't really supported. If source field appears without source_list, then it's a bug.

**Comment by Evgeny-** [comment]
Checked code, seems like code is fine, and you probably have source list in the player. Anyway, if you want to hide it, you may use hideSource: true, in the tile. Also its possible to use subtitle for songname instead of state

**Comment by rchl** [comment]
It has source_list but it's empty so probably should be treated like it doesn't exist:
```
volume_level: 0.16
is_volume_muted: false
media_content_type: music
media_duration: 15
media_position: 15
media_position_updated_at: 2018-07-11T19:27:57.879974+00:00
media_title: OUTRO - Will Singing the Clash
media_artist: Will Byers
media_album_name: Stranger Things (Soundtrack from the Netflix Original Series)
source_list: 
shuffle: false
sonos_group: media_player.kitchen
friendly_name: Kitchen
entity_picture: /api/media_player_proxy/media_player.kitchen?token=9b6ea47e76434f801555681275cb3c8d097afcb28fd56b1f8858de8d5319554c&cache=f5a03202e4ed521d
supported_features: 64063
```

**Comment by Evgeny-** [comment]
Did you hide the state? I think you should have enough space without source and state, unless your tilesize is much less than original

**Comment by rchl** [comment]
Look at that state I've posted - the album name is quite long. In fact, it even overflows tile when shown, so that looks buggy.

Yes, I can hide the state and have more space, but consider handling empty source_list as if there would be no source_list. I think that makes sense.

**Comment by Evgeny-** [comment]
Yes, it will be fixed tomorrow
