### ISSUE TITLE
Add ability to specify decimals to show for temperatures on WEATHER_LIST tile

### ISSUE THREAD

**Issue by sjabby** [resoai/TileBoard#84]
Would it be possible to strip the decimals or specify 0,1,2 decimals to use for temperatures for the "WEATHER_LIST" tile?

The current setup doesnt look very clean:

![image](https://user-images.githubusercontent.com/27990031/42604197-d3020436-8571-11e8-82ed-55953ae40046.png)

**Comment by Evgeny-** [comment]
There's a way, you can use anonymous functions, use `parseFieldValue` function from the context for each temperature, and then format each one. Not the easiest way to to this, but i don't think there's exist another way making it universal and simple.

**Comment by Evgeny-** [comment]
Here an example
```js
return {
   date: date,
   icon: "&sensor.dark_sky_icon_" + id + ".state",
   primary: function (item, entity) {
      var high = this.parseFieldValue("&sensor.dark_sky_daytime_high_temperature_"
         + id + ".state", item, entity);
      var low = this.parseFieldValue("&sensor.dark_sky_overnight_low_temperature_"
         + id + ".state", item, entity);
      var unit = this.parseFieldValue("&sensor.dark_sky_daytime_high_temperature_"
         + id + ".attributes.unit_of_measurement", item, entity);

      high = parseFloat(high);
      low = parseFloat(low);

      return low.toFixed(1) + ' - ' + high.toFixed(1) + unit;
   },
   secondary: secondary
}
```
