### ISSUE TITLE
Device Tracker Tile transitions even when only one slide is set

### ISSUE THREAD

**Issue by NilSkilz** [resoai/TileBoard#87]
My config for the tile:

```
{
   position: [1, 2],
   type: TYPES.DEVICE_TRACKER,
   id: 'device_tracker.iphone',
   map: 'google',
   states: {
      home: "Home",
      not_home: "Away",
      office: "Office",
   },
   zoomLevels: [12],
   slidesDelay: 2
},
```

So I've set only one zoom level, and no background image. The tile transitions from the map to a blank, black tile, and then back again.

**Comment by Evgeny-** [comment]
First slide is for picture from `attributes.entity_picture`.
If you want only map, set `zoomLevels: []` and use `bg` as an function that return url of the map

**Comment by Evgeny-** [comment]
Yes, our solution for this isn't perfect, because it wasn't created to be customisable. May be we should think about it.

**Comment by Evgeny-** [comment]
Ok, now you can hide entity picture. And it is hide automatically if there's none.

https://github.com/resoai/TileBoard/blob/master/TILE_EXAMPLES.md#device_tracker

**Comment by avandeputte** [comment]
You're awesome,  as always!
