### ISSUE TITLE
parseVariable() function breaks urls with querystrings

### ISSUE THREAD

**Issue by NilSkilz** [resoai/TileBoard#89]
I'm using a url with a query string to pull graphs from grafana into the dashboard. The urls have a querystring, which is broken by the parseVariable() function - due to your "&" prefixes.

as an example:
`www.example.com?foo=foo&bar=bar`
becomes
`www.example.com?foo=foo&bar=null`

**Comment by Evgeny-** [comment]
Well i can suggest use anonymous function that will return your url, unless we don't decide how to rewrite parser and it won't brake things much.

**Comment by resoai** [comment]
@NilSkilz Could you please confirm that the matter is resolved?

**Comment by NilSkilz** [comment]
yup, good work!
