### ISSUE TITLE
Media player source name is ugly

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#94]
The media source name shown on media player tile is "ugly" (non-descriptive). At least for the component that I'm using to control my Sony Bravia TV (https://github.com/gerard33/sony-bravia-ha).

Let me show that in pictures:

This is how the tile looks like with any of the 4 HDMI sources selected (it shows same for all):
![hdmi-source](https://user-images.githubusercontent.com/153197/42847612-cb35dd36-8a1c-11e8-84c9-7ed816454609.png)

As you can see, it shows "extInput:hdmi" which is neither precise enough (shows same for all 4 hdmis) nor clean.

This is the list of sources shown on clicking the source name:
![source-list](https://user-images.githubusercontent.com/153197/42847678-fc1bfb7e-8a1c-11e8-8489-442a5256ea48.png)

That looks nice and correct.

Here is the state snapshot of the entity:
```
{
    "entity_id": "media_player.mybraviatv",
    "state": "on",
    "attributes": {
        "volume_level": 0.1,
        "is_volume_muted": false,
        "media_content_id": "HDMI 4",
        "media_content_type": "tvshow",
        "media_title": "HDMI 4",
        "source": "extInput:hdmi",
        "source_list": [
            "HDMI 1",
            "HDMI 2",
            "HDMI 3/ARC",
            "HDMI 4",
            "AV 1",
            "AV 2/Component"
        ],
        "friendly_name": "MyBraviaTV",
        "supported_features": 23997,
    },
    "last_changed": "2018-07-17T21:46:06.771413+00:00",
    "last_updated": "2018-07-17T21:47:04.259447+00:00"
}
```

As you can see here, the better choice to show would be either `attributes.media_title` or `attributes.media_content_id`. Not sure which one is more "standard" or common.

**Comment by rchl** [comment]
Or possibly the component is doing a bad job here by not translating internal name to user-friendly one...

**Comment by resoai** [comment]
I have the very same issue as I'm a (not so) proud owner of 65' Sony Android TV (2015). We really need to test it as `media_title` could be showing name of the movie instead of the source etc. There could be situations where `media_title` could not be present at all etc. This could also be specific to that component.

**Comment by rchl** [comment]
I've created an issue for that component (referenced here) so we'll see if that can be fixed there.

As for TileBoard, I thought one can work-around it by disabling source and using `subtitle` instead, like:
```
...
hideSource: true,
subtitle: '@attributes.media_title',
...
```
but when turning on netflix for example, `media_title` (and also `source`) are disappearing completely...
```
"attributes": {
        "volume_level": 0.1,
        "is_volume_muted": false,
        "media_content_type": "tvshow",
        "media_series_title": "No info (resumed after pause or                                           app opened)",
        "source_list": [
            "HDMI 1",
            "HDMI 2",
            "HDMI 3/ARC",
            "HDMI 4",
            "AV 1",
            "AV 2/Component"
        ],
        "friendly_name": "MyBraviaTV",
        "supported_features": 23997,
        "_c": {
            "max": 100,
            "min": 0,
            "step": 2,
            "value": 10
        },
        "_sliderInited": true
    },
```

**Comment by resoai** [comment]
I have not looked at HA's code but I think what HA is doing is showing name of the source as long as source is within source_list array and simply `Source` title otherwise. If this is an adequate enough solution, we could easily do that.

**Comment by rchl** [comment]
Yes, that is true - it shows 'Source' when there is no `source` attribute.

**Comment by resoai** [comment]
We are doing the same thing in TileBoard already but we don't verify source against source_list.

**Comment by resoai** [comment]
The only logical solution would be to understand how HA's UI does it and do the same thing.

**Comment by Evgeny-** [comment]
I think it's your TV problem. But I'm not sure. 
See no reason why media title should be used instead source.

**Comment by rchl** [comment]
As I said, it's probably HA's component fault. But as @resoai pointed out, HA manages to show correct input name.

**Comment by rchl** [comment]
I think HA just shows `media_title` which makes it look like it shows correct source. But the source selector doesn't show selected source which is probably due to `source` not matching selected source from `source_list`. So there is nothing to fix in TileBoard IMO - feel free to close unless you see something that can be improved.
