### ISSUE TITLE
head.html template unused

### ISSUE THREAD

**Issue by rchl** [resoai/TileBoard#96]
This code from index.html is not used.
```
<script type="text/ng-template" id="head.html">
   <div class="page-head-content">
      <div class="page-head--left">
         <div class="page-head--time" ng-style="clockStyles()">
            <clock></clock>
         </div>
      </div>
      <div class="page-head--right">
      </div>
   </div>
</script>
```

I've been debugging my problem with double time showing and it was due to legacy `head: 'head.html` option in the config that seems no longer supported.

**Comment by resoai** [comment]
It is deprecated but we will (probably) have top keep it for some time to allow people to  switch to the new header.

**Comment by rchl** [comment]
Maybe add some deprecation note in the template to force people to switch?

**Comment by Evgeny-** [comment]
We probably will
