### ISSUE TITLE
Bug: Large entity size doesn't impact all elements

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#98]
Currently, if you need to select say climate operation mode or fan speed, there is a list popup which is quite small and difficult to read from a distance. 

Can this list be displayed in a manner similar to alarm tile with bigger buttons? Or at least the font size increased?

**Comment by resoai** [comment]
Climate control uses same control as input_select. I don't find it being too small or difficult to read, in fact it mimics Windows 10 behavior. A popup is only good when there is no other choice but to have one. 

You can make font bigger using custom css.

**Comment by mouth4war** [comment]
Yeah increasing the font size will be an easier fix.

Maybe link the font size to the entity size? 

If large entity size, then font size of input selects in all tiles (media_player, fan, climate, input_select etc) will adjust. Sounds good?

**Comment by resoai** [comment]
This is all very individual and current defaults are the best for screen sizes we have tested it on. But please feel free to adjust the size in custom.css file which will not be overwritten by an update.

**Comment by mouth4war** [comment]
Alright will give it a try. Which elements do I need to modify?

**Comment by mouth4war** [comment]
Hey @resoai  . I've been looking for the right element but no luck so far. Help pls.

I've found another tiny font that i fixed using custom.css. I'm using COMPACT theme and LARGE entity size as recommended in documentation for an 8in tablet. Font size was 16.8 so I increased to 32. 
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/30283635/42936475-c94f09fe-8b69-11e8-8717-87a8f72ac176.png">


.-theme-winphone .item-entity.-select .item-entity--value,
.-theme-mobile .item-entity.-select .item-entity--value,
.-theme-compact .item-entity.-select .item-entity--value {
  font-size: 32px;
}

**Comment by mouth4war** [comment]
The final one, is this element (controls icon size of fan tile):

.item-entity.-with-select .item-entity--icon,
.-big-entity .item-entity--icon {
  font-size: 72px;
}

Now, the icons are the same size.

![image](https://user-images.githubusercontent.com/30283635/42961454-6adbf696-8bac-11e8-8f0d-a8290793a4ba.png)
