### ISSUE TITLE
Feature Request: Fan tile speed selection on long press

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#99]
The fan tile doesn't increase icon size which means the icon is much smaller compared to other tiles if you use LARGE entity size. 

Can the speed be displayed in addition to state in the top right corner? This will remove the speed text and allow icon to be large like other tiles.

And to set speed, long press to see a set of tiles just like alarm tile.

**Comment by resoai** [comment]
Speed can not be in the state and is unnatural behavior. We have player with the fan tile for almost a week and this is the best and most logical way to have it at the moment.

There is no long-press on the alarm tile.

**Comment by resoai** [comment]
There was no icon before at all, we've managed to squeeze one inside while keeping the speed selection.  When you say it looks too small, can you show me a screenshot please?

**Comment by mouth4war** [comment]
![screenshot_2018-07-19-04-17-26_de ozerov fully](https://user-images.githubusercontent.com/30283635/42911986-cb34d3ca-8b0a-11e8-81d6-164563b59b6e.png)

**Comment by resoai** [comment]
Looks OK to me. You probably need to set group height to 4 to have that automatons on the right to be in line with the rest.

**Comment by mouth4war** [comment]
Ah thanks for the tip. Closing.
